/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.quanLy;

import bus.QuanLyTau_BUS;
import entity.Tau;
import enums.TrangThaiTau;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import static utils.FormatUtil.formatDate;

/**
 *
 * @author LAPTOP DELL
 */
public class QuanLyTau_GUI extends javax.swing.JPanel {
    
    private QuanLyTau_BUS bus;
    private DefaultTableModel tblModel_thongtinTau;
    
    public QuanLyTau_GUI() {
        initComponents();
        init();
    }
    
     private void init(){
       bus = new QuanLyTau_BUS();
       tblModel_thongtinTau = new DefaultTableModel(new String[]{"Mã tàu","Tên tàu","Số lượng toa","Sức chứa","Ngày hoạt động","Trạng thái"},0);
       tbl_tau.setModel(tblModel_thongtinTau);
         getTableData(bus.getAllTau());
   }
     
    private void getTableData(ArrayList<Tau> dsTau) {
    // Xóa toàn bộ dữ liệu cũ trên bảng
    tblModel_thongtinTau.setRowCount(0);
    
    for(Tau tau : dsTau){
        String[]newRow = {tau.getMaTau(),tau.getTenTau(), String.valueOf(tau.getSoToaTau()), 
                            String.valueOf(tau.getSucChua()), formatDate(tau.getNgayHoatDong()), tau.getTrangThai().getDisplayName()};
        tblModel_thongtinTau.addRow(newRow);
    }
}
    
    private void getThongTinTau() {
    int row = tbl_tau.getSelectedRow(); // lấy dòng được chọn
    if (row != -1) {
        // Lấy dữ liệu từng cột
        String maTau = tbl_tau.getValueAt(row, 0).toString();
        String tenTau = tbl_tau.getValueAt(row, 1).toString();
        int soToaTau = Integer.parseInt(tbl_tau.getValueAt(row, 2).toString());
        int sucChua = Integer.parseInt(tbl_tau.getValueAt(row, 3).toString());
        String ngayHoatDongStr = tbl_tau.getValueAt(row, 4).toString();
        String trangThaiStr = tbl_tau.getValueAt(row, 5).toString();

        // Gán dữ liệu lên textfield
        txt_maTau.setText(maTau);
        txt_tenTau.setText(tenTau);
        txt_soLuongToa.setText(String.valueOf(soToaTau));
        txt_sucChua.setText(String.valueOf(sucChua));

        // Gán trạng thái vào combobox
        for (int i = 0; i < cbo_tt.getItemCount(); i++) {
            String item = cbo_tt.getItemAt(i).trim();
            if (item.equalsIgnoreCase(trangThaiStr.trim())) {
                cbo_tt.setSelectedIndex(i);
                break;
            }
        }
        // Gán ngày hoạt động vào JDateChooser
        if (ngayHoatDongStr != null && !ngayHoatDongStr.isEmpty()) {
            try {
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                LocalDate localDate = LocalDate.parse(ngayHoatDongStr, formatter);
                java.util.Date ngayHoatDong = java.sql.Date.valueOf(localDate);
                txt_ngayHD.setDate(ngayHoatDong);
            } catch (Exception e) { 
                txt_ngayHD.setDate(null);
            }
        } else {
            txt_ngayHD.setDate(null);
        }
    }
}

    private void xoaTrang() {
        // Xóa các ô nhập liệu văn bản
        txt_maTau.setText("");
        txt_tenTau.setText("");
        txt_soLuongToa.setText("");
        txt_sucChua.setText("");
        txt_timKiem.setText("");

         // Xóa ngày sinh
        if (txt_ngayHD.getDate() != null) {
        txt_ngayHD.setDate(null);
        }
  
         if (cbo_tt.getItemCount() > 0) {
         cbo_tt.setSelectedIndex(0); 
     }
        // Bỏ chọn hàng đang được chọn trong bảng (nếu có)
        tbl_tau.clearSelection();
    }
    
    private void handleActionTimKiem() {
        String ma = txt_timKiem.getText().trim();
        getTableData(bus.getTauTheoMa(ma));
    }
     
     
    private void handleActionLoc() {
    // Lấy giá trị từ combobox
    String trangThai = (String) cbo_trangThai.getSelectedItem();
        getTableData(bus.filter(trangThai));
}
    private void handleActionLamMoi() {
            tbl_tau.clearSelection();
            getTableData(bus.getAllTau());
            txt_timKiem.setText("Nhập mã tàu cần tìm...");
            txt_timKiem.setForeground(Color.GRAY);
        }

        
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnl_top = new javax.swing.JPanel();
        pnl_timKiem = new javax.swing.JPanel();
        txt_timKiem = new javax.swing.JTextField();
        pnl_btnTimKiem = new javax.swing.JPanel();
        btn_timKiem = new javax.swing.JButton();
        pnl_cta = new javax.swing.JPanel();
        cbo_trangThai = new javax.swing.JComboBox<>();
        btn_Loc = new javax.swing.JButton();
        btn_Reset = new javax.swing.JButton();
        pnl_center = new javax.swing.JPanel();
        spl_container = new javax.swing.JSplitPane();
        src_nhanVien = new javax.swing.JScrollPane();
        tbl_tau = new javax.swing.JTable();
        pnl_container = new javax.swing.JPanel();
        pnl_thongTinNhanVien = new javax.swing.JPanel();
        pnl_maTau = new javax.swing.JPanel();
        lbl_maTau = new javax.swing.JLabel();
        txt_maTau = new javax.swing.JTextField();
        pnl_tenTau = new javax.swing.JPanel();
        lbl_tenTau = new javax.swing.JLabel();
        txt_tenTau = new javax.swing.JTextField();
        pnl_slToa = new javax.swing.JPanel();
        lbl_soLuongToa = new javax.swing.JLabel();
        txt_soLuongToa = new javax.swing.JTextField();
        pnl_sucChua = new javax.swing.JPanel();
        lbl_sucChua = new javax.swing.JLabel();
        txt_sucChua = new javax.swing.JTextField();
        pnl_ngayHD = new javax.swing.JPanel();
        lbl_NgayHD = new javax.swing.JLabel();
        txt_ngayHD = new com.toedter.calendar.JDateChooser();
        pnl_trangThai = new javax.swing.JPanel();
        lbl_trangThai = new javax.swing.JLabel();
        cbo_tt = new javax.swing.JComboBox<>();
        pnl_btnGroup = new javax.swing.JPanel();
        btn_them = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btn_xoaTrang = new javax.swing.JButton();
        btn_capNhat = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã tàu", "Tên tàu", "Ga đi", "Ga đến", "Ngày khởi hành", "Giá vé"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setLayout(new java.awt.BorderLayout());

        pnl_top.setBackground(new java.awt.Color(255, 255, 255));
        pnl_top.setMinimumSize(new java.awt.Dimension(20, 20));
        pnl_top.setPreferredSize(new java.awt.Dimension(1366, 50));
        pnl_top.setLayout(new javax.swing.BoxLayout(pnl_top, javax.swing.BoxLayout.LINE_AXIS));

        pnl_timKiem.setLayout(new javax.swing.BoxLayout(pnl_timKiem, javax.swing.BoxLayout.LINE_AXIS));

        txt_timKiem.setPreferredSize(new java.awt.Dimension(700, 30));
        txt_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timKiemActionPerformed(evt);
            }
        });
        pnl_timKiem.add(txt_timKiem);

        pnl_btnTimKiem.setLayout(new java.awt.BorderLayout());

        btn_timKiem.setText("Tìm kiếm");
        btn_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timKiemActionPerformed(evt);
            }
        });
        pnl_btnTimKiem.add(btn_timKiem, java.awt.BorderLayout.CENTER);

        pnl_timKiem.add(pnl_btnTimKiem);

        pnl_top.add(pnl_timKiem);

        pnl_cta.setPreferredSize(new java.awt.Dimension(500, 50));
        pnl_cta.setLayout(new java.awt.GridLayout(1, 0));

        cbo_trangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trạng thái", "Hoạt động", "Bảo trì", "Ngừng hoạt động" }));
        cbo_trangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_trangThaiActionPerformed(evt);
            }
        });
        pnl_cta.add(cbo_trangThai);

        btn_Loc.setText("Lọc");
        btn_Loc.setMaximumSize(new java.awt.Dimension(100, 50));
        btn_Loc.setPreferredSize(new java.awt.Dimension(100, 50));
        btn_Loc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LocActionPerformed(evt);
            }
        });
        pnl_cta.add(btn_Loc);

        btn_Reset.setText("Reset");
        btn_Reset.setMaximumSize(new java.awt.Dimension(100, 50));
        btn_Reset.setPreferredSize(new java.awt.Dimension(100, 50));
        btn_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResetActionPerformed(evt);
            }
        });
        pnl_cta.add(btn_Reset);

        pnl_top.add(pnl_cta);

        add(pnl_top, java.awt.BorderLayout.PAGE_START);

        pnl_center.setLayout(new javax.swing.BoxLayout(pnl_center, javax.swing.BoxLayout.LINE_AXIS));

        spl_container.setResizeWeight(0.7);
        spl_container.setMinimumSize(new java.awt.Dimension(805, 416));
        spl_container.setPreferredSize(new java.awt.Dimension(1055, 718));

        src_nhanVien.setMinimumSize(new java.awt.Dimension(400, 20));
        src_nhanVien.setPreferredSize(new java.awt.Dimension(800, 402));

        tbl_tau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã tàu", "Tên tàu", "Số lượng toa", "Sức chứa", "Ngày hoạt động", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_tau.setMaximumSize(new java.awt.Dimension(1000, 80));
        tbl_tau.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl_tau.setShowGrid(false);
        tbl_tau.setShowHorizontalLines(true);
        tbl_tau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_tauMouseClicked(evt);
            }
        });
        src_nhanVien.setViewportView(tbl_tau);

        spl_container.setLeftComponent(src_nhanVien);

        pnl_container.setBackground(new java.awt.Color(255, 255, 255));
        pnl_container.setMinimumSize(new java.awt.Dimension(400, 379));
        pnl_container.setPreferredSize(new java.awt.Dimension(250, 100));
        pnl_container.setLayout(new java.awt.BorderLayout());

        pnl_thongTinNhanVien.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin tàu"), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        pnl_thongTinNhanVien.setLayout(new javax.swing.BoxLayout(pnl_thongTinNhanVien, javax.swing.BoxLayout.Y_AXIS));

        pnl_maTau.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        pnl_maTau.setMinimumSize(new java.awt.Dimension(118, 6));
        pnl_maTau.setPreferredSize(new java.awt.Dimension(230, 50));
        pnl_maTau.setLayout(new javax.swing.BoxLayout(pnl_maTau, javax.swing.BoxLayout.X_AXIS));

        lbl_maTau.setText("Mã tàu:");
        lbl_maTau.setMaximumSize(new java.awt.Dimension(45, 16));
        lbl_maTau.setMinimumSize(new java.awt.Dimension(45, 16));
        lbl_maTau.setPreferredSize(new java.awt.Dimension(100, 16));
        pnl_maTau.add(lbl_maTau);

        txt_maTau.setEnabled(false);
        txt_maTau.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        txt_maTau.setPreferredSize(new java.awt.Dimension(64, 40));
        txt_maTau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maTauActionPerformed(evt);
            }
        });
        pnl_maTau.add(txt_maTau);

        pnl_thongTinNhanVien.add(pnl_maTau);

        pnl_tenTau.setMaximumSize(pnl_maTau.getMaximumSize());
        pnl_tenTau.setPreferredSize(pnl_maTau.getPreferredSize());
        pnl_tenTau.setLayout(new javax.swing.BoxLayout(pnl_tenTau, javax.swing.BoxLayout.LINE_AXIS));

        lbl_tenTau.setText("Tên tàu:");
        lbl_tenTau.setMaximumSize(lbl_maTau.getMaximumSize());
        lbl_tenTau.setMinimumSize(new java.awt.Dimension(45, 16));
        lbl_tenTau.setPreferredSize(lbl_maTau.getPreferredSize());
        pnl_tenTau.add(lbl_tenTau);

        txt_tenTau.setMaximumSize(txt_maTau.getMaximumSize());
        txt_tenTau.setPreferredSize(txt_maTau.getPreferredSize());
        pnl_tenTau.add(txt_tenTau);

        pnl_thongTinNhanVien.add(pnl_tenTau);

        pnl_slToa.setMaximumSize(pnl_maTau.getMaximumSize());
        pnl_slToa.setMinimumSize(new java.awt.Dimension(118, 6));
        pnl_slToa.setPreferredSize(new java.awt.Dimension(230, 50));
        pnl_slToa.setLayout(new javax.swing.BoxLayout(pnl_slToa, javax.swing.BoxLayout.LINE_AXIS));

        lbl_soLuongToa.setText("Số lượng toa:");
        lbl_soLuongToa.setMaximumSize(lbl_maTau.getMaximumSize());
        lbl_soLuongToa.setPreferredSize(lbl_maTau.getPreferredSize());
        pnl_slToa.add(lbl_soLuongToa);

        txt_soLuongToa.setMaximumSize(txt_maTau.getMaximumSize());
        txt_soLuongToa.setPreferredSize(txt_maTau.getPreferredSize());
        txt_soLuongToa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_soLuongToaActionPerformed(evt);
            }
        });
        pnl_slToa.add(txt_soLuongToa);

        pnl_thongTinNhanVien.add(pnl_slToa);

        pnl_sucChua.setMaximumSize(pnl_maTau.getMaximumSize());
        pnl_sucChua.setMinimumSize(new java.awt.Dimension(118, 6));
        pnl_sucChua.setPreferredSize(pnl_maTau.getPreferredSize());
        pnl_sucChua.setLayout(new javax.swing.BoxLayout(pnl_sucChua, javax.swing.BoxLayout.LINE_AXIS));

        lbl_sucChua.setText("Sức chứa:");
        lbl_sucChua.setMaximumSize(new java.awt.Dimension(45, 16));
        lbl_sucChua.setMinimumSize(new java.awt.Dimension(45, 16));
        lbl_sucChua.setPreferredSize(new java.awt.Dimension(100, 16));
        pnl_sucChua.add(lbl_sucChua);

        txt_sucChua.setMaximumSize(txt_maTau.getMaximumSize());
        txt_sucChua.setMinimumSize(new java.awt.Dimension(64, 30));
        txt_sucChua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sucChuaActionPerformed(evt);
            }
        });
        pnl_sucChua.add(txt_sucChua);

        pnl_thongTinNhanVien.add(pnl_sucChua);

        pnl_ngayHD.setMaximumSize(pnl_maTau.getMaximumSize());
        pnl_ngayHD.setMinimumSize(new java.awt.Dimension(118, 6));
        pnl_ngayHD.setPreferredSize(pnl_maTau.getPreferredSize());
        pnl_ngayHD.setLayout(new javax.swing.BoxLayout(pnl_ngayHD, javax.swing.BoxLayout.LINE_AXIS));

        lbl_NgayHD.setText("Ngày hoạt động:");
        lbl_NgayHD.setMaximumSize(new java.awt.Dimension(45, 16));
        lbl_NgayHD.setMinimumSize(new java.awt.Dimension(45, 16));
        lbl_NgayHD.setPreferredSize(new java.awt.Dimension(100, 16));
        pnl_ngayHD.add(lbl_NgayHD);
        pnl_ngayHD.add(txt_ngayHD);

        pnl_thongTinNhanVien.add(pnl_ngayHD);

        pnl_trangThai.setMaximumSize(pnl_maTau.getMaximumSize());
        pnl_trangThai.setPreferredSize(new java.awt.Dimension(230, 50));
        pnl_trangThai.setLayout(new javax.swing.BoxLayout(pnl_trangThai, javax.swing.BoxLayout.LINE_AXIS));

        lbl_trangThai.setText("Trạng thái:");
        lbl_trangThai.setPreferredSize(new java.awt.Dimension(100, 16));
        pnl_trangThai.add(lbl_trangThai);

        cbo_tt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bảo trì", "Hoạt động", "Ngừng hoạt động" }));
        cbo_tt.setMaximumSize(new java.awt.Dimension(32767, 40));
        cbo_tt.setPreferredSize(new java.awt.Dimension(230, 40));
        pnl_trangThai.add(cbo_tt);

        pnl_thongTinNhanVien.add(pnl_trangThai);

        pnl_container.add(pnl_thongTinNhanVien, java.awt.BorderLayout.CENTER);

        pnl_btnGroup.setMaximumSize(new java.awt.Dimension(260, 100));
        pnl_btnGroup.setMinimumSize(new java.awt.Dimension(220, 100));
        pnl_btnGroup.setLayout(new java.awt.BorderLayout());

        btn_them.setBackground(new java.awt.Color(123, 17, 19));
        btn_them.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_them.setForeground(new java.awt.Color(255, 255, 255));
        btn_them.setText("Đưa vào hoạt động");
        btn_them.setMaximumSize(new java.awt.Dimension(139, 23));
        btn_them.setMinimumSize(new java.awt.Dimension(139, 23));
        btn_them.setPreferredSize(new java.awt.Dimension(72, 50));
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });
        pnl_btnGroup.add(btn_them, java.awt.BorderLayout.PAGE_END);

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 2, 0));
        jPanel5.setLayout(new java.awt.GridLayout(1, 2, 5, 5));

        btn_xoaTrang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_xoaTrang.setText("Xóa trắng");
        btn_xoaTrang.setMaximumSize(new java.awt.Dimension(120, 50));
        btn_xoaTrang.setPreferredSize(new java.awt.Dimension(120, 50));
        btn_xoaTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaTrangActionPerformed(evt);
            }
        });
        jPanel5.add(btn_xoaTrang);

        btn_capNhat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_capNhat.setText("Cập nhật");
        btn_capNhat.setMaximumSize(new java.awt.Dimension(120, 50));
        btn_capNhat.setPreferredSize(new java.awt.Dimension(120, 50));
        btn_capNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capNhatActionPerformed(evt);
            }
        });
        jPanel5.add(btn_capNhat);

        pnl_btnGroup.add(jPanel5, java.awt.BorderLayout.CENTER);

        pnl_container.add(pnl_btnGroup, java.awt.BorderLayout.PAGE_END);

        spl_container.setRightComponent(pnl_container);

        pnl_center.add(spl_container);

        add(pnl_center, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timKiemActionPerformed

    private void cbo_trangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_trangThaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_trangThaiActionPerformed

    private void txt_maTauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maTauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maTauActionPerformed

    private void txt_sucChuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sucChuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sucChuaActionPerformed

    private void btn_capNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capNhatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_capNhatActionPerformed

    private void txt_soLuongToaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_soLuongToaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_soLuongToaActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_xoaTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaTrangActionPerformed
        xoaTrang();
    }//GEN-LAST:event_btn_xoaTrangActionPerformed

    private void tbl_tauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_tauMouseClicked
        getThongTinTau();
    }//GEN-LAST:event_tbl_tauMouseClicked

    private void btn_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timKiemActionPerformed
        handleActionTimKiem();
    }//GEN-LAST:event_btn_timKiemActionPerformed

    private void btn_LocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LocActionPerformed
        handleActionLoc();
    }//GEN-LAST:event_btn_LocActionPerformed

    private void btn_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResetActionPerformed
        handleActionLamMoi();
    }//GEN-LAST:event_btn_ResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Loc;
    private javax.swing.JButton btn_Reset;
    private javax.swing.JButton btn_capNhat;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_timKiem;
    private javax.swing.JButton btn_xoaTrang;
    private javax.swing.JComboBox<String> cbo_trangThai;
    private javax.swing.JComboBox<String> cbo_tt;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_NgayHD;
    private javax.swing.JLabel lbl_maTau;
    private javax.swing.JLabel lbl_soLuongToa;
    private javax.swing.JLabel lbl_sucChua;
    private javax.swing.JLabel lbl_tenTau;
    private javax.swing.JLabel lbl_trangThai;
    private javax.swing.JPanel pnl_btnGroup;
    private javax.swing.JPanel pnl_btnTimKiem;
    private javax.swing.JPanel pnl_center;
    private javax.swing.JPanel pnl_container;
    private javax.swing.JPanel pnl_cta;
    private javax.swing.JPanel pnl_maTau;
    private javax.swing.JPanel pnl_ngayHD;
    private javax.swing.JPanel pnl_slToa;
    private javax.swing.JPanel pnl_sucChua;
    private javax.swing.JPanel pnl_tenTau;
    private javax.swing.JPanel pnl_thongTinNhanVien;
    private javax.swing.JPanel pnl_timKiem;
    private javax.swing.JPanel pnl_top;
    private javax.swing.JPanel pnl_trangThai;
    private javax.swing.JSplitPane spl_container;
    private javax.swing.JScrollPane src_nhanVien;
    private javax.swing.JTable tbl_tau;
    private javax.swing.JTextField txt_maTau;
    private com.toedter.calendar.JDateChooser txt_ngayHD;
    private javax.swing.JTextField txt_soLuongToa;
    private javax.swing.JTextField txt_sucChua;
    private javax.swing.JTextField txt_tenTau;
    private javax.swing.JTextField txt_timKiem;
    // End of variables declaration//GEN-END:variables
}
