/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 *
 * @author CÔNG HOÀNG
 */
public class Loading_GUI extends javax.swing.JFrame {
    
    private int value = 0;
    private static int dots = 0;

    /**
     * Creates new form Loading_GUI
     */
    public Loading_GUI() {
        initComponents();
        
//      Loading text animation
        new Timer(500, (ActionEvent evt) -> {
            dots++;
            if (dots > 3) {
                dots = 1;
            }

            String dotsString = "";
            for (int i = 0; i < dots; i++) {
                dotsString += ".";
            }
            lbl_loading.setText("Đang kết nối" + dotsString);
        }).start();

        Timer timer = new Timer(2500, (ActionEvent evt) -> {
            this.dispose();
        });
        timer.setRepeats(false);
        timer.start();

//      Loading bar animation
        new Timer(1, (ActionEvent evt) -> {
            if (value < 100) {
                value += 1;
                progressbar_status.setValue(value);
            }
        }).start();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_container = new javax.swing.JPanel();
        lbl_logo = new javax.swing.JLabel();
        lbl_loading = new javax.swing.JLabel();
        progressbar_status = new javax.swing.JProgressBar();
        pnl_decoration1 = new javax.swing.JPanel();
        pnl_decoration2 = new javax.swing.JPanel();
        pnl_decoration3 = new javax.swing.JPanel();
        pnl_decoration4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(400, 255));
        setMinimumSize(new java.awt.Dimension(400, 255));
        setName("Loading"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(400, 255));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        pnl_container.setBackground(new java.awt.Color(123, 17, 19));
        pnl_container.setMaximumSize(new java.awt.Dimension(400, 255));
        pnl_container.setMinimumSize(new java.awt.Dimension(400, 255));
        pnl_container.setLayout(null);

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Logo.png"))); // NOI18N
        lbl_logo.setMaximumSize(new java.awt.Dimension(180, 180));
        lbl_logo.setMinimumSize(new java.awt.Dimension(180, 180));
        lbl_logo.setPreferredSize(new java.awt.Dimension(180, 180));
        pnl_container.add(lbl_logo);
        lbl_logo.setBounds(110, 0, 180, 180);

        lbl_loading.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lbl_loading.setForeground(new java.awt.Color(255, 255, 255));
        lbl_loading.setText("Đang kết nối...");
        pnl_container.add(lbl_loading);
        lbl_loading.setBounds(150, 180, 101, 21);

        progressbar_status.setForeground(new java.awt.Color(240, 104, 107));
        progressbar_status.setValue(60);
        pnl_container.add(progressbar_status);
        progressbar_status.setBounds(100, 220, 200, 4);

        pnl_decoration1.setBackground(new Color(0xEE, 0x55, 0x77, 55));
        pnl_decoration1.setMaximumSize(new java.awt.Dimension(50, 50));
        pnl_decoration1.setMinimumSize(new java.awt.Dimension(50, 50));
        pnl_decoration1.setPreferredSize(new java.awt.Dimension(50, 50));

        pnl_decoration1.putClientProperty(FlatClientProperties.STYLE, "arc:9999;");

        javax.swing.GroupLayout pnl_decoration1Layout = new javax.swing.GroupLayout(pnl_decoration1);
        pnl_decoration1.setLayout(pnl_decoration1Layout);
        pnl_decoration1Layout.setHorizontalGroup(
            pnl_decoration1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pnl_decoration1Layout.setVerticalGroup(
            pnl_decoration1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pnl_container.add(pnl_decoration1);
        pnl_decoration1.setBounds(330, 20, 50, 50);

        pnl_decoration2.setBackground(new Color(0xEE, 0x55, 0x77, 55));
        pnl_decoration2.setMaximumSize(new java.awt.Dimension(100, 100));
        pnl_decoration2.setMinimumSize(new java.awt.Dimension(100, 100));

        pnl_decoration2.putClientProperty(FlatClientProperties.STYLE, "arc:9999;");

        javax.swing.GroupLayout pnl_decoration2Layout = new javax.swing.GroupLayout(pnl_decoration2);
        pnl_decoration2.setLayout(pnl_decoration2Layout);
        pnl_decoration2Layout.setHorizontalGroup(
            pnl_decoration2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pnl_decoration2Layout.setVerticalGroup(
            pnl_decoration2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pnl_container.add(pnl_decoration2);
        pnl_decoration2.setBounds(20, 10, 90, 90);

        pnl_decoration3.setBackground(new Color(0xEE, 0x55, 0x77, 55));
        pnl_decoration3.setMaximumSize(new java.awt.Dimension(100, 100));
        pnl_decoration3.setMinimumSize(new java.awt.Dimension(100, 100));

        pnl_decoration3.putClientProperty(FlatClientProperties.STYLE, "arc:9999;");

        javax.swing.GroupLayout pnl_decoration3Layout = new javax.swing.GroupLayout(pnl_decoration3);
        pnl_decoration3.setLayout(pnl_decoration3Layout);
        pnl_decoration3Layout.setHorizontalGroup(
            pnl_decoration3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pnl_decoration3Layout.setVerticalGroup(
            pnl_decoration3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pnl_container.add(pnl_decoration3);
        pnl_decoration3.setBounds(320, 140, 80, 80);

        pnl_decoration4.setBackground(new Color(0xEE, 0x55, 0x77, 55));
        pnl_decoration4.setMaximumSize(new java.awt.Dimension(80, 80));
        pnl_decoration4.setMinimumSize(new java.awt.Dimension(80, 80));
        pnl_decoration4.setPreferredSize(new java.awt.Dimension(80, 80));

        pnl_decoration4.putClientProperty(FlatClientProperties.STYLE, "arc:9999;");

        javax.swing.GroupLayout pnl_decoration4Layout = new javax.swing.GroupLayout(pnl_decoration4);
        pnl_decoration4.setLayout(pnl_decoration4Layout);
        pnl_decoration4Layout.setHorizontalGroup(
            pnl_decoration4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pnl_decoration4Layout.setVerticalGroup(
            pnl_decoration4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pnl_container.add(pnl_decoration4);
        pnl_decoration4.setBounds(-20, 120, 100, 100);

        pnl_container.putClientProperty(FlatClientProperties.STYLE, "background:rgb(123,17,19);" + "arc:8;");

        getContentPane().add(pnl_container, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        // Set Look and Feel FlatLaf
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Không thể khởi tạo FlatLaf");
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loading_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_loading;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JPanel pnl_container;
    private javax.swing.JPanel pnl_decoration1;
    private javax.swing.JPanel pnl_decoration2;
    private javax.swing.JPanel pnl_decoration3;
    private javax.swing.JPanel pnl_decoration4;
    private javax.swing.JProgressBar progressbar_status;
    // End of variables declaration//GEN-END:variables
}
