/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import bus.Login_BUS;
import com.formdev.flatlaf.FlatClientProperties;
import dao.NhanVien_DAO;
import entity.NhanVien;
import javax.swing.SwingWorker;
import main.Application;
import raven.toast.Notifications;

/**
 *
 * @author CÔNG HOÀNG
 */
public class Login_GUI extends javax.swing.JPanel {
    private final Login_BUS log_BUS = new Login_BUS();
    private final NhanVien_DAO nhanVienDAO = new NhanVien_DAO();
    /**
     * Creates new form Login
     */
    public Login_GUI() {
        initComponents();
        System.out.println(getClass().getResource("/icons/eye.png"));
        txt_taiKhoan.setText("0912345678");
        txt_matKhau.setText("6uZXqeMV");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_logo = new javax.swing.JPanel();
        lbl_logo = new javax.swing.JLabel();
        pnl_container = new javax.swing.JPanel();
        pnl_center = new javax.swing.JPanel();
        pnl_login = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 150), new java.awt.Dimension(0, 50), new java.awt.Dimension(32767, 150));
        jPanel7 = new javax.swing.JPanel();
        lbl_header1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lbl_taiKhoan = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txt_taiKhoan = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        lbl_matKhau = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txt_matKhau = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        lbl_quenMatKhau = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_dangNhap = new javax.swing.JButton();
        pnl_quenMatKhau = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 150), new java.awt.Dimension(0, 50), new java.awt.Dimension(32767, 150));
        jPanel8 = new javax.swing.JPanel();
        lbl_header2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lbl_taiKhoan1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        txt_taiKhoan1 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        lbl_email = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        txt_email = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        lbl_dangNhap = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        btn_layMatKhau = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1200, 650));
        setMinimumSize(new java.awt.Dimension(1200, 650));
        setLayout(new java.awt.BorderLayout());

        pnl_logo.setBackground(new java.awt.Color(123, 17, 19));
        pnl_logo.setMaximumSize(new java.awt.Dimension(630, 650));
        pnl_logo.setMinimumSize(new java.awt.Dimension(630, 650));
        pnl_logo.setLayout(new java.awt.BorderLayout());

        lbl_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Large_logo.png"))); // NOI18N
        lbl_logo.setMaximumSize(new java.awt.Dimension(630, 650));
        lbl_logo.setMinimumSize(new java.awt.Dimension(630, 650));
        lbl_logo.setPreferredSize(new java.awt.Dimension(630, 650));
        pnl_logo.add(lbl_logo, java.awt.BorderLayout.CENTER);

        add(pnl_logo, java.awt.BorderLayout.LINE_START);

        pnl_container.setBackground(new java.awt.Color(255, 255, 255));
        pnl_container.setMaximumSize(new java.awt.Dimension(570, 650));
        pnl_container.setMinimumSize(new java.awt.Dimension(570, 650));
        pnl_container.setPreferredSize(new java.awt.Dimension(570, 650));
        pnl_container.setLayout(new java.awt.BorderLayout());

        pnl_center.setBackground(new java.awt.Color(255, 255, 255));
        pnl_center.setMaximumSize(new java.awt.Dimension(400, 650));
        pnl_center.setMinimumSize(new java.awt.Dimension(400, 650));
        pnl_center.setPreferredSize(new java.awt.Dimension(400, 530));

        pnl_login.setBackground(new java.awt.Color(255, 255, 255));
        pnl_login.setPreferredSize(new java.awt.Dimension(400, 520));
        pnl_login.setLayout(new javax.swing.BoxLayout(pnl_login, javax.swing.BoxLayout.Y_AXIS));
        pnl_login.add(filler1);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.BorderLayout());

        lbl_header1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_header1.setForeground(new java.awt.Color(123, 17, 19));
        lbl_header1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_header1.setText("ĐĂNG NHẬP");
        jPanel7.add(lbl_header1, java.awt.BorderLayout.CENTER);

        pnl_login.add(jPanel7);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(400, 15));
        jPanel6.setLayout(new java.awt.BorderLayout());

        lbl_taiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_taiKhoan.setText("Tài khoản");
        lbl_taiKhoan.setPreferredSize(new java.awt.Dimension(400, 15));
        jPanel6.add(lbl_taiKhoan, java.awt.BorderLayout.LINE_START);

        pnl_login.add(jPanel6);

        jPanel5.setMinimumSize(new java.awt.Dimension(64, 16));
        jPanel5.setLayout(new java.awt.BorderLayout());

        txt_taiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_taiKhoan.setMinimumSize(new java.awt.Dimension(64, 14));
        txt_taiKhoan.setPreferredSize(new java.awt.Dimension(64, 10));
        jPanel5.add(txt_taiKhoan, java.awt.BorderLayout.CENTER);
        txt_taiKhoan.putClientProperty(FlatClientProperties.STYLE,                                  
            "arc:10;" +                                                
            "focusWidth: 0"           
        );

        pnl_login.add(jPanel5);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(400, 15));
        jPanel4.setLayout(new java.awt.BorderLayout());

        lbl_matKhau.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_matKhau.setText("Mật khẩu");
        lbl_matKhau.setMaximumSize(new java.awt.Dimension(65, 15));
        lbl_matKhau.setMinimumSize(new java.awt.Dimension(65, 15));
        lbl_matKhau.setPreferredSize(new java.awt.Dimension(400, 15));
        jPanel4.add(lbl_matKhau, java.awt.BorderLayout.LINE_START);

        pnl_login.add(jPanel4);

        jPanel3.setLayout(new java.awt.BorderLayout());

        txt_matKhau.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_matKhau.setMinimumSize(new java.awt.Dimension(64, 14));
        txt_matKhau.setPreferredSize(new java.awt.Dimension(90, 10));
        jPanel3.add(txt_matKhau, java.awt.BorderLayout.CENTER);
        txt_matKhau.putClientProperty(FlatClientProperties.STYLE, "arc:10;" + "" + "showRevealButton:true;");

        pnl_login.add(jPanel3);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        lbl_quenMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbl_quenMatKhau.setForeground(new java.awt.Color(123, 17, 19));
        lbl_quenMatKhau.setText("Quên mật khẩu?");
        lbl_quenMatKhau.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_quenMatKhau.setPreferredSize(new java.awt.Dimension(110, 15));
        lbl_quenMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_quenMatKhauMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_quenMatKhau, java.awt.BorderLayout.LINE_END);

        pnl_login.add(jPanel2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 20));
        jPanel1.setLayout(new java.awt.BorderLayout());

        btn_dangNhap.setBackground(new java.awt.Color(123, 17, 19));
        btn_dangNhap.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_dangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btn_dangNhap.setText("Đăng nhập");
        btn_dangNhap.setOpaque(true);
        btn_dangNhap.setPreferredSize(new java.awt.Dimension(88, 18));
        btn_dangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangNhapActionPerformed(evt);
            }
        });
        btn_dangNhap.putClientProperty(FlatClientProperties.STYLE, "arc:10;");
        jPanel1.add(btn_dangNhap, java.awt.BorderLayout.CENTER);

        pnl_login.add(jPanel1);

        pnl_center.add(pnl_login);

        pnl_quenMatKhau.setBackground(new java.awt.Color(255, 255, 255));
        pnl_quenMatKhau.setPreferredSize(new java.awt.Dimension(400, 520));
        pnl_quenMatKhau.setLayout(new javax.swing.BoxLayout(pnl_quenMatKhau, javax.swing.BoxLayout.Y_AXIS));
        pnl_quenMatKhau.setVisible(false);
        pnl_quenMatKhau.add(filler2);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new java.awt.BorderLayout());

        lbl_header2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_header2.setForeground(new java.awt.Color(123, 17, 19));
        lbl_header2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_header2.setText("QUÊN MẬT KHẨU");
        jPanel8.add(lbl_header2, java.awt.BorderLayout.CENTER);

        pnl_quenMatKhau.add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.BorderLayout());

        lbl_taiKhoan1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_taiKhoan1.setText("Tài khoản");
        lbl_taiKhoan1.setPreferredSize(new java.awt.Dimension(400, 15));
        jPanel9.add(lbl_taiKhoan1, java.awt.BorderLayout.LINE_START);

        pnl_quenMatKhau.add(jPanel9);

        jPanel10.setMinimumSize(new java.awt.Dimension(64, 16));
        jPanel10.setLayout(new java.awt.BorderLayout());

        txt_taiKhoan1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_taiKhoan1.setMinimumSize(new java.awt.Dimension(64, 14));
        txt_taiKhoan1.setPreferredSize(new java.awt.Dimension(64, 10));
        jPanel10.add(txt_taiKhoan1, java.awt.BorderLayout.CENTER);
        txt_taiKhoan1.putClientProperty(FlatClientProperties.STYLE,                                  
            "arc:10;" +                                                
            "focusWidth: 0"           
        );

        pnl_quenMatKhau.add(jPanel10);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setPreferredSize(new java.awt.Dimension(400, 15));
        jPanel11.setLayout(new java.awt.BorderLayout());

        lbl_email.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_email.setText("Email");
        lbl_email.setMaximumSize(new java.awt.Dimension(38, 15));
        lbl_email.setMinimumSize(new java.awt.Dimension(38, 15));
        lbl_email.setPreferredSize(new java.awt.Dimension(400, 15));
        jPanel11.add(lbl_email, java.awt.BorderLayout.LINE_START);

        pnl_quenMatKhau.add(jPanel11);

        jPanel12.setLayout(new java.awt.BorderLayout());

        txt_email.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_email.setMinimumSize(new java.awt.Dimension(64, 14));
        txt_email.setPreferredSize(new java.awt.Dimension(64, 10));
        jPanel12.add(txt_email, java.awt.BorderLayout.CENTER);
        txt_email.putClientProperty(FlatClientProperties.STYLE,                                  
            "arc:10;" +                                                
            "focusWidth: 0"           
        );

        pnl_quenMatKhau.add(jPanel12);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new java.awt.BorderLayout());

        lbl_dangNhap.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbl_dangNhap.setForeground(new java.awt.Color(123, 17, 19));
        lbl_dangNhap.setText("Đăng nhập");
        lbl_dangNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_dangNhap.setPreferredSize(new java.awt.Dimension(75, 15));
        lbl_dangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_dangNhapMouseClicked(evt);
            }
        });
        jPanel13.add(lbl_dangNhap, java.awt.BorderLayout.LINE_END);

        pnl_quenMatKhau.add(jPanel13);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setMinimumSize(new java.awt.Dimension(400, 32));
        jPanel14.setPreferredSize(new java.awt.Dimension(400, 20));
        jPanel14.setLayout(new java.awt.BorderLayout());

        btn_layMatKhau.setBackground(new java.awt.Color(123, 17, 19));
        btn_layMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_layMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        btn_layMatKhau.setText("Lấy lại mật khẩu");
        btn_layMatKhau.setOpaque(true);
        btn_layMatKhau.setPreferredSize(new java.awt.Dimension(400, 18));
        btn_layMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_layMatKhauActionPerformed(evt);
            }
        });
        btn_layMatKhau.putClientProperty(FlatClientProperties.STYLE, "arc:10;");
        jPanel14.add(btn_layMatKhau, java.awt.BorderLayout.CENTER);

        pnl_quenMatKhau.add(jPanel14);

        pnl_center.add(pnl_quenMatKhau);

        pnl_container.add(pnl_center, java.awt.BorderLayout.CENTER);

        add(pnl_container, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_layMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_layMatKhauActionPerformed
        // TODO add your handling code here:
        String taiKhoan = txt_taiKhoan1.getText();
        String email = txt_email.getText();
        
        // Chạy bất đồng bộ
        SwingWorker<Void, Void> worker = new SwingWorker<>() {
            @Override
            protected Void doInBackground() throws Exception {
            // Code nặng (reset password, gửi email)
                log_BUS.resetPassword(taiKhoan, email);
                return null;
            }

            @Override
            protected void done() {
                try {
                    get(); // bắt exception nếu có trong doInBackground
                    Notifications.getInstance().show(Notifications.Type.SUCCESS, 
                    "Mật khẩu đã được cập nhật. Vui lòng đăng nhập lại!");
                } catch (Exception ex) {
                    Notifications.getInstance().show(Notifications.Type.ERROR, ex.getMessage());
                }
            }
    };

    worker.execute(); // chạy
    }//GEN-LAST:event_btn_layMatKhauActionPerformed

    private void lbl_quenMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_quenMatKhauMouseClicked
        // TODO add your handling code here:
        pnl_login.setVisible(false);
        pnl_quenMatKhau.setVisible(true);
        txt_taiKhoan1.requestFocus();
    }//GEN-LAST:event_lbl_quenMatKhauMouseClicked

    private void lbl_dangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_dangNhapMouseClicked
        // TODO add your handling code here:
        pnl_quenMatKhau.setVisible(false);
        pnl_login.setVisible(true);
        txt_taiKhoan.requestFocus();
    }//GEN-LAST:event_lbl_dangNhapMouseClicked

    private void btn_dangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangNhapActionPerformed
        // TODO add your handling code here:
        String taiKhoan = txt_taiKhoan.getText();
        String matKhau = String.copyValueOf(txt_matKhau.getPassword());

        try {
            NhanVien nhanVien = log_BUS.login(taiKhoan, matKhau);
            if (nhanVien != null && nhanVien.isTrangThai()) {
                Application.login(nhanVien);
            }
        } catch (Exception ex) {
            Notifications.getInstance().show(Notifications.Type.ERROR, ex.getMessage());
        }
    }//GEN-LAST:event_btn_dangNhapActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dangNhap;
    private javax.swing.JButton btn_layMatKhau;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbl_dangNhap;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_header1;
    private javax.swing.JLabel lbl_header2;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_matKhau;
    private javax.swing.JLabel lbl_quenMatKhau;
    private javax.swing.JLabel lbl_taiKhoan;
    private javax.swing.JLabel lbl_taiKhoan1;
    private javax.swing.JPanel pnl_center;
    private javax.swing.JPanel pnl_container;
    private javax.swing.JPanel pnl_login;
    private javax.swing.JPanel pnl_logo;
    private javax.swing.JPanel pnl_quenMatKhau;
    private javax.swing.JTextField txt_email;
    private javax.swing.JPasswordField txt_matKhau;
    private javax.swing.JTextField txt_taiKhoan;
    private javax.swing.JTextField txt_taiKhoan1;
    // End of variables declaration//GEN-END:variables
}
