/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author LAPTOP DELL
 */
public class QuanLyNhanVien_GUI extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyNhanVien_GUI
     */
    public QuanLyNhanVien_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        pnl_top = new javax.swing.JPanel();
        pnl_timKiem = new javax.swing.JPanel();
        txt_timKiem = new javax.swing.JTextField();
        pnl_btnTimKiem = new javax.swing.JPanel();
        btn_timKiem = new javax.swing.JButton();
        pnl_cta = new javax.swing.JPanel();
        cbo_chucVu = new javax.swing.JComboBox<>();
        cbo_trangThai = new javax.swing.JComboBox<>();
        btn_Loc = new javax.swing.JButton();
        btn_Reset = new javax.swing.JButton();
        pnl_center = new javax.swing.JPanel();
        spl_container = new javax.swing.JSplitPane();
        src_nhanVien = new javax.swing.JScrollPane();
        tbl_nhanVien = new javax.swing.JTable();
        pnl_container = new javax.swing.JPanel();
        pnl_thongTinNhanVien = new javax.swing.JPanel();
        pnl_MaNV = new javax.swing.JPanel();
        lbl_maNV = new javax.swing.JLabel();
        txt_maNV = new javax.swing.JTextField();
        pnl_hoTen = new javax.swing.JPanel();
        lbl_hoTen = new javax.swing.JLabel();
        txt_hoTen = new javax.swing.JTextField();
        pnl_diaChi = new javax.swing.JPanel();
        lbl_diaChi = new javax.swing.JLabel();
        txt_diaChi = new javax.swing.JTextField();
        pnl_gioiTinh = new javax.swing.JPanel();
        lbl_gioiTinh = new javax.swing.JLabel();
        pnl_radGroup = new javax.swing.JPanel();
        rad_Nam = new javax.swing.JRadioButton();
        rad_Nu = new javax.swing.JRadioButton();
        pnl_ngaySinh = new javax.swing.JPanel();
        lbl_ngaySinh = new javax.swing.JLabel();
        txt_ngaySinh = new com.toedter.calendar.JDateChooser();
        pnl_chucVu = new javax.swing.JPanel();
        lbl_chucVu = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        pnl_sdt = new javax.swing.JPanel();
        lbl_sdt = new javax.swing.JLabel();
        txt_sdt = new javax.swing.JTextField();
        pnl_cccd = new javax.swing.JPanel();
        lbl_cccd = new javax.swing.JLabel();
        txt_cccd = new javax.swing.JTextField();
        pnl_trangThai = new javax.swing.JPanel();
        lbl_trangThai = new javax.swing.JLabel();
        pnl_radGroup2 = new javax.swing.JPanel();
        rad_tt1 = new javax.swing.JRadioButton();
        rad_tt2 = new javax.swing.JRadioButton();
        pnl_btnGroup = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btn_xoaTrang = new javax.swing.JButton();
        btn_capNhat = new javax.swing.JButton();
        btn_datLaiMK = new javax.swing.JButton();
        btn_xuatExcel = new javax.swing.JButton();
        btn_themNV = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1366, 768));
        setLayout(new java.awt.BorderLayout());

        pnl_top.setBackground(new java.awt.Color(255, 255, 255));
        pnl_top.setMinimumSize(new java.awt.Dimension(20, 20));
        pnl_top.setPreferredSize(new java.awt.Dimension(1366, 50));
        pnl_top.setLayout(new javax.swing.BoxLayout(pnl_top, javax.swing.BoxLayout.LINE_AXIS));

        pnl_timKiem.setPreferredSize(new java.awt.Dimension(579, 30));
        pnl_timKiem.setLayout(new javax.swing.BoxLayout(pnl_timKiem, javax.swing.BoxLayout.LINE_AXIS));

        txt_timKiem.setPreferredSize(new java.awt.Dimension(500, 30));
        txt_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timKiemActionPerformed(evt);
            }
        });
        pnl_timKiem.add(txt_timKiem);

        pnl_btnTimKiem.setPreferredSize(new java.awt.Dimension(79, 23));
        pnl_btnTimKiem.setLayout(new java.awt.BorderLayout());

        btn_timKiem.setText("Tìm kiếm");
        pnl_btnTimKiem.add(btn_timKiem, java.awt.BorderLayout.CENTER);

        pnl_timKiem.add(pnl_btnTimKiem);

        pnl_top.add(pnl_timKiem);

        pnl_cta.setPreferredSize(new java.awt.Dimension(500, 50));
        pnl_cta.setLayout(new java.awt.GridLayout(1, 0));

        cbo_chucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chức vụ", "Quản lý", "Nhân viên" }));
        cbo_chucVu.setToolTipText("");
        cbo_chucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_chucVuActionPerformed(evt);
            }
        });
        pnl_cta.add(cbo_chucVu);

        cbo_trangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trạng thái", "Đang làm", "Đã nghỉ" }));
        cbo_trangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_trangThaiActionPerformed(evt);
            }
        });
        pnl_cta.add(cbo_trangThai);

        btn_Loc.setText("Lọc");
        btn_Loc.setMaximumSize(new java.awt.Dimension(100, 50));
        btn_Loc.setPreferredSize(new java.awt.Dimension(100, 50));
        pnl_cta.add(btn_Loc);

        btn_Reset.setText("Reset");
        btn_Reset.setMaximumSize(new java.awt.Dimension(100, 50));
        btn_Reset.setPreferredSize(new java.awt.Dimension(100, 50));
        pnl_cta.add(btn_Reset);

        pnl_top.add(pnl_cta);

        add(pnl_top, java.awt.BorderLayout.PAGE_START);

        pnl_center.setLayout(new javax.swing.BoxLayout(pnl_center, javax.swing.BoxLayout.LINE_AXIS));

        spl_container.setResizeWeight(0.6);
        spl_container.setMinimumSize(new java.awt.Dimension(805, 416));
        spl_container.setPreferredSize(new java.awt.Dimension(1055, 718));

        src_nhanVien.setMinimumSize(new java.awt.Dimension(400, 20));
        src_nhanVien.setPreferredSize(new java.awt.Dimension(800, 402));

        tbl_nhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Ngày sinh", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_nhanVien.setMaximumSize(new java.awt.Dimension(1000, 80));
        tbl_nhanVien.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl_nhanVien.setShowGrid(false);
        src_nhanVien.setViewportView(tbl_nhanVien);

        spl_container.setLeftComponent(src_nhanVien);

        pnl_container.setBackground(new java.awt.Color(255, 255, 255));
        pnl_container.setMinimumSize(new java.awt.Dimension(400, 379));
        pnl_container.setPreferredSize(new java.awt.Dimension(250, 100));
        pnl_container.setLayout(new java.awt.BorderLayout());

        pnl_thongTinNhanVien.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin nhân viên"), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        pnl_thongTinNhanVien.setLayout(new javax.swing.BoxLayout(pnl_thongTinNhanVien, javax.swing.BoxLayout.Y_AXIS));

        pnl_MaNV.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        pnl_MaNV.setMinimumSize(new java.awt.Dimension(118, 6));
        pnl_MaNV.setPreferredSize(new java.awt.Dimension(230, 50));
        pnl_MaNV.setLayout(new javax.swing.BoxLayout(pnl_MaNV, javax.swing.BoxLayout.X_AXIS));

        lbl_maNV.setText("Mã NV:");
        lbl_maNV.setMaximumSize(new java.awt.Dimension(45, 16));
        lbl_maNV.setMinimumSize(new java.awt.Dimension(45, 16));
        lbl_maNV.setPreferredSize(new java.awt.Dimension(100, 16));
        pnl_MaNV.add(lbl_maNV);

        txt_maNV.setEnabled(false);
        txt_maNV.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        txt_maNV.setPreferredSize(new java.awt.Dimension(64, 40));
        txt_maNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maNVActionPerformed(evt);
            }
        });
        pnl_MaNV.add(txt_maNV);

        pnl_thongTinNhanVien.add(pnl_MaNV);

        pnl_hoTen.setMaximumSize(pnl_MaNV.getMaximumSize());
        pnl_hoTen.setMinimumSize(pnl_MaNV.getMinimumSize());
        pnl_hoTen.setPreferredSize(pnl_MaNV.getPreferredSize());
        pnl_hoTen.setLayout(new javax.swing.BoxLayout(pnl_hoTen, javax.swing.BoxLayout.LINE_AXIS));

        lbl_hoTen.setText("Họ tên:");
        lbl_hoTen.setMaximumSize(new java.awt.Dimension(45, 16));
        lbl_hoTen.setMinimumSize(new java.awt.Dimension(45, 16));
        lbl_hoTen.setPreferredSize(new java.awt.Dimension(100, 16));
        pnl_hoTen.add(lbl_hoTen);

        txt_hoTen.setMaximumSize(txt_maNV.getMaximumSize());
        txt_hoTen.setPreferredSize(txt_maNV.getPreferredSize());
        pnl_hoTen.add(txt_hoTen);

        pnl_thongTinNhanVien.add(pnl_hoTen);

        pnl_diaChi.setMaximumSize(pnl_MaNV.getMaximumSize());
        pnl_diaChi.setMinimumSize(new java.awt.Dimension(118, 6));
        pnl_diaChi.setPreferredSize(pnl_MaNV.getPreferredSize());
        pnl_diaChi.setLayout(new javax.swing.BoxLayout(pnl_diaChi, javax.swing.BoxLayout.LINE_AXIS));

        lbl_diaChi.setText("Địa chỉ:");
        lbl_diaChi.setMaximumSize(new java.awt.Dimension(45, 16));
        lbl_diaChi.setMinimumSize(new java.awt.Dimension(45, 16));
        lbl_diaChi.setPreferredSize(new java.awt.Dimension(100, 16));
        pnl_diaChi.add(lbl_diaChi);

        txt_diaChi.setMaximumSize(txt_maNV.getMaximumSize());
        txt_diaChi.setMinimumSize(new java.awt.Dimension(64, 30));
        txt_diaChi.setPreferredSize(txt_maNV.getPreferredSize());
        txt_diaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_diaChiActionPerformed(evt);
            }
        });
        pnl_diaChi.add(txt_diaChi);

        pnl_thongTinNhanVien.add(pnl_diaChi);

        pnl_gioiTinh.setMaximumSize(pnl_MaNV.getMaximumSize());
        pnl_gioiTinh.setPreferredSize(pnl_MaNV.getPreferredSize());
        pnl_gioiTinh.setLayout(new javax.swing.BoxLayout(pnl_gioiTinh, javax.swing.BoxLayout.X_AXIS));

        lbl_gioiTinh.setText("Giới tính:");
        lbl_gioiTinh.setMaximumSize(new java.awt.Dimension(45, 16));
        lbl_gioiTinh.setMinimumSize(new java.awt.Dimension(45, 16));
        lbl_gioiTinh.setPreferredSize(lbl_maNV.getPreferredSize());
        pnl_gioiTinh.add(lbl_gioiTinh);

        pnl_radGroup.setMaximumSize(new java.awt.Dimension(32767, 30));
        pnl_radGroup.setMinimumSize(new java.awt.Dimension(103, 30));
        pnl_radGroup.setPreferredSize(new java.awt.Dimension(103, 30));
        pnl_radGroup.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 4));

        buttonGroup1.add(rad_Nam);
        rad_Nam.setText("Nam");
        pnl_radGroup.add(rad_Nam);

        buttonGroup1.add(rad_Nu);
        rad_Nu.setText("Nữ");
        rad_Nu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad_NuActionPerformed(evt);
            }
        });
        pnl_radGroup.add(rad_Nu);

        pnl_gioiTinh.add(pnl_radGroup);

        pnl_thongTinNhanVien.add(pnl_gioiTinh);

        pnl_ngaySinh.setMaximumSize(pnl_MaNV.getMaximumSize());
        pnl_ngaySinh.setMinimumSize(new java.awt.Dimension(118, 6));
        pnl_ngaySinh.setPreferredSize(pnl_MaNV.getPreferredSize());
        pnl_ngaySinh.setLayout(new javax.swing.BoxLayout(pnl_ngaySinh, javax.swing.BoxLayout.LINE_AXIS));

        lbl_ngaySinh.setText("Ngày sinh:");
        lbl_ngaySinh.setMaximumSize(new java.awt.Dimension(100, 16));
        lbl_ngaySinh.setPreferredSize(lbl_maNV.getPreferredSize());
        pnl_ngaySinh.add(lbl_ngaySinh);

        txt_ngaySinh.setMaximumSize(txt_maNV.getMaximumSize());
        txt_ngaySinh.setMinimumSize(new java.awt.Dimension(141, 0));
        txt_ngaySinh.setPreferredSize(txt_maNV.getPreferredSize());
        pnl_ngaySinh.add(txt_ngaySinh);

        pnl_thongTinNhanVien.add(pnl_ngaySinh);

        pnl_chucVu.setMaximumSize(new java.awt.Dimension(32817, 50));
        pnl_chucVu.setPreferredSize(new java.awt.Dimension(230, 50));
        pnl_chucVu.setLayout(new javax.swing.BoxLayout(pnl_chucVu, javax.swing.BoxLayout.LINE_AXIS));

        lbl_chucVu.setText("Chức vụ :");
        lbl_chucVu.setPreferredSize(new java.awt.Dimension(100, 16));
        pnl_chucVu.add(lbl_chucVu);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân viên", "Quản lý" }));
        jComboBox1.setMaximumSize(new java.awt.Dimension(32767, 40));
        jComboBox1.setPreferredSize(new java.awt.Dimension(230, 40));
        pnl_chucVu.add(jComboBox1);

        pnl_thongTinNhanVien.add(pnl_chucVu);

        pnl_sdt.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        pnl_sdt.setMinimumSize(new java.awt.Dimension(118, 6));
        pnl_sdt.setPreferredSize(new java.awt.Dimension(230, 50));
        pnl_sdt.setLayout(new javax.swing.BoxLayout(pnl_sdt, javax.swing.BoxLayout.LINE_AXIS));

        lbl_sdt.setText("SDT:");
        lbl_sdt.setPreferredSize(new java.awt.Dimension(100, 16));
        pnl_sdt.add(lbl_sdt);

        txt_sdt.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        txt_sdt.setPreferredSize(new java.awt.Dimension(230, 40));
        pnl_sdt.add(txt_sdt);

        pnl_thongTinNhanVien.add(pnl_sdt);

        pnl_cccd.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        pnl_cccd.setMinimumSize(new java.awt.Dimension(118, 6));
        pnl_cccd.setPreferredSize(new java.awt.Dimension(230, 50));
        pnl_cccd.setLayout(new javax.swing.BoxLayout(pnl_cccd, javax.swing.BoxLayout.LINE_AXIS));

        lbl_cccd.setText("CCCD:");
        lbl_cccd.setPreferredSize(lbl_maNV.getPreferredSize());
        pnl_cccd.add(lbl_cccd);

        txt_cccd.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        txt_cccd.setPreferredSize(new java.awt.Dimension(64, 40));
        pnl_cccd.add(txt_cccd);

        pnl_thongTinNhanVien.add(pnl_cccd);

        pnl_trangThai.setMaximumSize(new java.awt.Dimension(100000, 50));
        pnl_trangThai.setPreferredSize(new java.awt.Dimension(230, 50));
        pnl_trangThai.setLayout(new javax.swing.BoxLayout(pnl_trangThai, javax.swing.BoxLayout.LINE_AXIS));

        lbl_trangThai.setText("Trạng thái:");
        lbl_trangThai.setPreferredSize(lbl_maNV.getPreferredSize());
        pnl_trangThai.add(lbl_trangThai);

        pnl_radGroup2.setMaximumSize(new java.awt.Dimension(32767, 40));
        pnl_radGroup2.setPreferredSize(new java.awt.Dimension(156, 40));
        pnl_radGroup2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        buttonGroup2.add(rad_tt1);
        rad_tt1.setText("Đang làm");
        rad_tt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad_tt1ActionPerformed(evt);
            }
        });
        pnl_radGroup2.add(rad_tt1);

        buttonGroup2.add(rad_tt2);
        rad_tt2.setText("Đã nghỉ");
        pnl_radGroup2.add(rad_tt2);

        pnl_trangThai.add(pnl_radGroup2);

        pnl_thongTinNhanVien.add(pnl_trangThai);

        pnl_container.add(pnl_thongTinNhanVien, java.awt.BorderLayout.CENTER);

        pnl_btnGroup.setMaximumSize(new java.awt.Dimension(260, 100));
        pnl_btnGroup.setMinimumSize(new java.awt.Dimension(220, 100));
        pnl_btnGroup.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        btn_xoaTrang.setText("Xóa trắng");
        btn_xoaTrang.setMaximumSize(new java.awt.Dimension(120, 50));
        btn_xoaTrang.setPreferredSize(new java.awt.Dimension(120, 50));
        jPanel5.add(btn_xoaTrang);

        btn_capNhat.setText("Cập nhật");
        btn_capNhat.setMaximumSize(new java.awt.Dimension(120, 50));
        btn_capNhat.setPreferredSize(new java.awt.Dimension(120, 50));
        btn_capNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capNhatActionPerformed(evt);
            }
        });
        jPanel5.add(btn_capNhat);

        btn_datLaiMK.setText("Đặt lại mật khẩu");
        btn_datLaiMK.setMaximumSize(new java.awt.Dimension(120, 50));
        btn_datLaiMK.setPreferredSize(new java.awt.Dimension(120, 50));
        jPanel5.add(btn_datLaiMK);

        btn_xuatExcel.setText("Xuất Excel");
        btn_xuatExcel.setMaximumSize(new java.awt.Dimension(120, 50));
        btn_xuatExcel.setPreferredSize(new java.awt.Dimension(120, 50));
        jPanel5.add(btn_xuatExcel);

        pnl_btnGroup.add(jPanel5, java.awt.BorderLayout.CENTER);

        btn_themNV.setText("Thêm nhân viên");
        btn_themNV.setMaximumSize(new java.awt.Dimension(139, 23));
        btn_themNV.setMinimumSize(new java.awt.Dimension(139, 23));
        btn_themNV.setPreferredSize(new java.awt.Dimension(72, 50));
        pnl_btnGroup.add(btn_themNV, java.awt.BorderLayout.PAGE_END);

        pnl_container.add(pnl_btnGroup, java.awt.BorderLayout.PAGE_END);

        spl_container.setRightComponent(pnl_container);

        pnl_center.add(spl_container);

        add(pnl_center, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timKiemActionPerformed

    private void cbo_chucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_chucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_chucVuActionPerformed

    private void txt_diaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_diaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_diaChiActionPerformed

    private void rad_NuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_NuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rad_NuActionPerformed

    private void txt_maNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maNVActionPerformed

    private void btn_capNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capNhatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_capNhatActionPerformed

    private void cbo_trangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_trangThaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_trangThaiActionPerformed

    private void rad_tt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_tt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rad_tt1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Loc;
    private javax.swing.JButton btn_Reset;
    private javax.swing.JButton btn_capNhat;
    private javax.swing.JButton btn_datLaiMK;
    private javax.swing.JButton btn_themNV;
    private javax.swing.JButton btn_timKiem;
    private javax.swing.JButton btn_xoaTrang;
    private javax.swing.JButton btn_xuatExcel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbo_chucVu;
    private javax.swing.JComboBox<String> cbo_trangThai;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbl_cccd;
    private javax.swing.JLabel lbl_chucVu;
    private javax.swing.JLabel lbl_diaChi;
    private javax.swing.JLabel lbl_gioiTinh;
    private javax.swing.JLabel lbl_hoTen;
    private javax.swing.JLabel lbl_maNV;
    private javax.swing.JLabel lbl_ngaySinh;
    private javax.swing.JLabel lbl_sdt;
    private javax.swing.JLabel lbl_trangThai;
    private javax.swing.JPanel pnl_MaNV;
    private javax.swing.JPanel pnl_btnGroup;
    private javax.swing.JPanel pnl_btnTimKiem;
    private javax.swing.JPanel pnl_cccd;
    private javax.swing.JPanel pnl_center;
    private javax.swing.JPanel pnl_chucVu;
    private javax.swing.JPanel pnl_container;
    private javax.swing.JPanel pnl_cta;
    private javax.swing.JPanel pnl_diaChi;
    private javax.swing.JPanel pnl_gioiTinh;
    private javax.swing.JPanel pnl_hoTen;
    private javax.swing.JPanel pnl_ngaySinh;
    private javax.swing.JPanel pnl_radGroup;
    private javax.swing.JPanel pnl_radGroup2;
    private javax.swing.JPanel pnl_sdt;
    private javax.swing.JPanel pnl_thongTinNhanVien;
    private javax.swing.JPanel pnl_timKiem;
    private javax.swing.JPanel pnl_top;
    private javax.swing.JPanel pnl_trangThai;
    private javax.swing.JRadioButton rad_Nam;
    private javax.swing.JRadioButton rad_Nu;
    private javax.swing.JRadioButton rad_tt1;
    private javax.swing.JRadioButton rad_tt2;
    private javax.swing.JSplitPane spl_container;
    private javax.swing.JScrollPane src_nhanVien;
    private javax.swing.JTable tbl_nhanVien;
    private javax.swing.JTextField txt_cccd;
    private javax.swing.JTextField txt_diaChi;
    private javax.swing.JTextField txt_hoTen;
    private javax.swing.JTextField txt_maNV;
    private com.toedter.calendar.JDateChooser txt_ngaySinh;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_timKiem;
    // End of variables declaration//GEN-END:variables
}
