/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author LAPTOP DELL
 */
public class QuanLyTau_GUI extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyTau_GUI
     */
    public QuanLyTau_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_timKiem = new javax.swing.JPanel();
        filler21 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        jLabel1 = new javax.swing.JLabel();
        filler20 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        jTextField1 = new javax.swing.JTextField();
        filler15 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        bnt_timKiem = new javax.swing.JButton();
        filler16 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        cbo_trangThai = new javax.swing.JComboBox<>();
        filler17 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        btn_loc = new javax.swing.JButton();
        filler18 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        btn_reset = new javax.swing.JButton();
        filler19 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        pnl_thongTin = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        pnl_máTau = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        pnl_tenTau = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        pnl_gaDi = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        pnl_gaDen = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        pnl_ngayKhoiHanh = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        pnl_gioDi = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        pnl_gioDen = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        pnl_soCho = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        pnl_giaVe = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        pnl_nut1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        filler13 = new javax.swing.Box.Filler(new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 32767));
        jButton2 = new javax.swing.JButton();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        pnl_nut2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        filler14 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        jButton4 = new javax.swing.JButton();
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        jPanel12 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        pnl_timKiem.setBackground(new java.awt.Color(255, 255, 255));
        pnl_timKiem.setPreferredSize(new java.awt.Dimension(919, 40));
        pnl_timKiem.setLayout(new javax.swing.BoxLayout(pnl_timKiem, javax.swing.BoxLayout.LINE_AXIS));
        pnl_timKiem.add(filler21);

        jLabel1.setText("Mã tàu :");
        pnl_timKiem.add(jLabel1);
        pnl_timKiem.add(filler20);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        pnl_timKiem.add(jTextField1);
        pnl_timKiem.add(filler15);

        bnt_timKiem.setText("Tìm kiếm");
        bnt_timKiem.setMaximumSize(new java.awt.Dimension(79, 60));
        bnt_timKiem.setPreferredSize(new java.awt.Dimension(79, 60));
        bnt_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_timKiemActionPerformed(evt);
            }
        });
        pnl_timKiem.add(bnt_timKiem);
        pnl_timKiem.add(filler16);

        cbo_trangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trạng thái", "Hoạt động", "Ngưng hoạt động" }));
        pnl_timKiem.add(cbo_trangThai);
        pnl_timKiem.add(filler17);

        btn_loc.setText("Lọc");
        btn_loc.setMaximumSize(new java.awt.Dimension(72, 60));
        btn_loc.setPreferredSize(new java.awt.Dimension(72, 60));
        pnl_timKiem.add(btn_loc);
        pnl_timKiem.add(filler18);

        btn_reset.setText("Reset");
        btn_reset.setMaximumSize(new java.awt.Dimension(72, 60));
        btn_reset.setPreferredSize(new java.awt.Dimension(72, 60));
        pnl_timKiem.add(btn_reset);
        pnl_timKiem.add(filler19);

        add(pnl_timKiem, java.awt.BorderLayout.PAGE_START);

        pnl_thongTin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin tàu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        pnl_thongTin.setPreferredSize(new java.awt.Dimension(450, 479));
        pnl_thongTin.setLayout(new javax.swing.BoxLayout(pnl_thongTin, javax.swing.BoxLayout.Y_AXIS));
        pnl_thongTin.add(filler1);

        pnl_máTau.setLayout(new javax.swing.BoxLayout(pnl_máTau, javax.swing.BoxLayout.X_AXIS));

        jLabel2.setText("Mã tàu :");
        jLabel2.setMaximumSize(new java.awt.Dimension(90, 16));
        jLabel2.setPreferredSize(new java.awt.Dimension(90, 16));
        pnl_máTau.add(jLabel2);
        pnl_máTau.add(jTextField2);

        pnl_thongTin.add(pnl_máTau);
        pnl_thongTin.add(filler2);

        pnl_tenTau.setLayout(new javax.swing.BoxLayout(pnl_tenTau, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setText("Tên tàu :");
        jLabel3.setMaximumSize(new java.awt.Dimension(90, 16));
        jLabel3.setPreferredSize(new java.awt.Dimension(90, 16));
        pnl_tenTau.add(jLabel3);
        pnl_tenTau.add(jTextField3);

        pnl_thongTin.add(pnl_tenTau);
        pnl_thongTin.add(filler3);

        pnl_gaDi.setLayout(new javax.swing.BoxLayout(pnl_gaDi, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setText("Ga đi :");
        jLabel4.setMaximumSize(new java.awt.Dimension(90, 16));
        jLabel4.setPreferredSize(new java.awt.Dimension(90, 16));
        pnl_gaDi.add(jLabel4);
        pnl_gaDi.add(jTextField4);

        pnl_thongTin.add(pnl_gaDi);
        pnl_thongTin.add(filler4);

        pnl_gaDen.setLayout(new javax.swing.BoxLayout(pnl_gaDen, javax.swing.BoxLayout.LINE_AXIS));

        jLabel5.setText("Ga đến :");
        jLabel5.setMaximumSize(new java.awt.Dimension(90, 16));
        jLabel5.setPreferredSize(new java.awt.Dimension(90, 16));
        pnl_gaDen.add(jLabel5);
        pnl_gaDen.add(jTextField5);

        pnl_thongTin.add(pnl_gaDen);
        pnl_thongTin.add(filler5);

        pnl_ngayKhoiHanh.setLayout(new javax.swing.BoxLayout(pnl_ngayKhoiHanh, javax.swing.BoxLayout.LINE_AXIS));

        jLabel6.setText("Ngày khởi hành :");
        pnl_ngayKhoiHanh.add(jLabel6);
        pnl_ngayKhoiHanh.add(jDateChooser1);

        pnl_thongTin.add(pnl_ngayKhoiHanh);
        pnl_thongTin.add(filler6);

        pnl_gioDi.setLayout(new javax.swing.BoxLayout(pnl_gioDi, javax.swing.BoxLayout.LINE_AXIS));

        jLabel7.setText("Giờ đi :");
        jLabel7.setMaximumSize(new java.awt.Dimension(90, 16));
        jLabel7.setPreferredSize(new java.awt.Dimension(90, 16));
        pnl_gioDi.add(jLabel7);
        pnl_gioDi.add(jTextField6);

        pnl_thongTin.add(pnl_gioDi);
        pnl_thongTin.add(filler7);

        pnl_gioDen.setLayout(new javax.swing.BoxLayout(pnl_gioDen, javax.swing.BoxLayout.LINE_AXIS));

        jLabel8.setText("Giờ đến :");
        jLabel8.setMaximumSize(new java.awt.Dimension(90, 16));
        jLabel8.setPreferredSize(new java.awt.Dimension(90, 16));
        pnl_gioDen.add(jLabel8);
        pnl_gioDen.add(jTextField7);

        pnl_thongTin.add(pnl_gioDen);
        pnl_thongTin.add(filler8);

        pnl_soCho.setLayout(new javax.swing.BoxLayout(pnl_soCho, javax.swing.BoxLayout.LINE_AXIS));

        jLabel9.setText("Số chỗ :");
        jLabel9.setMaximumSize(new java.awt.Dimension(90, 16));
        jLabel9.setPreferredSize(new java.awt.Dimension(90, 16));
        pnl_soCho.add(jLabel9);
        pnl_soCho.add(jTextField8);

        pnl_thongTin.add(pnl_soCho);
        pnl_thongTin.add(filler9);

        pnl_giaVe.setLayout(new javax.swing.BoxLayout(pnl_giaVe, javax.swing.BoxLayout.LINE_AXIS));

        jLabel10.setText("Giá vé :");
        jLabel10.setMaximumSize(new java.awt.Dimension(90, 16));
        jLabel10.setPreferredSize(new java.awt.Dimension(90, 16));
        pnl_giaVe.add(jLabel10);
        pnl_giaVe.add(jTextField9);

        pnl_thongTin.add(pnl_giaVe);
        pnl_thongTin.add(filler10);

        pnl_nut1.setLayout(new javax.swing.BoxLayout(pnl_nut1, javax.swing.BoxLayout.LINE_AXIS));

        jButton1.setText("Xóa trắng");
        jButton1.setMaximumSize(new java.awt.Dimension(90, 40));
        jButton1.setMinimumSize(new java.awt.Dimension(90, 23));
        jButton1.setPreferredSize(new java.awt.Dimension(90, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnl_nut1.add(jButton1);
        pnl_nut1.add(filler13);

        jButton2.setText("Cập Nhật");
        jButton2.setMaximumSize(new java.awt.Dimension(90, 40));
        jButton2.setPreferredSize(new java.awt.Dimension(90, 40));
        pnl_nut1.add(jButton2);

        pnl_thongTin.add(pnl_nut1);
        pnl_thongTin.add(filler11);

        pnl_nut2.setLayout(new javax.swing.BoxLayout(pnl_nut2, javax.swing.BoxLayout.LINE_AXIS));

        jButton3.setText("Thêm tàu");
        jButton3.setMaximumSize(new java.awt.Dimension(90, 40));
        jButton3.setPreferredSize(new java.awt.Dimension(90, 40));
        pnl_nut2.add(jButton3);
        pnl_nut2.add(filler14);

        jButton4.setText("Sửa");
        jButton4.setMaximumSize(new java.awt.Dimension(90, 40));
        jButton4.setPreferredSize(new java.awt.Dimension(90, 40));
        pnl_nut2.add(jButton4);

        pnl_thongTin.add(pnl_nut2);
        pnl_thongTin.add(filler12);

        add(pnl_thongTin, java.awt.BorderLayout.LINE_END);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bảng thông tin tàu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.LINE_AXIS));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã tàu", "Tên tàu", "Ga đi", "Ga đến", "Ngày khởi hành", "Giá vé"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel12.add(jScrollPane1);

        add(jPanel12, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void bnt_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_timKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnt_timKiemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_timKiem;
    private javax.swing.JButton btn_loc;
    private javax.swing.JButton btn_reset;
    private javax.swing.JComboBox<String> cbo_trangThai;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler13;
    private javax.swing.Box.Filler filler14;
    private javax.swing.Box.Filler filler15;
    private javax.swing.Box.Filler filler16;
    private javax.swing.Box.Filler filler17;
    private javax.swing.Box.Filler filler18;
    private javax.swing.Box.Filler filler19;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler20;
    private javax.swing.Box.Filler filler21;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel pnl_gaDen;
    private javax.swing.JPanel pnl_gaDi;
    private javax.swing.JPanel pnl_giaVe;
    private javax.swing.JPanel pnl_gioDen;
    private javax.swing.JPanel pnl_gioDi;
    private javax.swing.JPanel pnl_máTau;
    private javax.swing.JPanel pnl_ngayKhoiHanh;
    private javax.swing.JPanel pnl_nut1;
    private javax.swing.JPanel pnl_nut2;
    private javax.swing.JPanel pnl_soCho;
    private javax.swing.JPanel pnl_tenTau;
    private javax.swing.JPanel pnl_thongTin;
    private javax.swing.JPanel pnl_timKiem;
    // End of variables declaration//GEN-END:variables
}
