/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author Laptopone
 */
public class QuanLiThongTinCaNhan_GUI extends javax.swing.JPanel {

    /**
     * Creates new form QLTT_GUI
     */
    public QuanLiThongTinCaNhan_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnlWest = new javax.swing.JPanel();
        lbl_taiAnh = new javax.swing.JLabel();
        btn_taiAnh = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTextField6 = new javax.swing.JTextField();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        jPanel7 = new javax.swing.JPanel();
        btn_Luu = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField3 = new javax.swing.JPasswordField();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        jPanel9 = new javax.swing.JPanel();
        btn_Luu1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setLayout(new java.awt.BorderLayout());

        pnlWest.setBackground(new java.awt.Color(255, 255, 255));
        pnlWest.setBorder(javax.swing.BorderFactory.createEmptyBorder(60, 10, 0, 10));
        pnlWest.setPreferredSize(new java.awt.Dimension(450, 380));

        lbl_taiAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_taiAnh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl_taiAnh.setPreferredSize(new java.awt.Dimension(300, 300));
        pnlWest.add(lbl_taiAnh);

        btn_taiAnh.setBackground(new java.awt.Color(123, 17, 19));
        btn_taiAnh.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_taiAnh.setForeground(new java.awt.Color(255, 255, 255));
        btn_taiAnh.setText("Tải ảnh lên");
        btn_taiAnh.setPreferredSize(new java.awt.Dimension(200, 50));
        btn_taiAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_taiAnhActionPerformed(evt);
            }
        });
        pnlWest.add(btn_taiAnh);

        jPanel2.add(pnlWest, java.awt.BorderLayout.LINE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(40, 10, 10, 65));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setMaximumSize(new java.awt.Dimension(32767, 120));
        jPanel4.setLayout(new java.awt.GridLayout(2, 2, 40, 0));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Mã nhân viên");
        jPanel4.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Họ tên");
        jPanel4.add(jLabel4);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextField3.setText("jTextField3");
        jPanel4.add(jTextField3);

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextField4.setText("jTextField4");
        jPanel4.add(jTextField4);

        jPanel3.add(jPanel4);
        jPanel3.add(filler1);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setMaximumSize(new java.awt.Dimension(32767, 120));
        jPanel5.setLayout(new java.awt.GridLayout(2, 2, 40, 0));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Ngày sinh");
        jPanel5.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Email");
        jPanel5.add(jLabel6);

        jDateChooser1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel5.add(jDateChooser1);

        jTextField6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextField6.setText("jTextField4");
        jPanel5.add(jTextField6);

        jPanel3.add(jPanel5);
        jPanel3.add(filler2);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setMaximumSize(new java.awt.Dimension(32767, 120));
        jPanel6.setLayout(new java.awt.GridLayout(2, 2, 40, 0));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Số điện thoại");
        jPanel6.add(jLabel7);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Địa chỉ");
        jPanel6.add(jLabel8);

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextField7.setText("jTextField3");
        jPanel6.add(jTextField7);

        jTextField8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextField8.setText("jTextField4");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField8);

        jPanel3.add(jPanel6);
        jPanel3.add(filler3);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setMaximumSize(new java.awt.Dimension(32767, 60));
        jPanel7.setPreferredSize(new java.awt.Dimension(200, 80));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btn_Luu.setBackground(new java.awt.Color(123, 17, 19));
        btn_Luu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Luu.setForeground(new java.awt.Color(255, 255, 255));
        btn_Luu.setText("Lưu thông tin");
        btn_Luu.setBorder(null);
        btn_Luu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Luu.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel7.add(btn_Luu);

        jPanel3.add(jPanel7);
        jPanel3.add(filler4);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setMaximumSize(new java.awt.Dimension(32767, 120));
        jPanel8.setPreferredSize(new java.awt.Dimension(100, 120));
        jPanel8.setLayout(new java.awt.GridLayout(2, 3, 20, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Mật khẩu hiện tại");
        jPanel8.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Mật khẩu mới");
        jPanel8.add(jLabel2);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Xác nhận mật khẩu");
        jPanel8.add(jLabel9);

        jPasswordField1.setText("jPasswordField1");
        jPanel8.add(jPasswordField1);

        jPasswordField2.setText("jPasswordField2");
        jPanel8.add(jPasswordField2);

        jPasswordField3.setText("jPasswordField3");
        jPanel8.add(jPasswordField3);

        jPanel3.add(jPanel8);
        jPanel3.add(filler5);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setMaximumSize(new java.awt.Dimension(32767, 60));
        jPanel9.setPreferredSize(new java.awt.Dimension(200, 80));
        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btn_Luu1.setBackground(new java.awt.Color(123, 17, 19));
        btn_Luu1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Luu1.setForeground(new java.awt.Color(255, 255, 255));
        btn_Luu1.setText("Đổi mật khẩu");
        btn_Luu1.setBorder(null);
        btn_Luu1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Luu1.setPreferredSize(new java.awt.Dimension(200, 50));
        btn_Luu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Luu1ActionPerformed(evt);
            }
        });
        jPanel9.add(btn_Luu1);

        jPanel3.add(jPanel9);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_taiAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_taiAnhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_taiAnhActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void btn_Luu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Luu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Luu1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Luu;
    private javax.swing.JButton btn_Luu1;
    private javax.swing.JButton btn_taiAnh;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel lbl_taiAnh;
    private javax.swing.JPanel pnlWest;
    // End of variables declaration//GEN-END:variables
}
