/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author Laptopone
 */
public class QuanLiKhuyenMai_GUI extends javax.swing.JPanel {

    /**
     * Creates new form TraCuuHanhKhach_GUI
     */
    public QuanLiKhuyenMai_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlNorth = new javax.swing.JPanel();
        pnl_timKiem = new javax.swing.JPanel();
        txt_timKiem = new javax.swing.JTextField();
        pnl_btnTimKiem = new javax.swing.JPanel();
        btn_timKiem = new javax.swing.JButton();
        pnl_cta = new javax.swing.JPanel();
        cbo_loaiKM = new javax.swing.JComboBox<>();
        cbo_trangThaiKM = new javax.swing.JComboBox<>();
        btn_Loc = new javax.swing.JButton();
        btn_Reset = new javax.swing.JButton();
        pnlEast = new javax.swing.JPanel();
        pnl_maKM = new javax.swing.JPanel();
        lbl_maKM = new javax.swing.JLabel();
        txt_maKM = new javax.swing.JTextField();
        pnl_tenKM = new javax.swing.JPanel();
        lbl_tenKM = new javax.swing.JLabel();
        txt_tenKM = new javax.swing.JTextField();
        pnl_loaiKM = new javax.swing.JPanel();
        lbl_loaiKM = new javax.swing.JLabel();
        pnl_radioLoaiKM = new javax.swing.JPanel();
        rdo_phanTram = new javax.swing.JRadioButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        rdo_tien = new javax.swing.JRadioButton();
        pnl_mucGiam = new javax.swing.JPanel();
        lbl_mucGiam = new javax.swing.JLabel();
        txt_mucGiam = new javax.swing.JTextField();
        pnl_ngayBatDau = new javax.swing.JPanel();
        lbl_ngayBatDau = new javax.swing.JLabel();
        txt_ngayBatDau = new com.toedter.calendar.JDateChooser();
        pnl_ngayKetThuc = new javax.swing.JPanel();
        lbl_ngayKetThuc = new javax.swing.JLabel();
        txt_ngayKetThuc = new com.toedter.calendar.JDateChooser();
        pnl_tongTienToiThieu = new javax.swing.JPanel();
        lbl_tongTienToiThieu = new javax.swing.JLabel();
        txt_tongTienToiThieu = new javax.swing.JTextField();
        pnl_tienKhuyenMaiToiDa = new javax.swing.JPanel();
        lbl_tienKhuyenMaiToiDa = new javax.swing.JLabel();
        txt_tienKhuyenMaiToiDa = new javax.swing.JTextField();
        pnl_trangThai = new javax.swing.JPanel();
        lbl_trangThai = new javax.swing.JLabel();
        cbo_trangThai = new javax.swing.JComboBox<>();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 100), new java.awt.Dimension(0, 100), new java.awt.Dimension(32767, 100));
        pnl_button = new javax.swing.JPanel();
        btn_xoaTrang = new javax.swing.JButton();
        btn_capNhat = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_taoKM = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_khuyenMai = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        pnlNorth.setBackground(new java.awt.Color(255, 255, 255));
        pnlNorth.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnlNorth.setPreferredSize(new java.awt.Dimension(1366, 55));
        pnlNorth.setLayout(new javax.swing.BoxLayout(pnlNorth, javax.swing.BoxLayout.LINE_AXIS));

        pnl_timKiem.setLayout(new javax.swing.BoxLayout(pnl_timKiem, javax.swing.BoxLayout.LINE_AXIS));

        txt_timKiem.setPreferredSize(new java.awt.Dimension(500, 30));
        txt_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timKiemActionPerformed(evt);
            }
        });
        pnl_timKiem.add(txt_timKiem);

        pnl_btnTimKiem.setPreferredSize(new java.awt.Dimension(79, 23));
        pnl_btnTimKiem.setLayout(new java.awt.BorderLayout());

        btn_timKiem.setText("Tìm kiếm");
        pnl_btnTimKiem.add(btn_timKiem, java.awt.BorderLayout.CENTER);

        pnl_timKiem.add(pnl_btnTimKiem);

        pnlNorth.add(pnl_timKiem);

        pnl_cta.setPreferredSize(new java.awt.Dimension(500, 50));
        pnl_cta.setLayout(new java.awt.GridLayout(1, 0));

        cbo_loaiKM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loại khuyến mãi", " " }));
        cbo_loaiKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_loaiKMActionPerformed(evt);
            }
        });
        pnl_cta.add(cbo_loaiKM);

        cbo_trangThaiKM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trạng thái", " " }));
        cbo_trangThaiKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_trangThaiKMActionPerformed(evt);
            }
        });
        pnl_cta.add(cbo_trangThaiKM);

        btn_Loc.setText("Lọc");
        btn_Loc.setMaximumSize(new java.awt.Dimension(100, 50));
        btn_Loc.setPreferredSize(new java.awt.Dimension(100, 50));
        pnl_cta.add(btn_Loc);

        btn_Reset.setText("Reset");
        btn_Reset.setMaximumSize(new java.awt.Dimension(100, 50));
        btn_Reset.setPreferredSize(new java.awt.Dimension(100, 50));
        pnl_cta.add(btn_Reset);

        pnlNorth.add(pnl_cta);

        add(pnlNorth, java.awt.BorderLayout.PAGE_START);

        pnlEast.setBackground(new java.awt.Color(255, 255, 255));
        pnlEast.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khuyến mãi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(123, 17, 19))); // NOI18N
        pnlEast.setPreferredSize(new java.awt.Dimension(400, 668));
        pnlEast.setLayout(new javax.swing.BoxLayout(pnlEast, javax.swing.BoxLayout.Y_AXIS));

        pnl_maKM.setBackground(new java.awt.Color(255, 255, 255));
        pnl_maKM.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnl_maKM.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        pnl_maKM.setPreferredSize(new java.awt.Dimension(390, 50));
        pnl_maKM.setLayout(new javax.swing.BoxLayout(pnl_maKM, javax.swing.BoxLayout.LINE_AXIS));

        lbl_maKM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_maKM.setLabelFor(lbl_maKM);
        lbl_maKM.setText("Mã KM:");
        lbl_maKM.setMaximumSize(new java.awt.Dimension(100, 30));
        lbl_maKM.setPreferredSize(new java.awt.Dimension(100, 20));
        pnl_maKM.add(lbl_maKM);

        txt_maKM.setEditable(false);
        txt_maKM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_maKM.setText("KM0001");
        txt_maKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maKMActionPerformed(evt);
            }
        });
        pnl_maKM.add(txt_maKM);

        pnlEast.add(pnl_maKM);

        pnl_tenKM.setBackground(new java.awt.Color(255, 255, 255));
        pnl_tenKM.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnl_tenKM.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        pnl_tenKM.setPreferredSize(new java.awt.Dimension(390, 50));
        pnl_tenKM.setLayout(new javax.swing.BoxLayout(pnl_tenKM, javax.swing.BoxLayout.LINE_AXIS));

        lbl_tenKM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_tenKM.setLabelFor(lbl_tenKM);
        lbl_tenKM.setText("Tên KM:");
        lbl_tenKM.setMaximumSize(new java.awt.Dimension(100, 30));
        lbl_tenKM.setPreferredSize(new java.awt.Dimension(100, 20));
        pnl_tenKM.add(lbl_tenKM);

        txt_tenKM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_tenKM.setText("Giảm 10%");
        txt_tenKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tenKMActionPerformed(evt);
            }
        });
        pnl_tenKM.add(txt_tenKM);

        pnlEast.add(pnl_tenKM);

        pnl_loaiKM.setBackground(new java.awt.Color(255, 255, 255));
        pnl_loaiKM.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnl_loaiKM.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        pnl_loaiKM.setPreferredSize(new java.awt.Dimension(390, 50));
        pnl_loaiKM.setLayout(new javax.swing.BoxLayout(pnl_loaiKM, javax.swing.BoxLayout.LINE_AXIS));

        lbl_loaiKM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_loaiKM.setText("Loại khuyến mãi:");
        lbl_loaiKM.setMaximumSize(new java.awt.Dimension(100, 30));
        lbl_loaiKM.setPreferredSize(new java.awt.Dimension(100, 20));
        pnl_loaiKM.add(lbl_loaiKM);

        pnl_radioLoaiKM.setBackground(new java.awt.Color(255, 255, 255));
        pnl_radioLoaiKM.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        pnl_radioLoaiKM.setLayout(new javax.swing.BoxLayout(pnl_radioLoaiKM, javax.swing.BoxLayout.LINE_AXIS));

        buttonGroup1.add(rdo_phanTram);
        rdo_phanTram.setSelected(true);
        rdo_phanTram.setText("Phần trăm");
        pnl_radioLoaiKM.add(rdo_phanTram);
        pnl_radioLoaiKM.add(filler2);

        buttonGroup1.add(rdo_tien);
        rdo_tien.setText("Tiền");
        pnl_radioLoaiKM.add(rdo_tien);

        pnl_loaiKM.add(pnl_radioLoaiKM);

        pnlEast.add(pnl_loaiKM);

        pnl_mucGiam.setBackground(new java.awt.Color(255, 255, 255));
        pnl_mucGiam.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnl_mucGiam.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        pnl_mucGiam.setPreferredSize(new java.awt.Dimension(390, 50));
        pnl_mucGiam.setLayout(new javax.swing.BoxLayout(pnl_mucGiam, javax.swing.BoxLayout.LINE_AXIS));

        lbl_mucGiam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_mucGiam.setLabelFor(pnl_mucGiam);
        lbl_mucGiam.setText("Mức giảm:");
        lbl_mucGiam.setMaximumSize(new java.awt.Dimension(100, 30));
        lbl_mucGiam.setPreferredSize(new java.awt.Dimension(100, 20));
        pnl_mucGiam.add(lbl_mucGiam);

        txt_mucGiam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_mucGiam.setText("0.1");
        txt_mucGiam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mucGiamActionPerformed(evt);
            }
        });
        pnl_mucGiam.add(txt_mucGiam);

        pnlEast.add(pnl_mucGiam);

        pnl_ngayBatDau.setBackground(new java.awt.Color(255, 255, 255));
        pnl_ngayBatDau.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnl_ngayBatDau.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        pnl_ngayBatDau.setPreferredSize(new java.awt.Dimension(390, 50));
        pnl_ngayBatDau.setLayout(new javax.swing.BoxLayout(pnl_ngayBatDau, javax.swing.BoxLayout.LINE_AXIS));

        lbl_ngayBatDau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_ngayBatDau.setLabelFor(txt_ngayBatDau);
        lbl_ngayBatDau.setText("Ngày bắt đầu:");
        lbl_ngayBatDau.setMaximumSize(new java.awt.Dimension(100, 30));
        lbl_ngayBatDau.setPreferredSize(new java.awt.Dimension(100, 20));
        pnl_ngayBatDau.add(lbl_ngayBatDau);

        txt_ngayBatDau.setMinimumSize(new java.awt.Dimension(141, 0));
        pnl_ngayBatDau.add(txt_ngayBatDau);

        pnlEast.add(pnl_ngayBatDau);

        pnl_ngayKetThuc.setBackground(new java.awt.Color(255, 255, 255));
        pnl_ngayKetThuc.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnl_ngayKetThuc.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        pnl_ngayKetThuc.setPreferredSize(new java.awt.Dimension(390, 50));
        pnl_ngayKetThuc.setLayout(new javax.swing.BoxLayout(pnl_ngayKetThuc, javax.swing.BoxLayout.LINE_AXIS));

        lbl_ngayKetThuc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_ngayKetThuc.setLabelFor(txt_ngayKetThuc);
        lbl_ngayKetThuc.setText("Ngày kết thúc:");
        lbl_ngayKetThuc.setMaximumSize(new java.awt.Dimension(100, 30));
        lbl_ngayKetThuc.setPreferredSize(new java.awt.Dimension(100, 20));
        pnl_ngayKetThuc.add(lbl_ngayKetThuc);

        txt_ngayKetThuc.setMinimumSize(new java.awt.Dimension(141, 0));
        pnl_ngayKetThuc.add(txt_ngayKetThuc);

        pnlEast.add(pnl_ngayKetThuc);

        pnl_tongTienToiThieu.setBackground(new java.awt.Color(255, 255, 255));
        pnl_tongTienToiThieu.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnl_tongTienToiThieu.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        pnl_tongTienToiThieu.setPreferredSize(new java.awt.Dimension(390, 50));
        pnl_tongTienToiThieu.setLayout(new javax.swing.BoxLayout(pnl_tongTienToiThieu, javax.swing.BoxLayout.LINE_AXIS));

        lbl_tongTienToiThieu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_tongTienToiThieu.setLabelFor(pnl_tongTienToiThieu);
        lbl_tongTienToiThieu.setText("Tổng tiền tối thiểu");
        lbl_tongTienToiThieu.setMaximumSize(new java.awt.Dimension(100, 30));
        lbl_tongTienToiThieu.setPreferredSize(new java.awt.Dimension(100, 20));
        pnl_tongTienToiThieu.add(lbl_tongTienToiThieu);

        txt_tongTienToiThieu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_tongTienToiThieu.setText("100.000");
        txt_tongTienToiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tongTienToiThieuActionPerformed(evt);
            }
        });
        pnl_tongTienToiThieu.add(txt_tongTienToiThieu);

        pnlEast.add(pnl_tongTienToiThieu);

        pnl_tienKhuyenMaiToiDa.setBackground(new java.awt.Color(255, 255, 255));
        pnl_tienKhuyenMaiToiDa.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnl_tienKhuyenMaiToiDa.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        pnl_tienKhuyenMaiToiDa.setPreferredSize(new java.awt.Dimension(390, 50));
        pnl_tienKhuyenMaiToiDa.setLayout(new javax.swing.BoxLayout(pnl_tienKhuyenMaiToiDa, javax.swing.BoxLayout.LINE_AXIS));

        lbl_tienKhuyenMaiToiDa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_tienKhuyenMaiToiDa.setLabelFor(pnl_tienKhuyenMaiToiDa);
        lbl_tienKhuyenMaiToiDa.setText("Khuyến mãi tối đa");
        lbl_tienKhuyenMaiToiDa.setMaximumSize(new java.awt.Dimension(100, 30));
        lbl_tienKhuyenMaiToiDa.setPreferredSize(new java.awt.Dimension(100, 20));
        pnl_tienKhuyenMaiToiDa.add(lbl_tienKhuyenMaiToiDa);

        txt_tienKhuyenMaiToiDa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_tienKhuyenMaiToiDa.setText("100.000");
        txt_tienKhuyenMaiToiDa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tienKhuyenMaiToiDaActionPerformed(evt);
            }
        });
        pnl_tienKhuyenMaiToiDa.add(txt_tienKhuyenMaiToiDa);

        pnlEast.add(pnl_tienKhuyenMaiToiDa);

        pnl_trangThai.setBackground(new java.awt.Color(255, 255, 255));
        pnl_trangThai.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnl_trangThai.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        pnl_trangThai.setPreferredSize(new java.awt.Dimension(390, 50));
        pnl_trangThai.setLayout(new javax.swing.BoxLayout(pnl_trangThai, javax.swing.BoxLayout.LINE_AXIS));

        lbl_trangThai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_trangThai.setLabelFor(pnl_mucGiam);
        lbl_trangThai.setText("Trạng thái:");
        lbl_trangThai.setMaximumSize(new java.awt.Dimension(100, 30));
        lbl_trangThai.setPreferredSize(new java.awt.Dimension(100, 20));
        pnl_trangThai.add(lbl_trangThai);

        cbo_trangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnl_trangThai.add(cbo_trangThai);

        pnlEast.add(pnl_trangThai);
        pnlEast.add(filler1);

        pnl_button.setBackground(new java.awt.Color(255, 255, 255));
        pnl_button.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnl_button.setMaximumSize(new java.awt.Dimension(32767, 150));
        pnl_button.setPreferredSize(new java.awt.Dimension(390, 200));
        pnl_button.setLayout(new java.awt.GridLayout(2, 0, 10, 10));

        btn_xoaTrang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_xoaTrang.setText("Xóa trắng");
        pnl_button.add(btn_xoaTrang);

        btn_capNhat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_capNhat.setText("Cập nhật");
        pnl_button.add(btn_capNhat);

        btn_xoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_xoa.setText("Xóa");
        pnl_button.add(btn_xoa);

        btn_taoKM.setBackground(new java.awt.Color(123, 17, 19));
        btn_taoKM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_taoKM.setForeground(new java.awt.Color(255, 255, 255));
        btn_taoKM.setText("Tạo khuyến mãi");
        pnl_button.add(btn_taoKM);

        pnlEast.add(pnl_button);

        add(pnlEast, java.awt.BorderLayout.LINE_END);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        tbl_khuyenMai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(tbl_khuyenMai);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_maKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maKMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maKMActionPerformed

    private void txt_tenKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tenKMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tenKMActionPerformed

    private void txt_mucGiamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mucGiamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mucGiamActionPerformed

    private void txt_tongTienToiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tongTienToiThieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tongTienToiThieuActionPerformed

    private void txt_tienKhuyenMaiToiDaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tienKhuyenMaiToiDaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tienKhuyenMaiToiDaActionPerformed

    private void cbo_trangThaiKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_trangThaiKMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_trangThaiKMActionPerformed

    private void txt_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timKiemActionPerformed

    private void cbo_loaiKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_loaiKMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_loaiKMActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Loc;
    private javax.swing.JButton btn_Reset;
    private javax.swing.JButton btn_capNhat;
    private javax.swing.JButton btn_taoKM;
    private javax.swing.JButton btn_timKiem;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JButton btn_xoaTrang;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbo_loaiKM;
    private javax.swing.JComboBox<String> cbo_trangThai;
    private javax.swing.JComboBox<String> cbo_trangThaiKM;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_loaiKM;
    private javax.swing.JLabel lbl_maKM;
    private javax.swing.JLabel lbl_mucGiam;
    private javax.swing.JLabel lbl_ngayBatDau;
    private javax.swing.JLabel lbl_ngayKetThuc;
    private javax.swing.JLabel lbl_tenKM;
    private javax.swing.JLabel lbl_tienKhuyenMaiToiDa;
    private javax.swing.JLabel lbl_tongTienToiThieu;
    private javax.swing.JLabel lbl_trangThai;
    private javax.swing.JPanel pnlEast;
    private javax.swing.JPanel pnlNorth;
    private javax.swing.JPanel pnl_btnTimKiem;
    private javax.swing.JPanel pnl_button;
    private javax.swing.JPanel pnl_cta;
    private javax.swing.JPanel pnl_loaiKM;
    private javax.swing.JPanel pnl_maKM;
    private javax.swing.JPanel pnl_mucGiam;
    private javax.swing.JPanel pnl_ngayBatDau;
    private javax.swing.JPanel pnl_ngayKetThuc;
    private javax.swing.JPanel pnl_radioLoaiKM;
    private javax.swing.JPanel pnl_tenKM;
    private javax.swing.JPanel pnl_tienKhuyenMaiToiDa;
    private javax.swing.JPanel pnl_timKiem;
    private javax.swing.JPanel pnl_tongTienToiThieu;
    private javax.swing.JPanel pnl_trangThai;
    private javax.swing.JRadioButton rdo_phanTram;
    private javax.swing.JRadioButton rdo_tien;
    private javax.swing.JTable tbl_khuyenMai;
    private javax.swing.JTextField txt_maKM;
    private javax.swing.JTextField txt_mucGiam;
    private com.toedter.calendar.JDateChooser txt_ngayBatDau;
    private com.toedter.calendar.JDateChooser txt_ngayKetThuc;
    private javax.swing.JTextField txt_tenKM;
    private javax.swing.JTextField txt_tienKhuyenMaiToiDa;
    private javax.swing.JTextField txt_timKiem;
    private javax.swing.JTextField txt_tongTienToiThieu;
    // End of variables declaration//GEN-END:variables
}
