/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author PC
 */
public class QuanLyGaTau_GUI extends javax.swing.JPanel {

    /**
     * Creates new form QuanLiGaTau2_GUI
     */
    public QuanLyGaTau_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_center = new javax.swing.JPanel();
        spl_container = new javax.swing.JSplitPane();
        pnl_container = new javax.swing.JPanel();
        pnl_thongTinNhanVien = new javax.swing.JPanel();
        pnl_MaNV = new javax.swing.JPanel();
        lbl_maNV = new javax.swing.JLabel();
        txt_maNV = new javax.swing.JTextField();
        pnl_hoTen1 = new javax.swing.JPanel();
        lbl_hoTen1 = new javax.swing.JLabel();
        txt_hoTen1 = new javax.swing.JTextField();
        lbl_ngaySinh = new javax.swing.JLabel();
        pnl_ngaySinh = new javax.swing.JPanel();
        pnl_chucVu1 = new javax.swing.JPanel();
        pnl_hoTen = new javax.swing.JPanel();
        lbl_hoTen = new javax.swing.JLabel();
        txt_hoTen = new javax.swing.JTextField();
        pnl_diaChi = new javax.swing.JPanel();
        lbl_diaChi = new javax.swing.JLabel();
        txt_diaChi2 = new javax.swing.JTextField();
        pnl_btnGroup = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btn_xoaTrang = new javax.swing.JButton();
        btn_capNhat = new javax.swing.JButton();
        btn_xuatExcel = new javax.swing.JButton();
        btn_themNV = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnl_top = new javax.swing.JPanel();
        pnl_timKiem = new javax.swing.JPanel();
        txt_timKiem = new javax.swing.JTextField();
        pnl_btnTimKiem = new javax.swing.JPanel();
        btn_timKiem = new javax.swing.JButton();
        pnl_cta = new javax.swing.JPanel();
        cbo_chucVu = new javax.swing.JComboBox<>();
        cbo_trangThai = new javax.swing.JComboBox<>();
        btn_Loc = new javax.swing.JButton();
        btn_Reset = new javax.swing.JButton();

        pnl_center.setLayout(new javax.swing.BoxLayout(pnl_center, javax.swing.BoxLayout.LINE_AXIS));

        spl_container.setResizeWeight(0.6);
        spl_container.setMinimumSize(new java.awt.Dimension(805, 416));
        spl_container.setPreferredSize(new java.awt.Dimension(1055, 718));

        pnl_container.setBackground(new java.awt.Color(255, 255, 255));
        pnl_container.setMinimumSize(new java.awt.Dimension(400, 379));
        pnl_container.setPreferredSize(new java.awt.Dimension(250, 100));
        pnl_container.setLayout(new java.awt.BorderLayout());

        pnl_thongTinNhanVien.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin ga tàu"));
        pnl_thongTinNhanVien.setLayout(new javax.swing.BoxLayout(pnl_thongTinNhanVien, javax.swing.BoxLayout.Y_AXIS));

        pnl_MaNV.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        pnl_MaNV.setMinimumSize(new java.awt.Dimension(118, 6));
        pnl_MaNV.setPreferredSize(new java.awt.Dimension(230, 50));
        pnl_MaNV.setLayout(new javax.swing.BoxLayout(pnl_MaNV, javax.swing.BoxLayout.X_AXIS));

        lbl_maNV.setText("Mã ga :");
        lbl_maNV.setMaximumSize(new java.awt.Dimension(45, 16));
        lbl_maNV.setMinimumSize(new java.awt.Dimension(45, 16));
        lbl_maNV.setPreferredSize(new java.awt.Dimension(100, 16));
        pnl_MaNV.add(lbl_maNV);

        txt_maNV.setEnabled(false);
        txt_maNV.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        txt_maNV.setPreferredSize(new java.awt.Dimension(64, 40));
        txt_maNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maNVActionPerformed(evt);
            }
        });
        pnl_MaNV.add(txt_maNV);

        pnl_thongTinNhanVien.add(pnl_MaNV);

        pnl_hoTen1.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        pnl_hoTen1.setPreferredSize(new java.awt.Dimension(164, 50));
        pnl_hoTen1.setLayout(new javax.swing.BoxLayout(pnl_hoTen1, javax.swing.BoxLayout.LINE_AXIS));

        lbl_hoTen1.setText("Tên ga :");
        lbl_hoTen1.setMaximumSize(new java.awt.Dimension(45, 16));
        lbl_hoTen1.setMinimumSize(new java.awt.Dimension(45, 16));
        lbl_hoTen1.setPreferredSize(new java.awt.Dimension(100, 16));
        pnl_hoTen1.add(lbl_hoTen1);

        txt_hoTen1.setMaximumSize(new java.awt.Dimension(2147483647, 180));
        pnl_hoTen1.add(txt_hoTen1);

        pnl_thongTinNhanVien.add(pnl_hoTen1);

        lbl_ngaySinh.setMaximumSize(new java.awt.Dimension(100, 16));
        pnl_thongTinNhanVien.add(lbl_ngaySinh);

        pnl_ngaySinh.setMinimumSize(new java.awt.Dimension(118, 6));
        pnl_ngaySinh.setLayout(new javax.swing.BoxLayout(pnl_ngaySinh, javax.swing.BoxLayout.LINE_AXIS));
        pnl_thongTinNhanVien.add(pnl_ngaySinh);

        pnl_chucVu1.setMaximumSize(new java.awt.Dimension(32817, 50));
        pnl_chucVu1.setPreferredSize(new java.awt.Dimension(230, 50));
        pnl_chucVu1.setLayout(new javax.swing.BoxLayout(pnl_chucVu1, javax.swing.BoxLayout.LINE_AXIS));

        pnl_hoTen.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        pnl_hoTen.setPreferredSize(new java.awt.Dimension(164, 50));
        pnl_hoTen.setLayout(new javax.swing.BoxLayout(pnl_hoTen, javax.swing.BoxLayout.LINE_AXIS));

        lbl_hoTen.setText("Địa chỉ :");
        lbl_hoTen.setMaximumSize(new java.awt.Dimension(45, 16));
        lbl_hoTen.setMinimumSize(new java.awt.Dimension(45, 16));
        lbl_hoTen.setPreferredSize(new java.awt.Dimension(100, 16));
        pnl_hoTen.add(lbl_hoTen);

        txt_hoTen.setMaximumSize(new java.awt.Dimension(1147483647, 1147483647));
        pnl_hoTen.add(txt_hoTen);

        pnl_chucVu1.add(pnl_hoTen);

        pnl_thongTinNhanVien.add(pnl_chucVu1);

        pnl_diaChi.setMaximumSize(new java.awt.Dimension(1147483692, 50));
        pnl_diaChi.setMinimumSize(new java.awt.Dimension(118, 6));
        pnl_diaChi.setPreferredSize(new java.awt.Dimension(164, 50));
        pnl_diaChi.setLayout(new javax.swing.BoxLayout(pnl_diaChi, javax.swing.BoxLayout.LINE_AXIS));

        lbl_diaChi.setText("Số điện thoại");
        lbl_diaChi.setMaximumSize(new java.awt.Dimension(45, 16));
        lbl_diaChi.setMinimumSize(new java.awt.Dimension(45, 16));
        lbl_diaChi.setPreferredSize(new java.awt.Dimension(100, 16));
        pnl_diaChi.add(lbl_diaChi);

        txt_diaChi2.setMaximumSize(new java.awt.Dimension(1147483647, 1147483647));
        txt_diaChi2.setMinimumSize(new java.awt.Dimension(64, 30));
        txt_diaChi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_diaChi2ActionPerformed(evt);
            }
        });
        pnl_diaChi.add(txt_diaChi2);

        pnl_thongTinNhanVien.add(pnl_diaChi);

        pnl_container.add(pnl_thongTinNhanVien, java.awt.BorderLayout.CENTER);

        pnl_btnGroup.setMaximumSize(new java.awt.Dimension(260, 100));
        pnl_btnGroup.setMinimumSize(new java.awt.Dimension(220, 100));
        pnl_btnGroup.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        btn_xoaTrang.setText("Xóa trắng");
        btn_xoaTrang.setMaximumSize(new java.awt.Dimension(120, 50));
        btn_xoaTrang.setPreferredSize(new java.awt.Dimension(120, 50));
        jPanel5.add(btn_xoaTrang);

        btn_capNhat.setText("Cập nhật");
        btn_capNhat.setMaximumSize(new java.awt.Dimension(120, 50));
        btn_capNhat.setPreferredSize(new java.awt.Dimension(120, 50));
        btn_capNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capNhatActionPerformed(evt);
            }
        });
        jPanel5.add(btn_capNhat);

        btn_xuatExcel.setText("Xuất Excel");
        btn_xuatExcel.setMaximumSize(new java.awt.Dimension(120, 50));
        btn_xuatExcel.setPreferredSize(new java.awt.Dimension(120, 50));
        jPanel5.add(btn_xuatExcel);

        pnl_btnGroup.add(jPanel5, java.awt.BorderLayout.CENTER);

        btn_themNV.setText("Thêm ga mới");
        btn_themNV.setMaximumSize(new java.awt.Dimension(139, 23));
        btn_themNV.setMinimumSize(new java.awt.Dimension(139, 23));
        btn_themNV.setPreferredSize(new java.awt.Dimension(72, 50));
        btn_themNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themNVActionPerformed(evt);
            }
        });
        pnl_btnGroup.add(btn_themNV, java.awt.BorderLayout.PAGE_END);

        pnl_container.add(pnl_btnGroup, java.awt.BorderLayout.PAGE_END);

        spl_container.setRightComponent(pnl_container);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã ga", "Tên ga", "Địa chỉ", "Số điện thoại"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        spl_container.setLeftComponent(jScrollPane1);

        pnl_center.add(spl_container);

        pnl_top.setBackground(new java.awt.Color(255, 255, 255));
        pnl_top.setMinimumSize(new java.awt.Dimension(20, 20));
        pnl_top.setPreferredSize(new java.awt.Dimension(1366, 50));
        pnl_top.setLayout(new javax.swing.BoxLayout(pnl_top, javax.swing.BoxLayout.LINE_AXIS));

        pnl_timKiem.setLayout(new javax.swing.BoxLayout(pnl_timKiem, javax.swing.BoxLayout.LINE_AXIS));

        txt_timKiem.setPreferredSize(new java.awt.Dimension(500, 30));
        txt_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timKiemActionPerformed(evt);
            }
        });
        pnl_timKiem.add(txt_timKiem);

        pnl_btnTimKiem.setLayout(new java.awt.BorderLayout());

        btn_timKiem.setText("Tìm kiếm");
        pnl_btnTimKiem.add(btn_timKiem, java.awt.BorderLayout.CENTER);

        pnl_timKiem.add(pnl_btnTimKiem);

        pnl_top.add(pnl_timKiem);

        pnl_cta.setPreferredSize(new java.awt.Dimension(500, 50));
        pnl_cta.setLayout(new java.awt.GridLayout());

        cbo_chucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Số sân ga", "1", "2" }));
        cbo_chucVu.setToolTipText("");
        cbo_chucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_chucVuActionPerformed(evt);
            }
        });
        pnl_cta.add(cbo_chucVu);

        cbo_trangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trạng thái", "Đang chạy", "Đã đến nơi", " " }));
        cbo_trangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_trangThaiActionPerformed(evt);
            }
        });
        pnl_cta.add(cbo_trangThai);

        btn_Loc.setText("Lọc");
        btn_Loc.setMaximumSize(new java.awt.Dimension(100, 50));
        btn_Loc.setPreferredSize(new java.awt.Dimension(100, 50));
        pnl_cta.add(btn_Loc);

        btn_Reset.setText("Reset");
        btn_Reset.setMaximumSize(new java.awt.Dimension(100, 50));
        btn_Reset.setPreferredSize(new java.awt.Dimension(100, 50));
        pnl_cta.add(btn_Reset);

        pnl_top.add(pnl_cta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnl_top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pnl_center, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnl_top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(pnl_center, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_maNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maNVActionPerformed

    private void txt_diaChi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_diaChi2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_diaChi2ActionPerformed

    private void btn_themNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_themNVActionPerformed

    private void txt_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timKiemActionPerformed

    private void cbo_trangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_trangThaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_trangThaiActionPerformed

    private void cbo_chucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_chucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_chucVuActionPerformed

    private void btn_capNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capNhatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_capNhatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Loc;
    private javax.swing.JButton btn_Reset;
    private javax.swing.JButton btn_capNhat;
    private javax.swing.JButton btn_themNV;
    private javax.swing.JButton btn_timKiem;
    private javax.swing.JButton btn_xoaTrang;
    private javax.swing.JButton btn_xuatExcel;
    private javax.swing.JComboBox<String> cbo_chucVu;
    private javax.swing.JComboBox<String> cbo_trangThai;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_diaChi;
    private javax.swing.JLabel lbl_hoTen;
    private javax.swing.JLabel lbl_hoTen1;
    private javax.swing.JLabel lbl_maNV;
    private javax.swing.JLabel lbl_ngaySinh;
    private javax.swing.JPanel pnl_MaNV;
    private javax.swing.JPanel pnl_btnGroup;
    private javax.swing.JPanel pnl_btnTimKiem;
    private javax.swing.JPanel pnl_center;
    private javax.swing.JPanel pnl_chucVu1;
    private javax.swing.JPanel pnl_container;
    private javax.swing.JPanel pnl_cta;
    private javax.swing.JPanel pnl_diaChi;
    private javax.swing.JPanel pnl_hoTen;
    private javax.swing.JPanel pnl_hoTen1;
    private javax.swing.JPanel pnl_ngaySinh;
    private javax.swing.JPanel pnl_thongTinNhanVien;
    private javax.swing.JPanel pnl_timKiem;
    private javax.swing.JPanel pnl_top;
    private javax.swing.JSplitPane spl_container;
    private javax.swing.JTextField txt_diaChi2;
    private javax.swing.JTextField txt_hoTen;
    private javax.swing.JTextField txt_hoTen1;
    private javax.swing.JTextField txt_maNV;
    private javax.swing.JTextField txt_timKiem;
    // End of variables declaration//GEN-END:variables
}
