/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author CÔNG HOÀNG
 */
public class TraCuuNhanVien_GUI extends javax.swing.JPanel {

    /**
     * Creates new form TraCuuNhanVien
     */
    public TraCuuNhanVien_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnl_header = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        pnl_1 = new javax.swing.JPanel();
        lbl_maNV = new javax.swing.JLabel();
        txt_maNV = new javax.swing.JTextField();
        lbl_next2 = new javax.swing.JLabel();
        lbl_tenNV = new javax.swing.JLabel();
        txt_tenNV = new javax.swing.JTextField();
        lbl_next6 = new javax.swing.JLabel();
        lbl_cccd = new javax.swing.JLabel();
        txt_cccd = new javax.swing.JTextField();
        pnl_2 = new javax.swing.JPanel();
        lbl_sdt = new javax.swing.JLabel();
        txt_sdt = new javax.swing.JTextField();
        lbl_next5 = new javax.swing.JLabel();
        lbl_gioitinh = new javax.swing.JLabel();
        cbo_gioitinh = new javax.swing.JComboBox<>();
        lbl_next3 = new javax.swing.JLabel();
        lbl_trangthai = new javax.swing.JLabel();
        cbo_trangthai = new javax.swing.JComboBox<>();
        pnl_timKiem = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bảng thông tin nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14)))); // NOI18N
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Ngày sinh", "Số điện thoại", "CCCD", "Trạng thái", "Địa chỉ ", "Chức vụ", "Giới tính"
            }
        ));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        pnl_header.setBackground(new java.awt.Color(255, 255, 255));
        pnl_header.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnl_header.setPreferredSize(new java.awt.Dimension(1366, 250));
        pnl_header.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin nhân viên"), javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        pnl_1.setBackground(new java.awt.Color(255, 255, 255));
        pnl_1.setMaximumSize(new java.awt.Dimension(65736, 70));
        pnl_1.setMinimumSize(new java.awt.Dimension(1000, 25));
        pnl_1.setPreferredSize(new java.awt.Dimension(100, 70));
        pnl_1.setLayout(new javax.swing.BoxLayout(pnl_1, javax.swing.BoxLayout.LINE_AXIS));

        lbl_maNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_maNV.setText("Mã nhân viên:");
        lbl_maNV.setPreferredSize(new java.awt.Dimension(100, 16));
        pnl_1.add(lbl_maNV);

        txt_maNV.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        txt_maNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maNVActionPerformed(evt);
            }
        });
        pnl_1.add(txt_maNV);

        lbl_next2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_next2.setPreferredSize(new java.awt.Dimension(30, 16));
        pnl_1.add(lbl_next2);

        lbl_tenNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_tenNV.setText("Tên nhân viên:");
        lbl_tenNV.setPreferredSize(new java.awt.Dimension(100, 25));
        pnl_1.add(lbl_tenNV);

        txt_tenNV.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        txt_tenNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tenNVActionPerformed(evt);
            }
        });
        pnl_1.add(txt_tenNV);

        lbl_next6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_next6.setPreferredSize(new java.awt.Dimension(30, 16));
        pnl_1.add(lbl_next6);

        lbl_cccd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_cccd.setText("Số CCCD:");
        lbl_cccd.setPreferredSize(new java.awt.Dimension(70, 20));
        pnl_1.add(lbl_cccd);

        txt_cccd.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        pnl_1.add(txt_cccd);

        jPanel3.add(pnl_1);

        pnl_2.setBackground(new java.awt.Color(255, 255, 255));
        pnl_2.setMaximumSize(new java.awt.Dimension(65679, 70));
        pnl_2.setMinimumSize(new java.awt.Dimension(1000, 25));
        pnl_2.setLayout(new javax.swing.BoxLayout(pnl_2, javax.swing.BoxLayout.LINE_AXIS));

        lbl_sdt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_sdt.setText("Số điện thoại:");
        lbl_sdt.setPreferredSize(new java.awt.Dimension(100, 16));
        pnl_2.add(lbl_sdt);

        txt_sdt.setMaximumSize(txt_maNV.getMaximumSize());
        txt_sdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sdtActionPerformed(evt);
            }
        });
        pnl_2.add(txt_sdt);

        lbl_next5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_next5.setPreferredSize(new java.awt.Dimension(30, 16));
        pnl_2.add(lbl_next5);

        lbl_gioitinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_gioitinh.setText("Giới tính:");
        lbl_gioitinh.setPreferredSize(new java.awt.Dimension(80, 25));
        pnl_2.add(lbl_gioitinh);

        cbo_gioitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cbo_gioitinh.setMaximumSize(new java.awt.Dimension(32767, 50));
        cbo_gioitinh.setPreferredSize(new java.awt.Dimension(120, 22));
        cbo_gioitinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_gioitinhActionPerformed(evt);
            }
        });
        pnl_2.add(cbo_gioitinh);

        lbl_next3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_next3.setPreferredSize(new java.awt.Dimension(30, 16));
        pnl_2.add(lbl_next3);

        lbl_trangthai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_trangthai.setText("Trạng thái:");
        lbl_trangthai.setPreferredSize(new java.awt.Dimension(80, 25));
        pnl_2.add(lbl_trangthai);

        cbo_trangthai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Còn làm", "Nghỉ làm" }));
        cbo_trangthai.setMaximumSize(new java.awt.Dimension(32767, 50));
        cbo_trangthai.setPreferredSize(new java.awt.Dimension(120, 22));
        cbo_trangthai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_trangthaiActionPerformed(evt);
            }
        });
        pnl_2.add(cbo_trangthai);

        jPanel3.add(pnl_2);

        pnl_timKiem.setBackground(new java.awt.Color(255, 255, 255));
        pnl_timKiem.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        pnl_timKiem.setMaximumSize(new java.awt.Dimension(32767, 60));
        pnl_timKiem.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Tìm kiếm");
        jButton1.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel4.add(jButton1);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Xóa trắng");
        jButton2.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel4.add(jButton2);

        pnl_timKiem.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel3.add(pnl_timKiem);

        pnl_header.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(pnl_header, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void cbo_trangthaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_trangthaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_trangthaiActionPerformed

    private void txt_maNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maNVActionPerformed

    private void txt_sdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sdtActionPerformed

    private void cbo_gioitinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_gioitinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_gioitinhActionPerformed

    private void txt_tenNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tenNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tenNVActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbo_gioitinh;
    private javax.swing.JComboBox<String> cbo_trangthai;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_cccd;
    private javax.swing.JLabel lbl_gioitinh;
    private javax.swing.JLabel lbl_maNV;
    private javax.swing.JLabel lbl_next2;
    private javax.swing.JLabel lbl_next3;
    private javax.swing.JLabel lbl_next5;
    private javax.swing.JLabel lbl_next6;
    private javax.swing.JLabel lbl_sdt;
    private javax.swing.JLabel lbl_tenNV;
    private javax.swing.JLabel lbl_trangthai;
    private javax.swing.JPanel pnl_1;
    private javax.swing.JPanel pnl_2;
    private javax.swing.JPanel pnl_header;
    private javax.swing.JPanel pnl_timKiem;
    private javax.swing.JTextField txt_cccd;
    private javax.swing.JTextField txt_maNV;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_tenNV;
    // End of variables declaration//GEN-END:variables
}
