/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author Laptopone
 */
public class TraCuuHanhKhach_GUI extends javax.swing.JPanel {

    /**
     * Creates new form TraCuuHanhKhach_GUI
     */
    public TraCuuHanhKhach_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_sdt = new javax.swing.JTextField();
        lbl_sdt = new javax.swing.JLabel();
        lbl_taiKhoan = new javax.swing.JLabel();
        txt_taiKhoan = new javax.swing.JTextField();
        lbl_mkMoi = new javax.swing.JLabel();
        pwd_mkMoi = new javax.swing.JPasswordField();
        lbl_xacNhanMk = new javax.swing.JLabel();
        pwd_xacNhanMk = new javax.swing.JPasswordField();
        pwd_mkCu = new javax.swing.JPasswordField();
        lbl_mkCu = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        lbl_email = new javax.swing.JLabel();
        lbl_hoTen = new javax.swing.JLabel();
        txt_hoTen = new javax.swing.JTextField();

        txt_sdt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_sdt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_sdt.setText("0966531172");
        txt_sdt.setPreferredSize(new java.awt.Dimension(60, 30));
        txt_sdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sdtActionPerformed(evt);
            }
        });

        lbl_sdt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_sdt.setLabelFor(txt_sdt);
        lbl_sdt.setText("Số điện thoại");
        lbl_sdt.setMaximumSize(new java.awt.Dimension(60, 30));
        lbl_sdt.setPreferredSize(new java.awt.Dimension(60, 30));

        lbl_taiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_taiKhoan.setLabelFor(lbl_taiKhoan);
        lbl_taiKhoan.setText("Tài khoản");
        lbl_taiKhoan.setMaximumSize(new java.awt.Dimension(60, 30));
        lbl_taiKhoan.setPreferredSize(new java.awt.Dimension(60, 30));

        txt_taiKhoan.setEditable(false);
        txt_taiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_taiKhoan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_taiKhoan.setText("NV0002");
        txt_taiKhoan.setPreferredSize(new java.awt.Dimension(60, 30));
        txt_taiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_taiKhoanActionPerformed(evt);
            }
        });

        lbl_mkMoi.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_mkMoi.setLabelFor(pwd_mkMoi);
        lbl_mkMoi.setText("Nhập mật khẩu mới");
        lbl_mkMoi.setMaximumSize(new java.awt.Dimension(60, 30));
        lbl_mkMoi.setPreferredSize(new java.awt.Dimension(60, 30));

        pwd_mkMoi.setPreferredSize(new java.awt.Dimension(60, 30));
        pwd_mkMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwd_mkMoiActionPerformed(evt);
            }
        });

        lbl_xacNhanMk.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_xacNhanMk.setLabelFor(pwd_xacNhanMk);
        lbl_xacNhanMk.setText("Xác nhận mật khẩu mới");
        lbl_xacNhanMk.setMaximumSize(new java.awt.Dimension(60, 30));
        lbl_xacNhanMk.setPreferredSize(new java.awt.Dimension(60, 30));

        pwd_xacNhanMk.setPreferredSize(new java.awt.Dimension(60, 30));
        pwd_xacNhanMk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwd_xacNhanMkActionPerformed(evt);
            }
        });

        pwd_mkCu.setPreferredSize(new java.awt.Dimension(60, 30));
        pwd_mkCu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwd_mkCuActionPerformed(evt);
            }
        });

        lbl_mkCu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_mkCu.setLabelFor(pwd_mkCu);
        lbl_mkCu.setText("Nhập mật khẩu cũ");
        lbl_mkCu.setMaximumSize(new java.awt.Dimension(60, 30));
        lbl_mkCu.setPreferredSize(new java.awt.Dimension(60, 30));

        txt_email.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_email.setText("phuc531172@gmai.com");
        txt_email.setPreferredSize(new java.awt.Dimension(60, 30));
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });

        lbl_email.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_email.setLabelFor(txt_email);
        lbl_email.setText("Email");
        lbl_email.setMaximumSize(new java.awt.Dimension(60, 30));
        lbl_email.setPreferredSize(new java.awt.Dimension(60, 30));

        lbl_hoTen.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_hoTen.setText("Họ tên");
        lbl_hoTen.setMaximumSize(new java.awt.Dimension(855, 50));

        txt_hoTen.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_hoTen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_hoTen.setText("Lê Minh Phúc");
        txt_hoTen.setMaximumSize(new java.awt.Dimension(120, 60));
        txt_hoTen.setMinimumSize(new java.awt.Dimension(30, 10));
        txt_hoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hoTenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(413, 413, 413)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(699, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 428, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbl_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(lbl_email, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lbl_mkMoi, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                .addComponent(pwd_mkMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pwd_xacNhanMk, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_xacNhanMk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lbl_taiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                .addComponent(txt_taiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pwd_mkCu, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_mkCu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(0, 428, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(lbl_hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(533, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 269, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_email, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(40, 40, 40)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_taiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addComponent(lbl_mkCu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_taiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addComponent(pwd_mkCu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(60, 60, 60)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_mkMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_xacNhanMk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pwd_mkMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pwd_xacNhanMk, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 139, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_sdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sdtActionPerformed

    private void txt_taiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_taiKhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_taiKhoanActionPerformed

    private void pwd_mkMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwd_mkMoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwd_mkMoiActionPerformed

    private void pwd_xacNhanMkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwd_xacNhanMkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwd_xacNhanMkActionPerformed

    private void pwd_mkCuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwd_mkCuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwd_mkCuActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_hoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hoTenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_hoTen;
    private javax.swing.JLabel lbl_mkCu;
    private javax.swing.JLabel lbl_mkMoi;
    private javax.swing.JLabel lbl_sdt;
    private javax.swing.JLabel lbl_taiKhoan;
    private javax.swing.JLabel lbl_xacNhanMk;
    private javax.swing.JPasswordField pwd_mkCu;
    private javax.swing.JPasswordField pwd_mkMoi;
    private javax.swing.JPasswordField pwd_xacNhanMk;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_hoTen;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_taiKhoan;
    // End of variables declaration//GEN-END:variables
}
