/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.quanLyVe;

import com.formdev.flatlaf.FlatClientProperties;

/**
 *
 * @author CÔNG HOÀNG
 */
public class ThongTinHanhTrinh_GUI extends javax.swing.JPanel {

    /**
     * Creates new form ThongTinHanhTrinh_GUI
     */
    public ThongTinHanhTrinh_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_main = new javax.swing.JPanel();
        pnl_header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnl_container = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setPreferredSize(new java.awt.Dimension(1200, 955));
        setLayout(new java.awt.BorderLayout());

        pnl_main.setBackground(new java.awt.Color(255, 255, 255));
        pnl_main.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_main.setLayout(new java.awt.BorderLayout());

        pnl_header.setBackground(new java.awt.Color(123, 17, 19));
        pnl_header.setPreferredSize(new java.awt.Dimension(660, 55));
        pnl_header.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/bookTicket/List.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(32, 32));
        pnl_header.add(jLabel1);
        jLabel1.setBounds(30, 10, 30, 30);

        pnl_main.add(pnl_header, java.awt.BorderLayout.PAGE_START);

        pnl_container.setBackground(new java.awt.Color(255, 255, 255));
        pnl_container.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        pnl_container.setLayout(new javax.swing.BoxLayout(pnl_container, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel11.setLayout(new java.awt.BorderLayout());
        pnl_container.add(jPanel11);

        jPanel10.setLayout(new java.awt.BorderLayout());
        pnl_container.add(jPanel10);

        jPanel9.setLayout(new java.awt.BorderLayout());
        pnl_container.add(jPanel9);

        jPanel8.setLayout(new java.awt.BorderLayout());
        pnl_container.add(jPanel8);

        jPanel6.setLayout(new java.awt.BorderLayout());
        pnl_container.add(jPanel6);

        jPanel5.setLayout(new java.awt.BorderLayout());
        pnl_container.add(jPanel5);

        jPanel4.setLayout(new java.awt.BorderLayout());
        pnl_container.add(jPanel4);

        jPanel3.setLayout(new java.awt.BorderLayout());
        pnl_container.add(jPanel3);

        pnl_main.add(pnl_container, java.awt.BorderLayout.CENTER);

        pnl_main.putClientProperty(FlatClientProperties.STYLE, "arc:5;");
        add(pnl_main, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel pnl_container;
    private javax.swing.JPanel pnl_header;
    private javax.swing.JPanel pnl_main;
    // End of variables declaration//GEN-END:variables
}
