/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.components;

import dao.ThongKe_DAO;
import java.awt.Color;
import java.awt.Font;
import java.text.DecimalFormat;
import java.util.*;
import java.text.SimpleDateFormat;
import javax.swing.JLabel;

/**
 *
 * @author Administrator
 */
public class BieuDoTongDoanhThu extends javax.swing.JPanel {
    private ThongKe_DAO thongKeDAO;
    private JLabel lblTitle;
    private JLabel lblDoanhThuHomNay;
    private JLabel lblTyLeThayDoi;
    /**
     * Creates new form SoVeBanDuoc
     */
    public BieuDoTongDoanhThu() {
        initComponents();
        thongKeDAO = new ThongKe_DAO();
        
        // Title
        lblTitle = new JLabel("Doanh thu hôm nay");
        lblTitle.setFont(new Font("Segoe UI", Font.BOLD, 16));
        lblTitle.setForeground(Color.decode("#333333"));
        lblTitle.setBounds(20, 20, 260, 30);
        panelShadow1.add(lblTitle);
        
        // Doanh thu hôm nay (số tiền lớn, nổi bật)
        lblDoanhThuHomNay = new JLabel("0đ");
        lblDoanhThuHomNay.setFont(new Font("Segoe UI", Font.BOLD, 32));
        lblDoanhThuHomNay.setForeground(Color.decode("#2196F3"));
        lblDoanhThuHomNay.setBounds(20, 60, 260, 50);
        panelShadow1.add(lblDoanhThuHomNay);
        
        // Tỷ lệ thay đổi so với hôm qua
        lblTyLeThayDoi = new JLabel("Không đổi so với hôm qua");
        lblTyLeThayDoi.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        lblTyLeThayDoi.setForeground(Color.decode("#666666"));
        lblTyLeThayDoi.setBounds(20, 120, 260, 30);
        panelShadow1.add(lblTyLeThayDoi);
        
        // Load dữ liệu
        loadDuLieu();
    }
    
     // Hàm load dữ liệu
    public void loadDuLieu() {
        try {
            Map<String, Double> duLieu = thongKeDAO.getDoanhThuHomNayVaHomQua();
            
            double doanhThuHomQua = duLieu.getOrDefault("homQua", 0.0);
            double doanhThuHomNay = duLieu.getOrDefault("homNay", 0.0);
            
            // Format số tiền
            DecimalFormat dfTien = new DecimalFormat("#,###");
            DecimalFormat dfTyLe = new DecimalFormat("#0.0");
            
            // Cập nhật doanh thu hôm nay
            lblDoanhThuHomNay.setText(dfTien.format(doanhThuHomNay) + "đ");
            
            // Tính tỷ lệ thay đổi
            double tyLeThayDoi = 0.0;
            if (doanhThuHomQua > 0) {
                tyLeThayDoi = ((doanhThuHomNay - doanhThuHomQua) / doanhThuHomQua) * 100;
            } else if (doanhThuHomNay > 0) {
                tyLeThayDoi = 100.0;
            }
            
            // Cập nhật label tỷ lệ với icon và màu sắc
            String text = "";
            Color color;
            
            if (tyLeThayDoi > 0) {
                text = "↑ Tăng " + dfTyLe.format(tyLeThayDoi) + "% so với hôm qua";
                color = Color.decode("#4caf50"); // Xanh lá
            } else if (tyLeThayDoi < 0) {
                text = "↓ Giảm " + dfTyLe.format(Math.abs(tyLeThayDoi)) + "% so với hôm qua";
                color = Color.decode("#f44336"); // Đỏ
            } else {
                text = "Không đổi so với hôm qua";
                color = Color.decode("#666666"); // Xám
            }
            
            lblTyLeThayDoi.setText(text);
            lblTyLeThayDoi.setForeground(color);
            
        } catch (Exception e) {
            e.printStackTrace();
            System.err.println("Lỗi khi load dữ liệu: " + e.getMessage());
        }
    }
    
    // Hàm refresh để cập nhật lại dữ liệu
    public void refreshBieuDo() {
        loadDuLieu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelShadow1 = new raven2.panel.PanelShadow();

        setPreferredSize(new java.awt.Dimension(295, 187));

        panelShadow1.setRadius(30);
        panelShadow1.setShadowColor(new java.awt.Color(102, 204, 255));
        panelShadow1.setShadowOpacity(0.4F);
        panelShadow1.setShadowSize(4);
        panelShadow1.setShadowType(raven2.panel.PanelShadow.ShadowType.BOT);
        panelShadow1.setLayout(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private raven2.panel.PanelShadow panelShadow1;
    // End of variables declaration//GEN-END:variables
}
