/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.components;

/**
 *
 * @author Công Hoàng
 */
public class BieuDoTyLeHuyVe extends javax.swing.JPanel {
    
    public BieuDoTyLeHuyVe() {
        initComponents();
        
    }
    
     /**
     * Refresh dữ liệu biểu đồ
     */
    public void refresh() {
        if (tyLeHuyVe2 != null) {
            tyLeHuyVe2.refresh();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tyLeHuyVe1 = new gui.components.TyLeHuyVe();
        panelShadow1 = new raven2.panel.PanelShadow();
        tyLeHuyVe2 = new gui.components.TyLeHuyVe();

        setLayout(new java.awt.BorderLayout());

        panelShadow1.setRadius(30);
        panelShadow1.setShadowColor(new java.awt.Color(102, 204, 255));
        panelShadow1.setShadowOpacity(0.4F);
        panelShadow1.setShadowSize(4);
        panelShadow1.setShadowType(raven2.panel.PanelShadow.ShadowType.BOT);
        panelShadow1.setLayout(new java.awt.BorderLayout());
        panelShadow1.add(tyLeHuyVe2, java.awt.BorderLayout.CENTER);

        add(panelShadow1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private raven2.panel.PanelShadow panelShadow1;
    private gui.components.TyLeHuyVe tyLeHuyVe1;
    private gui.components.TyLeHuyVe tyLeHuyVe2;
    // End of variables declaration//GEN-END:variables
}
