/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.components;

import com.raven.chart.ModelChart;
import dao.ThongKe_DAO;
import java.awt.Color;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Map;


/**
 *
 * @author Administrator
 */
public class BieuDoSoLuongHanhKhach extends javax.swing.JPanel {
    private ThongKe_DAO thongKeDAO;
    private DecimalFormat df = new DecimalFormat("#,##0");
    /**
     * Creates new form BieuDoDoanhThuTheoThang
     */
    public BieuDoSoLuongHanhKhach() {
        initComponents();
        
         thongKeDAO = new ThongKe_DAO();
        
        // Cấu hình biểu đồ với 1 đường
        blankPlotChart1.addLegend("Số Hành Khách", Color.decode("#00C9FF"));
        
        // Cập nhật label
        jLabel1.setText("Số Lượng Hành Khách 7 Ngày Gần Nhất");
        jLabel1.setFont(jLabel1.getFont().deriveFont(java.awt.Font.BOLD, 16));
        
        // Load dữ liệu
        if (!java.beans.Beans.isDesignTime()) {
            loadData();
        }
    }
    
    /**
     * Tải dữ liệu số lượng hành khách 7 ngày gần nhất
     */
    public void loadData() {
        try {
            // Lấy dữ liệu số hành khách
            Map<String, Integer> hanhKhachData = thongKeDAO.getSoLuongHanhKhach7NgayGanNhat();
            
            if (hanhKhachData == null || hanhKhachData.isEmpty()) {
                blankPlotChart1.addData(new ModelChart("Không có dữ liệu", new double[]{0}));
                return;
            }
            
            SimpleDateFormat sdfInput = new SimpleDateFormat("yyyy-MM-dd");
            SimpleDateFormat sdfOutput = new SimpleDateFormat("dd/MM");
            
            // Duyệt qua từng ngày và thêm dữ liệu
            for (Map.Entry<String, Integer> entry : hanhKhachData.entrySet()) {
                String ngay = entry.getKey();
                int soHanhKhach = entry.getValue();
                
                try {
                    // Format lại ngày để hiển thị đẹp hơn (dd/MM)
                    String ngayHienThi = sdfOutput.format(sdfInput.parse(ngay));
                    
                    // Thêm dữ liệu với 1 giá trị: số hành khách
                    blankPlotChart1.addData(new ModelChart(ngayHienThi, 
                        new double[]{soHanhKhach}));
                    
                } catch (Exception e) {
                    // Nếu parse lỗi thì dùng ngày gốc
                    blankPlotChart1.addData(new ModelChart(ngay, 
                        new double[]{soHanhKhach}));
                }
            }
            
            blankPlotChart1.start();
            
        } catch (Exception e) {
            e.printStackTrace();
            blankPlotChart1.addData(new ModelChart("Lỗi tải dữ liệu", new double[]{0}));
        }
    }
    
    /**
     * Làm mới dữ liệu biểu đồ
     */
    public void refresh() {
        blankPlotChart1.clear();
        loadData();
        repaint();
    }
    
    /**
     * Lấy tổng số hành khách trong 7 ngày
     */
    public int getTongSoHanhKhach() {
        return thongKeDAO.getTongSoLuongHanhKhach7NgayGanNhat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelShadow1 = new raven2.panel.PanelShadow();
        blankPlotChart1 = new com.raven.chart.Chart();
        jLabel1 = new javax.swing.JLabel();

        panelShadow1.setRadius(30);
        panelShadow1.setShadowColor(new java.awt.Color(102, 204, 255));
        panelShadow1.setShadowOpacity(0.4F);
        panelShadow1.setShadowSize(4);
        panelShadow1.setShadowType(raven2.panel.PanelShadow.ShadowType.BOT);

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout panelShadow1Layout = new javax.swing.GroupLayout(panelShadow1);
        panelShadow1.setLayout(panelShadow1Layout);
        panelShadow1Layout.setHorizontalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(blankPlotChart1, javax.swing.GroupLayout.DEFAULT_SIZE, 1005, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelShadow1Layout.setVerticalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(blankPlotChart1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.chart.Chart blankPlotChart1;
    private javax.swing.JLabel jLabel1;
    private raven2.panel.PanelShadow panelShadow1;
    // End of variables declaration//GEN-END:variables

    
}
