/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.components;

import dao.ThongKe_DAO;
import java.awt.Color;
import java.awt.Font;
import java.util.*;
import java.text.SimpleDateFormat;
import javax.swing.JLabel;


/**
 *
 * @author Administrator
 */
public class BieuDoSoVeBanDuoc extends javax.swing.JPanel {
     private ThongKe_DAO thongKeDAO;
     private JLabel lblSoVeHomNay;

    /**
     * Creates new form SoVeBanDuoc
     */
    public BieuDoSoVeBanDuoc() {
        initComponents();
        thongKeDAO = new ThongKe_DAO();
        
        // Tạo và cấu hình JLabel
        lblSoVeHomNay = new JLabel("Hôm nay: 0 vé");
        lblSoVeHomNay.setFont(new Font("Segoe UI", Font.BOLD, 14));
        lblSoVeHomNay.setForeground(Color.decode("#018e42"));
        lblSoVeHomNay.setBounds(10, 50, 150, 25);
        panelShadow1.add(lblSoVeHomNay);
        
        curveLineChart1.setTitle("Số vé bán");
        curveLineChart1.addLegend("Vé", Color.decode("#018e42"), Color.decode("#018e42"));
        curveLineChart1.setTitleColor(Color.decode("#333333"));
        
        curveLineChart1.clear();
        
        // Load dữ liệu lên biểu đồ
        loadDuLieuBieuDo();
    }
    
    // Hàm load dữ liệu lên biểu đồ
    public void loadDuLieuBieuDo() {
        try {
            curveLineChart1.clear();
            
            Map<String, Integer> duLieu = thongKeDAO.getSoVeBan7NgayGanNhat();
            
            // Lấy ngày hôm nay
            SimpleDateFormat sdfToday = new SimpleDateFormat("yyyy-MM-dd");
            String ngayHomNay = sdfToday.format(new java.util.Date());
            
            // Cập nhật số vé bán được hôm nay
            Integer soVeHomNay = duLieu.getOrDefault(ngayHomNay, 0);
            lblSoVeHomNay.setText("Hôm nay: " + soVeHomNay + " vé");
            
            // Kiểm tra nếu không có dữ liệu
            if (duLieu == null || duLieu.isEmpty()) {
                System.out.println("Không có dữ liệu để hiển thị");
                // Tạo dữ liệu mặc định cho 7 ngày với giá trị 0
                Calendar cal = Calendar.getInstance();
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM");
                
                for (int i = 6; i >= 0; i--) {
                    cal.setTime(new java.util.Date());
                    cal.add(Calendar.DAY_OF_MONTH, -i);
                    String ngay = sdf.format(cal.getTime());
                    curveLineChart1.addData(new raven2.chart.ModelChart(ngay, new double[]{0}));
                }
            } else {
                // Tạo map đầy đủ cho 7 ngày (bổ sung các ngày thiếu)
                Calendar cal = Calendar.getInstance();
                SimpleDateFormat sdfKey = new SimpleDateFormat("yyyy-MM-dd");
                SimpleDateFormat sdfDisplay = new SimpleDateFormat("dd/MM");
                
                for (int i = 6; i >= 0; i--) {
                    cal.setTime(new java.util.Date());
                    cal.add(Calendar.DAY_OF_MONTH, -i);
                    
                    String ngayKey = sdfKey.format(cal.getTime());
                    String ngayDisplay = sdfDisplay.format(cal.getTime());
                    
                    // Lấy số vé từ dữ liệu, nếu không có thì = 0
                    Integer soVe = duLieu.getOrDefault(ngayKey, 0);
                    
                    curveLineChart1.addData(new raven2.chart.ModelChart(ngayDisplay, new double[]{soVe.doubleValue()}));
                }
            }
            
            curveLineChart1.start();
            
        } catch (Exception e) {
            e.printStackTrace();
            System.err.println("Lỗi khi load dữ liệu biểu đồ: " + e.getMessage());
        }
    }

    
    // Hàm refresh để cập nhật lại dữ liệu
    public void refreshBieuDo() {
        loadDuLieuBieuDo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelShadow1 = new raven2.panel.PanelShadow();
        curveLineChart1 = new raven2.chart.CurveLineChart();

        setPreferredSize(new java.awt.Dimension(310, 187));

        panelShadow1.setRadius(30);
        panelShadow1.setShadowColor(new java.awt.Color(102, 204, 255));
        panelShadow1.setShadowOpacity(0.4F);
        panelShadow1.setShadowSize(4);
        panelShadow1.setShadowType(raven2.panel.PanelShadow.ShadowType.BOT);
        panelShadow1.setLayout(null);

        curveLineChart1.setFillColor(true);
        panelShadow1.add(curveLineChart1);
        curveLineChart1.setBounds(0, 30, 300, 170);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private raven2.chart.CurveLineChart curveLineChart1;
    private raven2.panel.PanelShadow panelShadow1;
    // End of variables declaration//GEN-END:variables
}
