/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.components;

import entity.ChuyenTau;
import entity.ToaTau;
import java.awt.Dimension;
import javax.swing.Box;
import javax.swing.JPanel;

/**
 *
 * @author CÔNG HOÀNG
 */
public class ChonChoNgoi extends javax.swing.JPanel {

    /**
     * Creates new form ChonChoNgoi
     */
    public ChonChoNgoi() {
        initComponents();
    }
    
    public void setData(ToaTau toaTau) {
        lbl_soToa.setText("Toa số " + String.valueOf(toaTau.getSoHieuToa()));
    }
    
    public void setContent(JPanel panel) {
        pnl_contain.add(panel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelShadow3 = new gui.custom.PanelShadow();
        lbl_soToa = new javax.swing.JLabel();
        pnl_contain = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(2147483647, 300));
        setMinimumSize(new java.awt.Dimension(101, 300));
        setPreferredSize(new java.awt.Dimension(101, 300));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        panelShadow3.setBackground(new java.awt.Color(255, 255, 255));
        panelShadow3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panelShadow3.setMaximumSize(new java.awt.Dimension(2147483647, 300));
        panelShadow3.setMinimumSize(new java.awt.Dimension(101, 300));
        panelShadow3.setPreferredSize(new java.awt.Dimension(101, 300));
        panelShadow3.setShadowOpacity(0.2F);
        panelShadow3.setShadowSize(4);
        panelShadow3.setLayout(new java.awt.BorderLayout());

        lbl_soToa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_soToa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_soToa.setText("Toa số 1");
        panelShadow3.add(lbl_soToa, java.awt.BorderLayout.PAGE_START);

        pnl_contain.setBackground(new java.awt.Color(255, 255, 255));
        pnl_contain.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnl_contain.setLayout(new javax.swing.BoxLayout(pnl_contain, javax.swing.BoxLayout.LINE_AXIS));
        panelShadow3.add(pnl_contain, java.awt.BorderLayout.CENTER);

        add(panelShadow3);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_soToa;
    private gui.custom.PanelShadow panelShadow3;
    private javax.swing.JPanel pnl_contain;
    // End of variables declaration//GEN-END:variables
}
