/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.components;

/**
 *
 * @author CÔNG HOÀNG
 */
public class ChonChuyenTau extends javax.swing.JPanel {

    /**
     * Creates new form ChonChuyenTau
     */
    public ChonChuyenTau() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelShadow1 = new gui.custom.PanelShadow();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        roundedTextField1 = new gui.custom.RoundedTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(400, 250));
        setLayout(new java.awt.BorderLayout());

        panelShadow1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        panelShadow1.setMaximumSize(new java.awt.Dimension(390, 250));
        panelShadow1.setMinimumSize(new java.awt.Dimension(390, 250));
        panelShadow1.setPreferredSize(new java.awt.Dimension(390, 250));
        panelShadow1.setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(100, 60));
        jPanel1.setLayout(new java.awt.GridLayout(2, 2));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Số hiệu tàu");
        jPanel1.add(jLabel1);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Số lượng chỗ trống");
        jPanel1.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(123, 17, 19));
        jLabel3.setText("SE1");
        jPanel1.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(123, 17, 19));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("100");
        jPanel1.add(jLabel4);

        panelShadow1.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setPreferredSize(new java.awt.Dimension(10, 30));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jLabel8.setText("--------------------------------------------------------------------------------------------------------------------------------------------------");
        jPanel4.add(jLabel8);

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setLayout(new java.awt.GridLayout(1, 3));

        jPanel3.setLayout(new java.awt.GridLayout(3, 1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Thời gian đi");
        jPanel3.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(123, 17, 19));
        jLabel6.setText("06:00");
        jPanel3.add(jLabel6);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("T7 01/11/2025");
        jPanel3.add(jLabel7);

        jPanel5.add(jPanel3);

        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 0, 0, 0));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/train.png"))); // NOI18N
        jLabel14.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel7.add(jLabel14);

        roundedTextField1.setEditable(false);
        roundedTextField1.setBackground(new java.awt.Color(76, 175, 80));
        roundedTextField1.setForeground(new java.awt.Color(255, 255, 255));
        roundedTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        roundedTextField1.setText("34 tiếng 10 phút");
        roundedTextField1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        roundedTextField1.setEnabled(false);
        roundedTextField1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        roundedTextField1.setRound(20);
        jPanel7.add(roundedTextField1);

        jPanel5.add(jPanel7);

        jPanel6.setLayout(new java.awt.GridLayout(3, 1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Thời gian đến");
        jPanel6.add(jLabel9);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(123, 17, 19));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("06:00");
        jPanel6.add(jLabel10);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("T7 01/11/2025");
        jPanel6.add(jLabel11);

        jPanel5.add(jPanel6);

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        panelShadow1.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(panelShadow1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private gui.custom.PanelShadow panelShadow1;
    private gui.custom.RoundedTextField roundedTextField1;
    // End of variables declaration//GEN-END:variables
}
