/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.components;

import java.awt.Font;
import java.util.Date;
import javax.swing.BorderFactory;

/**
 *
 * @author CÔNG HOÀNG
 */
public class ThongTinVe extends javax.swing.JPanel {
    private String maGhe;
    /**
     * Creates new form ThongTinVe
     */
    
    public class ThongTinHanhKhach {
    private String maGhe;
    private String hoTen;
    private String CCCD;
    private Date ngaySinh;
    private String loaiVe;
    public void setMaGhe(String maGhe) { this.maGhe = maGhe; }
    public void setHoTen(String hoTen) { this.hoTen = hoTen; }
    public void setCCCD(String CCCD) { this.CCCD = CCCD; }
    public void setNgaySinh(Date ngaySinh) { this.ngaySinh = ngaySinh; }
    public void setLoaiVe(String loaiVe) { this.loaiVe = loaiVe; }

    public String getMaGhe() { return maGhe; }
    public String getHoTen() { return hoTen; }
    public String getCCCD() { return CCCD; }
    public Date getNgaySinh() { return ngaySinh; }
    public String getLoaiVe() { return loaiVe; }
    }

    public ThongTinVe(String thongTin, String maGhe) {
        initComponents();
        pnl_thongTinHK.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createTitledBorder(
                null,
                thongTin,
                 javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                javax.swing.border.TitledBorder.DEFAULT_POSITION,
                new Font("Segoe UI", Font.BOLD, 14)
            ),
            BorderFactory.createEmptyBorder(10, 10, 10, 10)
        ));
        this.maGhe = maGhe;
    }
    
    public String getMaGhe() {
        return maGhe;
    }
    
    public ThongTinHanhKhach getThongTin() {
        ThongTinHanhKhach info = new ThongTinHanhKhach();
        info.setMaGhe(maGhe);
        info.setHoTen(txt_hoTen.getText());
        info.setCCCD(txt_cccd.getText());
        info.setNgaySinh(date_ngaySinh.getDate());
        info.setLoaiVe((String) cbo_loaiVe.getSelectedItem());
        return info;
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_thongTinHK = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_hoTen = new javax.swing.JTextField();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jLabel6 = new javax.swing.JLabel();
        txt_cccd = new javax.swing.JTextField();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel14 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        date_ngaySinh = new com.toedter.calendar.JDateChooser();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jLabel1 = new javax.swing.JLabel();
        cbo_loaiVe = new javax.swing.JComboBox<>();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        pnl_thongTinHK.setBackground(new java.awt.Color(255, 255, 255));
        pnl_thongTinHK.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14)), javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10))); // NOI18N
        pnl_thongTinHK.setMaximumSize(new java.awt.Dimension(32767, 200));
        pnl_thongTinHK.setLayout(new javax.swing.BoxLayout(pnl_thongTinHK, javax.swing.BoxLayout.Y_AXIS));

        jPanel13.setMaximumSize(new java.awt.Dimension(32767, 50));
        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setText("Họ tên:");
        jLabel4.setPreferredSize(new java.awt.Dimension(60, 16));
        jPanel13.add(jLabel4);
        jPanel13.add(txt_hoTen);
        jPanel13.add(filler2);

        jLabel6.setText("CCCD:");
        jLabel6.setPreferredSize(new java.awt.Dimension(60, 16));
        jPanel13.add(jLabel6);
        jPanel13.add(txt_cccd);

        pnl_thongTinHK.add(jPanel13);
        pnl_thongTinHK.add(filler4);

        jPanel14.setMaximumSize(new java.awt.Dimension(32767, 50));
        jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.LINE_AXIS));

        jLabel8.setText("NS:");
        jLabel8.setMaximumSize(new java.awt.Dimension(60, 16));
        jLabel8.setMinimumSize(new java.awt.Dimension(60, 16));
        jLabel8.setPreferredSize(new java.awt.Dimension(60, 16));
        jPanel14.add(jLabel8);

        date_ngaySinh.setMaximumSize(txt_hoTen.getMaximumSize());
        date_ngaySinh.setPreferredSize(txt_hoTen.getPreferredSize());
        jPanel14.add(date_ngaySinh);
        jPanel14.add(filler1);

        jLabel1.setText("Loại vé:");
        jLabel1.setPreferredSize(new java.awt.Dimension(60, 16));
        jPanel14.add(jLabel1);

        cbo_loaiVe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Người lớn ", "Trẻ em", "Sinh viên", "Người cao tuổi" }));
        cbo_loaiVe.setMaximumSize(txt_hoTen.getMaximumSize());
        cbo_loaiVe.setPreferredSize(txt_hoTen.getPreferredSize());
        jPanel14.add(cbo_loaiVe);

        pnl_thongTinHK.add(jPanel14);
        pnl_thongTinHK.add(filler3);

        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Giá vé: ");
        jPanel1.add(jLabel2);

        pnl_thongTinHK.add(jPanel1);

        add(pnl_thongTinHK);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbo_loaiVe;
    private com.toedter.calendar.JDateChooser date_ngaySinh;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel pnl_thongTinHK;
    private javax.swing.JTextField txt_cccd;
    private javax.swing.JTextField txt_hoTen;
    // End of variables declaration//GEN-END:variables
}
