/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.components;

import entity.ChuyenTau;

/**
 *
 * @author CÔNG HOÀNG
 */
public class ThongTinChuyenTau extends javax.swing.JPanel {
    private final ChuyenTau chuyenTau;
    /**
     * Creates new form ChonChuyenTau
     * @param chuyenTau
     */
    public ThongTinChuyenTau(ChuyenTau chuyenTau) {
        initComponents();
        this.chuyenTau = chuyenTau;
        init();
    }
    
    private void init() {
        String tenTau = chuyenTau.getTau().getTenTau();
        lbl_soHieuTau.setText(tenTau.substring(tenTau.lastIndexOf(" ") + 1));
        lbl_soChoTrong.setText(String.valueOf(chuyenTau.getSoGheConTrong()));
        lbl_thoiGianDi.setText(chuyenTau.getThoiGianDi().toLocalTime().toString());
        lbl_thoiGianDen.setText(chuyenTau.getThoiGianDen().toLocalTime().toString());
        lbl_ngayDi.setText(chuyenTau.getThoiGianDi().toLocalDate().toString());
        lbl_ngayDen.setText(chuyenTau.getThoiGianDen().toLocalDate().toString());
        lbl_thoiGianDiChuyen.setText(String.valueOf(chuyenTau.getTuyenDuong().getThoiGianDiChuyen()) + " tiếng");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelShadow1 = new gui.custom.PanelShadow();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_soHieuTau = new javax.swing.JLabel();
        lbl_soChoTrong = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbl_thoiGianDi = new javax.swing.JLabel();
        lbl_ngayDi = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        lbl_thoiGianDiChuyen = new gui.custom.RoundedTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lbl_thoiGianDen = new javax.swing.JLabel();
        lbl_ngayDen = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(320, 200));
        setMinimumSize(new java.awt.Dimension(320, 200));
        setPreferredSize(new java.awt.Dimension(320, 200));
        setLayout(new java.awt.BorderLayout());

        panelShadow1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        panelShadow1.setMaximumSize(new java.awt.Dimension(320, 200));
        panelShadow1.setMinimumSize(new java.awt.Dimension(320, 200));
        panelShadow1.setPreferredSize(new java.awt.Dimension(320, 200));
        panelShadow1.setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(100, 60));
        jPanel1.setLayout(new java.awt.GridLayout(2, 2));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Số hiệu tàu");
        jPanel1.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Số lượng chỗ trống");
        jPanel1.add(jLabel2);

        lbl_soHieuTau.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_soHieuTau.setForeground(new java.awt.Color(123, 17, 19));
        lbl_soHieuTau.setText("SE1");
        jPanel1.add(lbl_soHieuTau);

        lbl_soChoTrong.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_soChoTrong.setForeground(new java.awt.Color(123, 17, 19));
        lbl_soChoTrong.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_soChoTrong.setText("100");
        jPanel1.add(lbl_soChoTrong);

        panelShadow1.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jLabel8.setText("--------------------------------------------------------------------------------------------------------------------------------------------------");
        jPanel4.add(jLabel8);

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setLayout(new java.awt.GridLayout(1, 3));

        jPanel3.setLayout(new java.awt.GridLayout(3, 1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Thời gian đi");
        jPanel3.add(jLabel5);

        lbl_thoiGianDi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_thoiGianDi.setForeground(new java.awt.Color(123, 17, 19));
        lbl_thoiGianDi.setText("06:00");
        jPanel3.add(lbl_thoiGianDi);

        lbl_ngayDi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_ngayDi.setText("01/11/2025");
        jPanel3.add(lbl_ngayDi);

        jPanel5.add(jPanel3);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/train.png"))); // NOI18N
        jLabel14.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel7.add(jLabel14);

        lbl_thoiGianDiChuyen.setEditable(false);
        lbl_thoiGianDiChuyen.setBackground(new java.awt.Color(76, 175, 80));
        lbl_thoiGianDiChuyen.setForeground(new java.awt.Color(255, 255, 255));
        lbl_thoiGianDiChuyen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lbl_thoiGianDiChuyen.setText("30 tiếng");
        lbl_thoiGianDiChuyen.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        lbl_thoiGianDiChuyen.setEnabled(false);
        lbl_thoiGianDiChuyen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_thoiGianDiChuyen.setPreferredSize(new java.awt.Dimension(90, 42));
        lbl_thoiGianDiChuyen.setRound(15);
        jPanel7.add(lbl_thoiGianDiChuyen);

        jPanel5.add(jPanel7);

        jPanel6.setLayout(new java.awt.GridLayout(3, 1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Thời gian đến");
        jPanel6.add(jLabel9);

        lbl_thoiGianDen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_thoiGianDen.setForeground(new java.awt.Color(123, 17, 19));
        lbl_thoiGianDen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_thoiGianDen.setText("06:00");
        jPanel6.add(lbl_thoiGianDen);

        lbl_ngayDen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_ngayDen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_ngayDen.setText("01/11/2025");
        jPanel6.add(lbl_ngayDen);

        jPanel5.add(jPanel6);

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        panelShadow1.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(panelShadow1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lbl_ngayDen;
    private javax.swing.JLabel lbl_ngayDi;
    private javax.swing.JLabel lbl_soChoTrong;
    private javax.swing.JLabel lbl_soHieuTau;
    private javax.swing.JLabel lbl_thoiGianDen;
    private javax.swing.JLabel lbl_thoiGianDi;
    private gui.custom.RoundedTextField lbl_thoiGianDiChuyen;
    private gui.custom.PanelShadow panelShadow1;
    // End of variables declaration//GEN-END:variables
}
