/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.components;

/**
 *
 * @author CÔNG HOÀNG
 */
public class ToaGiuongNam6 extends javax.swing.JPanel {

    /**
     * Creates new form ToaGiuongNam6
     */
    public ToaGiuongNam6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel48 = new javax.swing.JPanel();
        jPanel49 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        roundedButton1 = new gui.custom.RoundedButton();
        roundedButton3 = new gui.custom.RoundedButton();
        roundedButton4 = new gui.custom.RoundedButton();
        roundedButton2 = new gui.custom.RoundedButton();
        roundedButton29 = new gui.custom.RoundedButton();
        roundedButton30 = new gui.custom.RoundedButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        roundedButton31 = new gui.custom.RoundedButton();
        roundedButton32 = new gui.custom.RoundedButton();
        roundedButton33 = new gui.custom.RoundedButton();
        roundedButton34 = new gui.custom.RoundedButton();
        roundedButton35 = new gui.custom.RoundedButton();
        roundedButton36 = new gui.custom.RoundedButton();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        jPanel27 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        roundedButton37 = new gui.custom.RoundedButton();
        roundedButton38 = new gui.custom.RoundedButton();
        roundedButton39 = new gui.custom.RoundedButton();
        roundedButton40 = new gui.custom.RoundedButton();
        roundedButton41 = new gui.custom.RoundedButton();
        roundedButton42 = new gui.custom.RoundedButton();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        jPanel30 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        roundedButton43 = new gui.custom.RoundedButton();
        roundedButton44 = new gui.custom.RoundedButton();
        roundedButton45 = new gui.custom.RoundedButton();
        roundedButton46 = new gui.custom.RoundedButton();
        roundedButton47 = new gui.custom.RoundedButton();
        roundedButton48 = new gui.custom.RoundedButton();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        jPanel33 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        roundedButton49 = new gui.custom.RoundedButton();
        roundedButton50 = new gui.custom.RoundedButton();
        roundedButton51 = new gui.custom.RoundedButton();
        roundedButton52 = new gui.custom.RoundedButton();
        roundedButton53 = new gui.custom.RoundedButton();
        roundedButton54 = new gui.custom.RoundedButton();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        jPanel36 = new javax.swing.JPanel();
        jPanel37 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        roundedButton55 = new gui.custom.RoundedButton();
        roundedButton56 = new gui.custom.RoundedButton();
        roundedButton57 = new gui.custom.RoundedButton();
        roundedButton58 = new gui.custom.RoundedButton();
        roundedButton59 = new gui.custom.RoundedButton();
        roundedButton60 = new gui.custom.RoundedButton();
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        jPanel39 = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel41 = new javax.swing.JPanel();
        roundedButton61 = new gui.custom.RoundedButton();
        roundedButton62 = new gui.custom.RoundedButton();
        roundedButton63 = new gui.custom.RoundedButton();
        roundedButton64 = new gui.custom.RoundedButton();
        roundedButton65 = new gui.custom.RoundedButton();
        roundedButton66 = new gui.custom.RoundedButton();

        setMaximumSize(new java.awt.Dimension(770, 250));
        setMinimumSize(new java.awt.Dimension(770, 250));
        setPreferredSize(new java.awt.Dimension(770, 250));
        setLayout(new java.awt.BorderLayout());

        jPanel48.setBackground(new java.awt.Color(255, 255, 255));
        jPanel48.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        jPanel48.setPreferredSize(new java.awt.Dimension(681, 50));
        jPanel48.setLayout(new javax.swing.BoxLayout(jPanel48, javax.swing.BoxLayout.LINE_AXIS));

        jPanel49.setBackground(new java.awt.Color(255, 255, 255));
        jPanel49.setLayout(new java.awt.BorderLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TOA SỐ 2: GIƯỜNG NẰM KHOANG 6 ĐIỀU HÒA");
        jPanel49.add(jLabel2, java.awt.BorderLayout.CENTER);

        jCheckBox3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox3.setText("  Chọn tất cả");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel49.add(jCheckBox3, java.awt.BorderLayout.LINE_START);

        jPanel48.add(jPanel49);

        add(jPanel48, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));
        jPanel23.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 0, 0, 0));
        jPanel23.setLayout(new java.awt.GridLayout(3, 1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("T3");
        jPanel23.add(jLabel11);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("T2");
        jPanel23.add(jLabel9);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("T1");
        jPanel23.add(jLabel10);

        jPanel1.add(jPanel23);
        jPanel1.add(filler7);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(100, 32767));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Khoang 1");
        jPanel3.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setLayout(new java.awt.GridLayout(3, 2, 8, 8));

        roundedButton1.setText("5");
        roundedButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        roundedButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundedButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(roundedButton1);

        roundedButton3.setText("6");
        roundedButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel4.add(roundedButton3);

        roundedButton4.setText("3");
        roundedButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel4.add(roundedButton4);

        roundedButton2.setText("4");
        roundedButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        roundedButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundedButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(roundedButton2);

        roundedButton29.setText("1");
        roundedButton29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel4.add(roundedButton29);

        roundedButton30.setText("2");
        roundedButton30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel4.add(roundedButton30);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2);
        jPanel1.add(filler1);

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));
        jPanel24.setMaximumSize(new java.awt.Dimension(100, 32767));
        jPanel24.setLayout(new java.awt.BorderLayout());

        jPanel25.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel25.setLayout(new java.awt.BorderLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Khoang 2");
        jPanel25.add(jLabel12, java.awt.BorderLayout.CENTER);

        jPanel24.add(jPanel25, java.awt.BorderLayout.PAGE_START);

        jPanel26.setLayout(new java.awt.GridLayout(3, 2, 8, 8));

        roundedButton31.setText("3");
        roundedButton31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel26.add(roundedButton31);

        roundedButton32.setText("4");
        roundedButton32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel26.add(roundedButton32);

        roundedButton33.setText("1");
        roundedButton33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel26.add(roundedButton33);

        roundedButton34.setText("2");
        roundedButton34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel26.add(roundedButton34);

        roundedButton35.setText("1");
        roundedButton35.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel26.add(roundedButton35);

        roundedButton36.setText("2");
        roundedButton36.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel26.add(roundedButton36);

        jPanel24.add(jPanel26, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel24);
        jPanel1.add(filler8);

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));
        jPanel27.setMaximumSize(new java.awt.Dimension(100, 32767));
        jPanel27.setLayout(new java.awt.BorderLayout());

        jPanel28.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel28.setLayout(new java.awt.BorderLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Khoang 3");
        jPanel28.add(jLabel13, java.awt.BorderLayout.CENTER);

        jPanel27.add(jPanel28, java.awt.BorderLayout.PAGE_START);

        jPanel29.setLayout(new java.awt.GridLayout(3, 2, 8, 8));

        roundedButton37.setText("3");
        roundedButton37.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel29.add(roundedButton37);

        roundedButton38.setText("4");
        roundedButton38.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel29.add(roundedButton38);

        roundedButton39.setText("1");
        roundedButton39.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel29.add(roundedButton39);

        roundedButton40.setText("2");
        roundedButton40.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel29.add(roundedButton40);

        roundedButton41.setText("1");
        roundedButton41.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel29.add(roundedButton41);

        roundedButton42.setText("2");
        roundedButton42.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel29.add(roundedButton42);

        jPanel27.add(jPanel29, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel27);
        jPanel1.add(filler9);

        jPanel30.setBackground(new java.awt.Color(255, 255, 255));
        jPanel30.setMaximumSize(new java.awt.Dimension(100, 32767));
        jPanel30.setLayout(new java.awt.BorderLayout());

        jPanel31.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel31.setLayout(new java.awt.BorderLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Khoang 4");
        jPanel31.add(jLabel14, java.awt.BorderLayout.CENTER);

        jPanel30.add(jPanel31, java.awt.BorderLayout.PAGE_START);

        jPanel32.setLayout(new java.awt.GridLayout(3, 2, 8, 8));

        roundedButton43.setText("3");
        roundedButton43.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel32.add(roundedButton43);

        roundedButton44.setText("4");
        roundedButton44.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel32.add(roundedButton44);

        roundedButton45.setText("1");
        roundedButton45.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel32.add(roundedButton45);

        roundedButton46.setText("2");
        roundedButton46.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel32.add(roundedButton46);

        roundedButton47.setText("1");
        roundedButton47.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel32.add(roundedButton47);

        roundedButton48.setText("2");
        roundedButton48.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel32.add(roundedButton48);

        jPanel30.add(jPanel32, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel30);
        jPanel1.add(filler10);

        jPanel33.setBackground(new java.awt.Color(255, 255, 255));
        jPanel33.setMaximumSize(new java.awt.Dimension(100, 32767));
        jPanel33.setLayout(new java.awt.BorderLayout());

        jPanel34.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel34.setLayout(new java.awt.BorderLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Khoang 5");
        jPanel34.add(jLabel15, java.awt.BorderLayout.CENTER);

        jPanel33.add(jPanel34, java.awt.BorderLayout.PAGE_START);

        jPanel35.setLayout(new java.awt.GridLayout(3, 2, 8, 8));

        roundedButton49.setText("3");
        roundedButton49.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel35.add(roundedButton49);

        roundedButton50.setText("4");
        roundedButton50.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel35.add(roundedButton50);

        roundedButton51.setText("1");
        roundedButton51.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel35.add(roundedButton51);

        roundedButton52.setText("2");
        roundedButton52.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel35.add(roundedButton52);

        roundedButton53.setText("1");
        roundedButton53.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel35.add(roundedButton53);

        roundedButton54.setText("2");
        roundedButton54.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel35.add(roundedButton54);

        jPanel33.add(jPanel35, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel33);
        jPanel1.add(filler11);

        jPanel36.setBackground(new java.awt.Color(255, 255, 255));
        jPanel36.setMaximumSize(new java.awt.Dimension(100, 32767));
        jPanel36.setLayout(new java.awt.BorderLayout());

        jPanel37.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel37.setLayout(new java.awt.BorderLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Khoang 6");
        jPanel37.add(jLabel16, java.awt.BorderLayout.CENTER);

        jPanel36.add(jPanel37, java.awt.BorderLayout.PAGE_START);

        jPanel38.setLayout(new java.awt.GridLayout(3, 2, 8, 8));

        roundedButton55.setText("3");
        roundedButton55.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel38.add(roundedButton55);

        roundedButton56.setText("4");
        roundedButton56.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel38.add(roundedButton56);

        roundedButton57.setText("1");
        roundedButton57.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel38.add(roundedButton57);

        roundedButton58.setText("2");
        roundedButton58.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel38.add(roundedButton58);

        roundedButton59.setText("1");
        roundedButton59.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel38.add(roundedButton59);

        roundedButton60.setText("2");
        roundedButton60.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel38.add(roundedButton60);

        jPanel36.add(jPanel38, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel36);
        jPanel1.add(filler12);

        jPanel39.setBackground(new java.awt.Color(255, 255, 255));
        jPanel39.setMaximumSize(new java.awt.Dimension(100, 32767));
        jPanel39.setLayout(new java.awt.BorderLayout());

        jPanel40.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel40.setLayout(new java.awt.BorderLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Khoang 7");
        jPanel40.add(jLabel17, java.awt.BorderLayout.CENTER);

        jPanel39.add(jPanel40, java.awt.BorderLayout.PAGE_START);

        jPanel41.setLayout(new java.awt.GridLayout(3, 2, 8, 8));

        roundedButton61.setText("3");
        roundedButton61.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel41.add(roundedButton61);

        roundedButton62.setText("4");
        roundedButton62.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel41.add(roundedButton62);

        roundedButton63.setText("1");
        roundedButton63.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel41.add(roundedButton63);

        roundedButton64.setText("2");
        roundedButton64.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel41.add(roundedButton64);

        roundedButton65.setText("1");
        roundedButton65.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel41.add(roundedButton65);

        roundedButton66.setText("2");
        roundedButton66.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel41.add(roundedButton66);

        jPanel39.add(jPanel41, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel39);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void roundedButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundedButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roundedButton2ActionPerformed

    private void roundedButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundedButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roundedButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private gui.custom.RoundedButton roundedButton1;
    private gui.custom.RoundedButton roundedButton2;
    private gui.custom.RoundedButton roundedButton29;
    private gui.custom.RoundedButton roundedButton3;
    private gui.custom.RoundedButton roundedButton30;
    private gui.custom.RoundedButton roundedButton31;
    private gui.custom.RoundedButton roundedButton32;
    private gui.custom.RoundedButton roundedButton33;
    private gui.custom.RoundedButton roundedButton34;
    private gui.custom.RoundedButton roundedButton35;
    private gui.custom.RoundedButton roundedButton36;
    private gui.custom.RoundedButton roundedButton37;
    private gui.custom.RoundedButton roundedButton38;
    private gui.custom.RoundedButton roundedButton39;
    private gui.custom.RoundedButton roundedButton4;
    private gui.custom.RoundedButton roundedButton40;
    private gui.custom.RoundedButton roundedButton41;
    private gui.custom.RoundedButton roundedButton42;
    private gui.custom.RoundedButton roundedButton43;
    private gui.custom.RoundedButton roundedButton44;
    private gui.custom.RoundedButton roundedButton45;
    private gui.custom.RoundedButton roundedButton46;
    private gui.custom.RoundedButton roundedButton47;
    private gui.custom.RoundedButton roundedButton48;
    private gui.custom.RoundedButton roundedButton49;
    private gui.custom.RoundedButton roundedButton50;
    private gui.custom.RoundedButton roundedButton51;
    private gui.custom.RoundedButton roundedButton52;
    private gui.custom.RoundedButton roundedButton53;
    private gui.custom.RoundedButton roundedButton54;
    private gui.custom.RoundedButton roundedButton55;
    private gui.custom.RoundedButton roundedButton56;
    private gui.custom.RoundedButton roundedButton57;
    private gui.custom.RoundedButton roundedButton58;
    private gui.custom.RoundedButton roundedButton59;
    private gui.custom.RoundedButton roundedButton60;
    private gui.custom.RoundedButton roundedButton61;
    private gui.custom.RoundedButton roundedButton62;
    private gui.custom.RoundedButton roundedButton63;
    private gui.custom.RoundedButton roundedButton64;
    private gui.custom.RoundedButton roundedButton65;
    private gui.custom.RoundedButton roundedButton66;
    // End of variables declaration//GEN-END:variables
}
