/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.components;

/**
 *
 * @author Administrator
 */
public class TopChuyenDi extends javax.swing.JPanel {

    /**
     * Creates new form huhuhuhuhu
     */
    public TopChuyenDi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelShadow1 = new raven2.panel.PanelShadow();
        topChuyenDiDuocYeuThich1 = new gui.components.TopChuyenDiDuocYeuThich();

        setLayout(new java.awt.BorderLayout());

        panelShadow1.setRadius(30);
        panelShadow1.setShadowColor(new java.awt.Color(102, 204, 255));
        panelShadow1.setShadowOpacity(0.4F);
        panelShadow1.setShadowSize(4);
        panelShadow1.setShadowType(raven2.panel.PanelShadow.ShadowType.BOT);
        panelShadow1.setLayout(null);

        javax.swing.GroupLayout topChuyenDiDuocYeuThich1Layout = new javax.swing.GroupLayout(topChuyenDiDuocYeuThich1);
        topChuyenDiDuocYeuThich1.setLayout(topChuyenDiDuocYeuThich1Layout);
        topChuyenDiDuocYeuThich1Layout.setHorizontalGroup(
            topChuyenDiDuocYeuThich1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        topChuyenDiDuocYeuThich1Layout.setVerticalGroup(
            topChuyenDiDuocYeuThich1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        panelShadow1.add(topChuyenDiDuocYeuThich1);
        topChuyenDiDuocYeuThich1.setBounds(8, 5, 290, 180);

        add(panelShadow1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private raven2.panel.PanelShadow panelShadow1;
    private gui.components.TopChuyenDiDuocYeuThich topChuyenDiDuocYeuThich1;
    // End of variables declaration//GEN-END:variables
}
