/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.traCuu;

/**
 *
 * @author Laptopone
 */
public class TraCuuHanhKhach_GUI extends javax.swing.JPanel {

    /**
     * Creates new form TraCuuHanhKhach_GUI
     */
    public TraCuuHanhKhach_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnl_table = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_thongTinHanhKhach = new javax.swing.JTable();
        pnl_header = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        pnl_ga = new javax.swing.JPanel();
        lbl_maHK = new javax.swing.JLabel();
        txt_maHK = new javax.swing.JTextField();
        lbl_next2 = new javax.swing.JLabel();
        lbl_tenHK = new javax.swing.JLabel();
        txt_tenHK = new javax.swing.JTextField();
        lbl_next6 = new javax.swing.JLabel();
        lbl_cccd = new javax.swing.JLabel();
        txt_cccd = new javax.swing.JTextField();
        pnl_timKiem = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnTimKiem = new javax.swing.JButton();
        btnXoaTrang = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        pnl_table.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnl_table.setLayout(new javax.swing.BoxLayout(pnl_table, javax.swing.BoxLayout.LINE_AXIS));

        tbl_thongTinHanhKhach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã hành khách", "Tên hành khách", "CCCD", "Ngày sinh"
            }
        ));
        jScrollPane1.setViewportView(tbl_thongTinHanhKhach);

        pnl_table.add(jScrollPane1);

        add(pnl_table, java.awt.BorderLayout.CENTER);

        pnl_header.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnl_header.setPreferredSize(new java.awt.Dimension(1366, 200));
        pnl_header.setLayout(new java.awt.BorderLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin hành khách"), javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        pnl_ga.setMaximumSize(new java.awt.Dimension(65736, 70));
        pnl_ga.setMinimumSize(new java.awt.Dimension(1000, 25));
        pnl_ga.setPreferredSize(new java.awt.Dimension(100, 70));
        pnl_ga.setLayout(new javax.swing.BoxLayout(pnl_ga, javax.swing.BoxLayout.LINE_AXIS));

        lbl_maHK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_maHK.setText("Mã hành khách:");
        lbl_maHK.setPreferredSize(new java.awt.Dimension(110, 16));
        pnl_ga.add(lbl_maHK);

        txt_maHK.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        txt_maHK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maHKActionPerformed(evt);
            }
        });
        pnl_ga.add(txt_maHK);

        lbl_next2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_next2.setPreferredSize(new java.awt.Dimension(30, 16));
        pnl_ga.add(lbl_next2);

        lbl_tenHK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_tenHK.setText("Tên hành khách:");
        lbl_tenHK.setPreferredSize(new java.awt.Dimension(110, 25));
        pnl_ga.add(lbl_tenHK);

        txt_tenHK.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        pnl_ga.add(txt_tenHK);

        lbl_next6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_next6.setPreferredSize(new java.awt.Dimension(30, 16));
        pnl_ga.add(lbl_next6);

        lbl_cccd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_cccd.setText("Số CCCD:");
        lbl_cccd.setPreferredSize(new java.awt.Dimension(70, 20));
        pnl_ga.add(lbl_cccd);

        txt_cccd.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        pnl_ga.add(txt_cccd);

        jPanel5.add(pnl_ga);

        pnl_timKiem.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        pnl_timKiem.setMaximumSize(new java.awt.Dimension(32767, 60));
        pnl_timKiem.setLayout(new java.awt.BorderLayout());

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.setPreferredSize(new java.awt.Dimension(100, 40));
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        jPanel6.add(btnTimKiem);

        btnXoaTrang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoaTrang.setText("Xóa trắng");
        btnXoaTrang.setPreferredSize(new java.awt.Dimension(100, 40));
        btnXoaTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTrangActionPerformed(evt);
            }
        });
        jPanel6.add(btnXoaTrang);

        pnl_timKiem.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel5.add(pnl_timKiem);

        pnl_header.add(jPanel5, java.awt.BorderLayout.CENTER);

        add(pnl_header, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_maHKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maHKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maHKActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnXoaTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTrangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaTrangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoaTrang;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_cccd;
    private javax.swing.JLabel lbl_maHK;
    private javax.swing.JLabel lbl_next2;
    private javax.swing.JLabel lbl_next6;
    private javax.swing.JLabel lbl_tenHK;
    private javax.swing.JPanel pnl_ga;
    private javax.swing.JPanel pnl_header;
    private javax.swing.JPanel pnl_table;
    private javax.swing.JPanel pnl_timKiem;
    private javax.swing.JTable tbl_thongTinHanhKhach;
    private javax.swing.JTextField txt_cccd;
    private javax.swing.JTextField txt_maHK;
    private javax.swing.JTextField txt_tenHK;
    // End of variables declaration//GEN-END:variables
}
