/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.traCuu;

import bus.QuanLyNhanVien_BUS;
import entity.NhanVien;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CÔNG HOÀNG
 */
public class TraCuuNhanVien_GUI extends javax.swing.JPanel {
    
    private QuanLyNhanVien_BUS bus;
    private DefaultTableModel tblModel_thongtinNhanVien;

    /**
     * Creates new form TraCuuNhanVien
     */
    public TraCuuNhanVien_GUI() {
        initComponents();
        init();
    }
    
     private void init() {
    bus = new QuanLyNhanVien_BUS();
    tblModel_thongtinNhanVien = new DefaultTableModel(
    new String[]{"Mã NV","Họ tên","Giới tính","Ngày sinh","Email","SDT","CCCD","Địa chỉ","Chức vụ","Trạng thái"}, 0);
    tbl_thongTinNhanVien.setModel(tblModel_thongtinNhanVien);
    ArrayList<NhanVien> ds = bus.getAllNhanVien();
    getTableData(ds);
}

   
  
   private void getTableData(ArrayList<NhanVien> dsNV){
       tblModel_thongtinNhanVien.setRowCount(0);
       DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
       for(NhanVien nv : dsNV){
           String gioiTinhstr = nv.isGioiTinh() ? "Nam":"Nữ";
           String trangThaistr = nv.isTrangThai()?"Đang làm":"Đã nghỉ";
           String ngaySinhstr = "";
           if(nv.getNgaySinh() != null){
               ngaySinhstr = nv.getNgaySinh().format(formatter);
           }
           String[] newRow = {nv.getMaNV(),nv.getTenNV(),gioiTinhstr,ngaySinhstr,nv.getEmail(),nv.getSoDienThoai(),nv.getCccd(),nv.getDiaChi(),nv.getChucVu(),trangThaistr};
           tblModel_thongtinNhanVien.addRow(newRow);
       }
   }
   
    private void getThongTinNhanVien() {
     int row = tbl_thongTinNhanVien.getSelectedRow(); // Lấy dòng được chọn
     if (row != -1) {
         // Lấy dữ liệu từ từng cột trong bảng
         String maNV = tbl_thongTinNhanVien.getValueAt(row, 0).toString();
         String hoTen = tbl_thongTinNhanVien.getValueAt(row, 1).toString();
         String gioiTinh = tbl_thongTinNhanVien.getValueAt(row, 2).toString();
         String sdt = tbl_thongTinNhanVien.getValueAt(row, 5).toString();
         String cccd = tbl_thongTinNhanVien.getValueAt(row, 6).toString();
         String trangThai = tbl_thongTinNhanVien.getValueAt(row, 9).toString();

         // Gán dữ liệu lên các ô nhập
         txt_maNV.setText(maNV);
         txt_tenNV.setText(hoTen);
         txt_soDienThoai.setText(sdt);
         txt_cccd.setText(cccd);

         // Giới tính
         for (int i = 0; i < cbo_gioiTinh.getItemCount(); i++) {
             String item = cbo_gioiTinh.getItemAt(i).toString().trim();
             if (item.equalsIgnoreCase(gioiTinh)) {
                 cbo_gioiTinh.setSelectedIndex(i);
                 break;
             }
         }

         // Trạng thái
         for (int i = 0; i < cbo_trangThai.getItemCount(); i++) {
             String item = cbo_trangThai.getItemAt(i).toString().trim();
             if (item.equalsIgnoreCase(trangThai)) {
                 cbo_trangThai.setSelectedIndex(i);
                 break;
             }
         }
     }
 }
    private void handleActionXoaTrang() {
     // Bỏ chọn dòng trên bảng (nếu có)
     tbl_thongTinNhanVien.clearSelection();

     // Xóa nội dung các ô nhập liệu
     txt_maNV.setText("");
     txt_tenNV.setText("");
     txt_cccd.setText("");
     txt_soDienThoai.setText("");

     // Đặt lại combobox giới tính và trạng thái về lựa chọn đầu tiên
     if (cbo_gioiTinh.getItemCount() > 0) {
         cbo_gioiTinh.setSelectedIndex(0); // "Tất cả" hoặc "Nam"
     }

     if (cbo_trangThai.getItemCount() > 0) {
         cbo_trangThai.setSelectedIndex(0); // "Tất cả" hoặc "Đang làm"
     }

     // Đưa focus về ô đầu tiên
     txt_maNV.requestFocus();
 }
    
    private void handleActionTimKiem() {
       String maNV = txt_maNV.getText().trim();
        String tenNV = txt_tenNV.getText().trim();
        String cccd = txt_cccd.getText().trim();
        String sdt = txt_soDienThoai.getText().trim();
        String gioiTinh = cbo_gioiTinh.getSelectedItem().toString();
        String trangThai = cbo_trangThai.getSelectedItem().toString();

        getTableData(bus.timNhanVien(maNV, tenNV, cccd, sdt, gioiTinh, trangThai));
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_thongTinNhanVien = new javax.swing.JTable();
        pnl_header = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        pnl_ga = new javax.swing.JPanel();
        lbl_maNV = new javax.swing.JLabel();
        txt_maNV = new javax.swing.JTextField();
        lbl_next2 = new javax.swing.JLabel();
        lbl_tenNV = new javax.swing.JLabel();
        txt_tenNV = new javax.swing.JTextField();
        lbl_next6 = new javax.swing.JLabel();
        lbl_cccd = new javax.swing.JLabel();
        txt_cccd = new javax.swing.JTextField();
        pnl_ngay = new javax.swing.JPanel();
        lbl_soDienThoai = new javax.swing.JLabel();
        txt_soDienThoai = new javax.swing.JTextField();
        lbl_next5 = new javax.swing.JLabel();
        lbl_gioiTinh = new javax.swing.JLabel();
        cbo_gioiTinh = new javax.swing.JComboBox<>();
        lbl_next3 = new javax.swing.JLabel();
        lbl_trangThai = new javax.swing.JLabel();
        cbo_trangThai = new javax.swing.JComboBox<>();
        pnl_timKiem = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnTimKiem = new javax.swing.JButton();
        btn_xoaTrang = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        tbl_thongTinNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Họ tên", "Giới tính", "Ngày sinh", "Email", "SDT", "CCCD", "Địa chỉ ", "Chức vụ", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_thongTinNhanVien.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl_thongTinNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_thongTinNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_thongTinNhanVien);

        jPanel2.add(jScrollPane1);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        pnl_header.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnl_header.setPreferredSize(new java.awt.Dimension(1366, 250));
        pnl_header.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin nhân viên"), javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        pnl_ga.setMaximumSize(new java.awt.Dimension(65736, 70));
        pnl_ga.setMinimumSize(new java.awt.Dimension(1000, 25));
        pnl_ga.setPreferredSize(new java.awt.Dimension(100, 70));
        pnl_ga.setLayout(new javax.swing.BoxLayout(pnl_ga, javax.swing.BoxLayout.LINE_AXIS));

        lbl_maNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_maNV.setText("Mã nhân viên:");
        lbl_maNV.setPreferredSize(new java.awt.Dimension(100, 16));
        pnl_ga.add(lbl_maNV);

        txt_maNV.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        txt_maNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maNVActionPerformed(evt);
            }
        });
        pnl_ga.add(txt_maNV);

        lbl_next2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_next2.setPreferredSize(new java.awt.Dimension(30, 16));
        pnl_ga.add(lbl_next2);

        lbl_tenNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_tenNV.setText("Tên nhân viên:");
        lbl_tenNV.setPreferredSize(new java.awt.Dimension(100, 25));
        pnl_ga.add(lbl_tenNV);

        txt_tenNV.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        pnl_ga.add(txt_tenNV);

        lbl_next6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_next6.setPreferredSize(new java.awt.Dimension(30, 16));
        pnl_ga.add(lbl_next6);

        lbl_cccd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_cccd.setText("Số CCCD:");
        lbl_cccd.setPreferredSize(new java.awt.Dimension(70, 20));
        pnl_ga.add(lbl_cccd);

        txt_cccd.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        pnl_ga.add(txt_cccd);

        jPanel3.add(pnl_ga);

        pnl_ngay.setMaximumSize(new java.awt.Dimension(65679, 70));
        pnl_ngay.setMinimumSize(new java.awt.Dimension(1000, 25));
        pnl_ngay.setLayout(new javax.swing.BoxLayout(pnl_ngay, javax.swing.BoxLayout.LINE_AXIS));

        lbl_soDienThoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_soDienThoai.setText("Số điện thoại:");
        lbl_soDienThoai.setPreferredSize(new java.awt.Dimension(100, 16));
        pnl_ngay.add(lbl_soDienThoai);

        txt_soDienThoai.setMaximumSize(txt_maNV.getMaximumSize());
        txt_soDienThoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_soDienThoaiActionPerformed(evt);
            }
        });
        pnl_ngay.add(txt_soDienThoai);

        lbl_next5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_next5.setPreferredSize(new java.awt.Dimension(30, 16));
        pnl_ngay.add(lbl_next5);

        lbl_gioiTinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_gioiTinh.setText("Giới tính:");
        lbl_gioiTinh.setPreferredSize(new java.awt.Dimension(80, 25));
        pnl_ngay.add(lbl_gioiTinh);

        cbo_gioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Nam ", "Nữ" }));
        cbo_gioiTinh.setMaximumSize(new java.awt.Dimension(32767, 50));
        cbo_gioiTinh.setPreferredSize(new java.awt.Dimension(120, 22));
        cbo_gioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_gioiTinhActionPerformed(evt);
            }
        });
        pnl_ngay.add(cbo_gioiTinh);

        lbl_next3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_next3.setPreferredSize(new java.awt.Dimension(30, 16));
        pnl_ngay.add(lbl_next3);

        lbl_trangThai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_trangThai.setText("Trạng thái:");
        lbl_trangThai.setPreferredSize(new java.awt.Dimension(80, 25));
        pnl_ngay.add(lbl_trangThai);

        cbo_trangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Đang làm", "Đã nghỉ" }));
        cbo_trangThai.setMaximumSize(new java.awt.Dimension(32767, 50));
        cbo_trangThai.setPreferredSize(new java.awt.Dimension(120, 22));
        cbo_trangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_trangThaiActionPerformed(evt);
            }
        });
        pnl_ngay.add(cbo_trangThai);

        jPanel3.add(pnl_ngay);

        pnl_timKiem.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        pnl_timKiem.setMaximumSize(new java.awt.Dimension(32767, 60));
        pnl_timKiem.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.setPreferredSize(new java.awt.Dimension(100, 40));
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        jPanel4.add(btnTimKiem);

        btn_xoaTrang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_xoaTrang.setText("Xóa trắng");
        btn_xoaTrang.setPreferredSize(new java.awt.Dimension(100, 40));
        btn_xoaTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaTrangActionPerformed(evt);
            }
        });
        jPanel4.add(btn_xoaTrang);

        pnl_timKiem.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel3.add(pnl_timKiem);

        pnl_header.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(pnl_header, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void cbo_trangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_trangThaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_trangThaiActionPerformed

    private void txt_maNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maNVActionPerformed

    private void txt_soDienThoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_soDienThoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_soDienThoaiActionPerformed

    private void cbo_gioiTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_gioiTinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_gioiTinhActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        handleActionTimKiem();
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btn_xoaTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaTrangActionPerformed
        handleActionXoaTrang();
    }//GEN-LAST:event_btn_xoaTrangActionPerformed

    private void tbl_thongTinNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_thongTinNhanVienMouseClicked
       getThongTinNhanVien();
    }//GEN-LAST:event_tbl_thongTinNhanVienMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btn_xoaTrang;
    private javax.swing.JComboBox<String> cbo_gioiTinh;
    private javax.swing.JComboBox<String> cbo_trangThai;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_cccd;
    private javax.swing.JLabel lbl_gioiTinh;
    private javax.swing.JLabel lbl_maNV;
    private javax.swing.JLabel lbl_next2;
    private javax.swing.JLabel lbl_next3;
    private javax.swing.JLabel lbl_next5;
    private javax.swing.JLabel lbl_next6;
    private javax.swing.JLabel lbl_soDienThoai;
    private javax.swing.JLabel lbl_tenNV;
    private javax.swing.JLabel lbl_trangThai;
    private javax.swing.JPanel pnl_ga;
    private javax.swing.JPanel pnl_header;
    private javax.swing.JPanel pnl_ngay;
    private javax.swing.JPanel pnl_timKiem;
    private javax.swing.JTable tbl_thongTinNhanVien;
    private javax.swing.JTextField txt_cccd;
    private javax.swing.JTextField txt_maNV;
    private javax.swing.JTextField txt_soDienThoai;
    private javax.swing.JTextField txt_tenNV;
    // End of variables declaration//GEN-END:variables
}
