/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.traCuu;

import bus.QuanLyGaTau_BUS;
import bus.TraCuuGaTau_BUS;
import entity.GaTau;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CÔNG HOÀNG
 */
public class TraCuuGaTau_GUI extends javax.swing.JPanel {
    private TraCuuGaTau_BUS bus;
    private DefaultTableModel tblModel_thongTinGa;
    /**
     * Creates new form TraCuuGaTau_GUI
     */
    public TraCuuGaTau_GUI() {
        initComponents();
        init();
    }
    
    private void init() {
        bus = new TraCuuGaTau_BUS();
        
//      setModel
        tblModel_thongTinGa = new DefaultTableModel(new String[] {"Mã ga", "Tên ga", "Địa chỉ", "Số điện thoại"}, 0);
        tbl_thongTinGa.setModel(tblModel_thongTinGa);
        
        loadDataToTable(bus.getAllGaTau());
    }
    
    private void loadDataToTable(ArrayList<GaTau> dsGaTau) {
        tblModel_thongTinGa.setRowCount(0);
        for(GaTau gaTau : dsGaTau) {
            String[] newRow = {gaTau.getMaGa(), gaTau.getTenGa(), gaTau.getDiaChi(), gaTau.getSoDienThoai()};
            tblModel_thongTinGa.addRow(newRow);
        }
    }
    
    private void handleXoaTrang() {
        tbl_thongTinGa.clearSelection();
        loadDataToTable(bus.getAllGaTau());
        txt_maGa.setText("");
        txt_tenGa.setText("");
        txt_tinhThanh.setText("");
        txt_soDienThoai.setText("");
    }
    
    private void handleTimKiem() {
        String maGa = txt_maGa.getText().trim();
        String tenGa = txt_tenGa.getText().trim();
        String tinhThanh = txt_tinhThanh.getText().trim();
        String soDienThoai = txt_soDienThoai.getText().trim();
        
        loadDataToTable(bus.filter(maGa, tenGa, tinhThanh, soDienThoai));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_header = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnl_ga = new javax.swing.JPanel();
        lbl_maGa = new javax.swing.JLabel();
        txt_maGa = new javax.swing.JTextField();
        lbl_next1 = new javax.swing.JLabel();
        lbl_tenGa = new javax.swing.JLabel();
        txt_tenGa = new javax.swing.JTextField();
        pnl_ngay = new javax.swing.JPanel();
        lbl_tinhThanh = new javax.swing.JLabel();
        txt_tinhThanh = new javax.swing.JTextField();
        lbl_next2 = new javax.swing.JLabel();
        lbl_soDienThoai = new javax.swing.JLabel();
        txt_soDienThoai = new javax.swing.JTextField();
        pnl_timKiem = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btn_timKiem = new javax.swing.JButton();
        btn_xoaTrang = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_thongTinGa = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        pnl_header.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnl_header.setPreferredSize(new java.awt.Dimension(1366, 250));
        pnl_header.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin ga tàu"), javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        pnl_ga.setMaximumSize(new java.awt.Dimension(65736, 70));
        pnl_ga.setMinimumSize(new java.awt.Dimension(1000, 25));
        pnl_ga.setPreferredSize(new java.awt.Dimension(100, 70));
        pnl_ga.setLayout(new javax.swing.BoxLayout(pnl_ga, javax.swing.BoxLayout.LINE_AXIS));

        lbl_maGa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_maGa.setText("Mã ga:");
        lbl_maGa.setPreferredSize(new java.awt.Dimension(150, 16));
        pnl_ga.add(lbl_maGa);

        txt_maGa.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        pnl_ga.add(txt_maGa);

        lbl_next1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_next1.setPreferredSize(new java.awt.Dimension(60, 16));
        pnl_ga.add(lbl_next1);

        lbl_tenGa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_tenGa.setText("Tên ga:");
        lbl_tenGa.setPreferredSize(new java.awt.Dimension(100, 25));
        pnl_ga.add(lbl_tenGa);

        txt_tenGa.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        pnl_ga.add(txt_tenGa);

        jPanel2.add(pnl_ga);

        pnl_ngay.setMaximumSize(new java.awt.Dimension(65679, 70));
        pnl_ngay.setMinimumSize(new java.awt.Dimension(1000, 25));
        pnl_ngay.setLayout(new javax.swing.BoxLayout(pnl_ngay, javax.swing.BoxLayout.LINE_AXIS));

        lbl_tinhThanh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_tinhThanh.setText("Tỉnh/thành phố:");
        lbl_tinhThanh.setPreferredSize(new java.awt.Dimension(150, 25));
        pnl_ngay.add(lbl_tinhThanh);

        txt_tinhThanh.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        pnl_ngay.add(txt_tinhThanh);

        lbl_next2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_next2.setPreferredSize(new java.awt.Dimension(60, 16));
        pnl_ngay.add(lbl_next2);

        lbl_soDienThoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_soDienThoai.setText("Số điện thoại:");
        lbl_soDienThoai.setPreferredSize(new java.awt.Dimension(100, 25));
        pnl_ngay.add(lbl_soDienThoai);

        txt_soDienThoai.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        pnl_ngay.add(txt_soDienThoai);

        jPanel2.add(pnl_ngay);

        pnl_timKiem.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        pnl_timKiem.setMaximumSize(new java.awt.Dimension(32767, 60));
        pnl_timKiem.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btn_timKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_timKiem.setText("Tìm kiếm");
        btn_timKiem.setPreferredSize(new java.awt.Dimension(100, 40));
        btn_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timKiemActionPerformed(evt);
            }
        });
        jPanel3.add(btn_timKiem);

        btn_xoaTrang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_xoaTrang.setText("Xóa trắng");
        btn_xoaTrang.setPreferredSize(new java.awt.Dimension(100, 40));
        btn_xoaTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaTrangActionPerformed(evt);
            }
        });
        jPanel3.add(btn_xoaTrang);

        pnl_timKiem.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel2.add(pnl_timKiem);

        pnl_header.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(pnl_header, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.setLayout(new java.awt.BorderLayout());

        tbl_thongTinGa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã ga", "Tên ga", "Địa chỉ ", "Số điện thoại"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_thongTinGa.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl_thongTinGa.setShowGrid(true);
        jScrollPane1.setViewportView(tbl_thongTinGa);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timKiemActionPerformed
        // TODO add your handling code here:
        handleTimKiem();
    }//GEN-LAST:event_btn_timKiemActionPerformed

    private void btn_xoaTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaTrangActionPerformed
        // TODO add your handling code here:
        handleXoaTrang();
    }//GEN-LAST:event_btn_xoaTrangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_timKiem;
    private javax.swing.JButton btn_xoaTrang;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_maGa;
    private javax.swing.JLabel lbl_next1;
    private javax.swing.JLabel lbl_next2;
    private javax.swing.JLabel lbl_soDienThoai;
    private javax.swing.JLabel lbl_tenGa;
    private javax.swing.JLabel lbl_tinhThanh;
    private javax.swing.JPanel pnl_ga;
    private javax.swing.JPanel pnl_header;
    private javax.swing.JPanel pnl_ngay;
    private javax.swing.JPanel pnl_timKiem;
    private javax.swing.JTable tbl_thongTinGa;
    private javax.swing.JTextField txt_maGa;
    private javax.swing.JTextField txt_soDienThoai;
    private javax.swing.JTextField txt_tenGa;
    private javax.swing.JTextField txt_tinhThanh;
    // End of variables declaration//GEN-END:variables
}
