/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.traCuu;

import bus.TraCuuTau_BUS;
import entity.Tau;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CÔNG HOÀNG
 */
public class TraCuuTau_GUI extends javax.swing.JPanel {
    private TraCuuTau_BUS bus;
    private DefaultTableModel tblModel_thongTinTau;
    /**
     * Creates new form TraCuuTau_GUI
     */
    public TraCuuTau_GUI() {
        initComponents();
        init();
    }
    
    private void init() {
        bus = new TraCuuTau_BUS();
        String[] columns = {"Mã tàu", "Tên tàu", "Số lượng toa", "Sức chứa", "Trạng thái"};
        tblModel_thongTinTau = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tbl_thongTinTau.setModel(tblModel_thongTinTau);
        
        loadDataToTable(bus.getAllTau());
    }
    
    private void loadDataToTable(ArrayList<Tau> dsTau) {
        tblModel_thongTinTau.setRowCount(0);
        for(Tau tau : dsTau) {
            String[] newRow = {tau.getMaTau(), tau.getTenTau(), String.valueOf(tau.getSoToaTau()), tau.getTrangThai().getDisplayName()};
            tblModel_thongTinTau.addRow(newRow);
        }
    }
    
    private void handleTimKiem() {
        String maTau = txt_maTau.getText().trim();
        String tenTau = txt_tenTau.getText().trim();
        int trangThai = cbo_trangThai.getSelectedIndex();
        
        loadDataToTable(bus.timKiemTau(maTau, tenTau, trangThai));
    }
    
    private void handleXoaTrang() {
        txt_maTau.setText("");
        txt_tenTau.setText("");
        cbo_trangThai.setSelectedIndex(0);
        loadDataToTable(bus.getAllTau());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_header = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnl_ga = new javax.swing.JPanel();
        lbl_maTau = new javax.swing.JLabel();
        txt_maTau = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        lbl_tenTau = new javax.swing.JLabel();
        txt_tenTau = new javax.swing.JTextField();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        lbl_trangThai = new javax.swing.JLabel();
        cbo_trangThai = new javax.swing.JComboBox<>();
        pnl_timKiem = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnTimKiem = new javax.swing.JButton();
        btn_xoaTrang = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_thongTinTau = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        pnl_header.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnl_header.setPreferredSize(new java.awt.Dimension(1366, 200));
        pnl_header.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin tàu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(123, 17, 19)), javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10))); // NOI18N
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        pnl_ga.setMaximumSize(new java.awt.Dimension(65736, 70));
        pnl_ga.setMinimumSize(new java.awt.Dimension(1000, 25));
        pnl_ga.setPreferredSize(new java.awt.Dimension(100, 70));
        pnl_ga.setLayout(new javax.swing.BoxLayout(pnl_ga, javax.swing.BoxLayout.LINE_AXIS));

        lbl_maTau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_maTau.setText("Mã tàu:");
        lbl_maTau.setPreferredSize(new java.awt.Dimension(80, 16));
        pnl_ga.add(lbl_maTau);

        txt_maTau.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        pnl_ga.add(txt_maTau);
        pnl_ga.add(filler1);

        lbl_tenTau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_tenTau.setText("Tên tàu:");
        lbl_tenTau.setPreferredSize(new java.awt.Dimension(80, 25));
        pnl_ga.add(lbl_tenTau);

        txt_tenTau.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        pnl_ga.add(txt_tenTau);
        pnl_ga.add(filler2);

        lbl_trangThai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_trangThai.setText("Trạng thái:");
        lbl_trangThai.setPreferredSize(new java.awt.Dimension(80, 25));
        pnl_ga.add(lbl_trangThai);

        cbo_trangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Hoạt động", "Bảo trì", "Ngừng hoạt động" }));
        cbo_trangThai.setMaximumSize(txt_maTau.getMaximumSize());
        cbo_trangThai.setPreferredSize(txt_maTau.getPreferredSize());
        pnl_ga.add(cbo_trangThai);

        jPanel2.add(pnl_ga);

        pnl_timKiem.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        pnl_timKiem.setMaximumSize(new java.awt.Dimension(32767, 60));
        pnl_timKiem.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.setPreferredSize(new java.awt.Dimension(100, 40));
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        jPanel3.add(btnTimKiem);

        btn_xoaTrang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_xoaTrang.setText("Xóa trắng");
        btn_xoaTrang.setPreferredSize(new java.awt.Dimension(100, 40));
        btn_xoaTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaTrangActionPerformed(evt);
            }
        });
        jPanel3.add(btn_xoaTrang);

        pnl_timKiem.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel2.add(pnl_timKiem);

        pnl_header.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(pnl_header, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.setLayout(new java.awt.BorderLayout());

        tbl_thongTinTau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã tàu", "Tên tàu", "Số lượng toa", "Sức chứa", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_thongTinTau.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl_thongTinTau.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(tbl_thongTinTau);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        handleTimKiem();
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btn_xoaTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaTrangActionPerformed
        // TODO add your handling code here:
        handleXoaTrang();
    }//GEN-LAST:event_btn_xoaTrangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btn_xoaTrang;
    private javax.swing.JComboBox<String> cbo_trangThai;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_maTau;
    private javax.swing.JLabel lbl_tenTau;
    private javax.swing.JLabel lbl_trangThai;
    private javax.swing.JPanel pnl_ga;
    private javax.swing.JPanel pnl_header;
    private javax.swing.JPanel pnl_timKiem;
    private javax.swing.JTable tbl_thongTinTau;
    private javax.swing.JTextField txt_maTau;
    private javax.swing.JTextField txt_tenTau;
    // End of variables declaration//GEN-END:variables
}
