/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.traCuu;

import bus.QuanLyGaTau_BUS;
import bus.TraCuuChuyenTau_BUS;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import entity.ChuyenTau;
import entity.GaTau;
import java.awt.event.ItemEvent;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import raven.toast.Notifications;
import utils.FormatUtil;

/**
 *
 * @author CÔNG HOÀNG
 */
public class TraCuuChuyenTau_GUI extends javax.swing.JPanel {
    private TraCuuChuyenTau_BUS bus;
    private DefaultTableModel tblModel_thongTinChuyenTau;
    private String gaDi;
    private String gaDen;
    private LocalDate ngayDi;
    /**
     * Creates new form TraCuuChuyenTau
     */
    public TraCuuChuyenTau_GUI() {
        initComponents();
        init();
    }
    
    private void init() {
        bus = new TraCuuChuyenTau_BUS();
        
//      setModel
        tblModel_thongTinChuyenTau = new DefaultTableModel(new String[] {"Mã chuyến tàu", "Tàu", "Ga đi", "Ga đến", "Thòi gian đi", "Thòi gian đến", "Số ghế còn trống", "Giá vé"}, 0);
        tbl_thongTinChuyenTau.setModel(tblModel_thongTinChuyenTau);
        
        cbo_gaDi.addItemListener(e -> {
            if (e.getStateChange() == ItemEvent.SELECTED) { // chỉ xử lý khi có lựa chọn mới
                cbo_gaDen.removeAllItems();
                cbo_gaDen.addItem("---Chọn ga đến---");
                if (cbo_gaDi.getSelectedIndex() != 0) {
                    for(int i = 0; i < cbo_gaDi.getItemCount(); i++) {
                        if(i != cbo_gaDi.getSelectedIndex() && i != 0) {
                            cbo_gaDen.addItem(cbo_gaDi.getItemAt(i));
                        }
                    }
                    cbo_gaDen.setEnabled(true); // bật combobox ga đến khi ga đi đã chọn
                    gaDi = cbo_gaDi.getSelectedItem().toString();   
                } else {
                    cbo_gaDen.setEnabled(false); // tắt nếu người dùng chọn lại "--Chọn ga đi--"
                }
            }
        });
        
        cbo_gaDen.addItemListener(e -> {
            if (e.getStateChange() == ItemEvent.SELECTED) { // chỉ xử lý khi có lựa chọn mới
                if (cbo_gaDen.getSelectedIndex() != 0) {
                    gaDen = cbo_gaDen.getSelectedItem().toString();   
                }
            }
        });
        
        
        loadDataToTable(bus.getAllChuyenTau());
        loadDataToCbo();
    }
    
//  Load dữ liệu lên table
    private void loadDataToTable(ArrayList<ChuyenTau> dsChuyenTau) {
        tblModel_thongTinChuyenTau.setRowCount(0);
        for(ChuyenTau ct : dsChuyenTau) {
            String[] newRow = {ct.getMaChuyenTau(), ct.getTau().getMaTau() + "-" + ct.getTau().getTenTau(), ct.getTuyenDuong().getGaDi().getTenGa(),  ct.getTuyenDuong().getGaDen().getTenGa(),FormatUtil.formatDateTime(ct.getThoiGianDi()), 
                FormatUtil.formatDateTime(ct.getThoiGianDen()), String.valueOf(ct.getSoGheConTrong()), FormatUtil.formatCurrency(ct.getTuyenDuong().getQuangDuong() * ct.getTuyenDuong().getSoTienMotKm())};
            tblModel_thongTinChuyenTau.addRow(newRow);
        }
    }
    
    private void loadDataToCbo() {
        ArrayList<GaTau> dsGaTau = bus.getAllGaTau();
        
        for(GaTau gaTau : dsGaTau) {
            cbo_gaDi.addItem(gaTau.getTenGa());
        }
    }
    
    private void handleXoaTrang() {
        cbo_gaDi.setSelectedIndex(0);
        cbo_gaDen.setSelectedIndex(0);
        date_ngayDi.setDate(new Date());
        loadDataToTable(bus.getAllChuyenTau());
    }
    
    private void handleTimKiem() {
        try {
            ngayDi = date_ngayDi.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            if(cbo_gaDi.getSelectedIndex() == 0) {
                Notifications.getInstance().show(Notifications.Type.WARNING,
                        "Vui lòng chọn ga đi!");
                return;
            }
            
            if(cbo_gaDen.getSelectedIndex() == 0) {
                Notifications.getInstance().show(Notifications.Type.WARNING,
                        "Vui lòng chọn ga đến!");
                return;
            }
            
            loadDataToTable(bus.filter(gaDi, gaDen, ngayDi));
        } catch (Exception e) {
            Notifications.getInstance().show(Notifications.Type.ERROR,
                        e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_header = new javax.swing.JPanel();
        pnl_thongTinHanhTrinh = new javax.swing.JPanel();
        pnl_thongTin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbo_gaDi = new javax.swing.JComboBox<>();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jLabel3 = new javax.swing.JLabel();
        cbo_gaDen = new javax.swing.JComboBox<>();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        pnl_ngay = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        date_ngayDi = new com.toedter.calendar.JDateChooser();
        pnl_timKiem = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnTimKiem = new javax.swing.JButton();
        btn_xoaTrang = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_thongTinChuyenTau = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1366, 768));
        setLayout(new java.awt.BorderLayout());

        pnl_header.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnl_header.setPreferredSize(new java.awt.Dimension(1366, 200));
        pnl_header.setLayout(new java.awt.BorderLayout());

        pnl_thongTinHanhTrinh.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin hành trình"), javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));
        pnl_thongTinHanhTrinh.setMaximumSize(new java.awt.Dimension(65766, 150));
        pnl_thongTinHanhTrinh.setPreferredSize(new java.awt.Dimension(247, 150));
        pnl_thongTinHanhTrinh.setLayout(new javax.swing.BoxLayout(pnl_thongTinHanhTrinh, javax.swing.BoxLayout.Y_AXIS));

        pnl_thongTin.setMaximumSize(new java.awt.Dimension(65736, 70));
        pnl_thongTin.setMinimumSize(new java.awt.Dimension(1000, 25));
        pnl_thongTin.setPreferredSize(new java.awt.Dimension(100, 70));
        pnl_thongTin.setLayout(new javax.swing.BoxLayout(pnl_thongTin, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Ga đi:");
        jLabel1.setMaximumSize(new java.awt.Dimension(100, 16));
        jLabel1.setPreferredSize(new java.awt.Dimension(80, 16));
        pnl_thongTin.add(jLabel1);

        cbo_gaDi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Chọn ga đi---" }));
        cbo_gaDi.setMaximumSize(new java.awt.Dimension(32767, 50));
        pnl_thongTin.add(cbo_gaDi);
        pnl_thongTin.add(filler1);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Ga đến:");
        jLabel3.setPreferredSize(new java.awt.Dimension(80, 25));
        pnl_thongTin.add(jLabel3);

        cbo_gaDen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chọn ga đến---" }));
        cbo_gaDen.setEnabled(false);
        cbo_gaDen.setMaximumSize(new java.awt.Dimension(32767, 50));
        cbo_gaDen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_gaDenActionPerformed(evt);
            }
        });
        pnl_thongTin.add(cbo_gaDen);
        pnl_thongTin.add(filler2);

        pnl_ngay.setMaximumSize(new java.awt.Dimension(65679, 70));
        pnl_ngay.setMinimumSize(new java.awt.Dimension(1000, 25));
        pnl_ngay.setLayout(new javax.swing.BoxLayout(pnl_ngay, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Ngày đi:");
        jLabel4.setPreferredSize(new java.awt.Dimension(80, 25));
        pnl_ngay.add(jLabel4);

        date_ngayDi.setMaximumSize(cbo_gaDi.getMaximumSize());
        date_ngayDi.setMinimumSize(cbo_gaDi.getMinimumSize());
        pnl_ngay.add(date_ngayDi);

        pnl_thongTin.add(pnl_ngay);

        pnl_thongTinHanhTrinh.add(pnl_thongTin);

        pnl_timKiem.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        pnl_timKiem.setMaximumSize(new java.awt.Dimension(32767, 60));
        pnl_timKiem.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.setPreferredSize(new java.awt.Dimension(100, 40));
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        jPanel3.add(btnTimKiem);

        btn_xoaTrang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_xoaTrang.setText("Xóa trắng");
        btn_xoaTrang.setPreferredSize(new java.awt.Dimension(100, 40));
        btn_xoaTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaTrangActionPerformed(evt);
            }
        });
        jPanel3.add(btn_xoaTrang);

        pnl_timKiem.add(jPanel3, java.awt.BorderLayout.CENTER);

        pnl_thongTinHanhTrinh.add(pnl_timKiem);

        pnl_header.add(pnl_thongTinHanhTrinh, java.awt.BorderLayout.CENTER);

        add(pnl_header, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.setLayout(new java.awt.BorderLayout());

        tbl_thongTinChuyenTau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tàu", "Ngày đi", "Thời gian đi", "Ngày đến", "Thời gian đến", "Số lượng chỗ trống", "Giá vé"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_thongTinChuyenTau.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tbl_thongTinChuyenTau);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        handleTimKiem();
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btn_xoaTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaTrangActionPerformed
        // TODO add your handling code here:
        handleXoaTrang();
    }//GEN-LAST:event_btn_xoaTrangActionPerformed

    private void cbo_gaDenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_gaDenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_gaDenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btn_xoaTrang;
    private javax.swing.JComboBox<String> cbo_gaDen;
    private javax.swing.JComboBox<String> cbo_gaDi;
    private com.toedter.calendar.JDateChooser date_ngayDi;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnl_header;
    private javax.swing.JPanel pnl_ngay;
    private javax.swing.JPanel pnl_thongTin;
    private javax.swing.JPanel pnl_thongTinHanhTrinh;
    private javax.swing.JPanel pnl_timKiem;
    private javax.swing.JTable tbl_thongTinChuyenTau;
    // End of variables declaration//GEN-END:variables
}
