/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.traCuu;

import bus.QuanLyGaTau_BUS;
import bus.TraCuuChuyenTau_BUS;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import entity.GaTau;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CÔNG HOÀNG
 */
public class TraCuuChuyenTau_GUI extends javax.swing.JPanel {
    private TraCuuChuyenTau_BUS bus;
    private DefaultTableModel tblModel_thongTinChuyenTau;
    /**
     * Creates new form TraCuuChuyenTau
     */
    public TraCuuChuyenTau_GUI() {
        initComponents();
        init();
    }
    
    private void init() {
        bus = new TraCuuChuyenTau_BUS();
        
//      setModel
        tblModel_thongTinChuyenTau = new DefaultTableModel(new String[] {"Mã chuyến tàu", "Tàu", "Ngày đi", "Ngày đến", "Thòi gian đi", "Thòi gian đến", "Số ghế còn tróng", "Giá "}, 0);
        tbl_thongTinChuyenTau.setModel(tblModel_thongTinChuyenTau);
        
        
        loadDataToTable();
        loadDataToCbo();
    }
    
//  Load dữ liệu lên table
    private void loadDataToTable() {
        
    }
    
    private void loadDataToCbo() {
        ArrayList<GaTau> dsGaTau = bus.getAllGaTau();
        
        for(GaTau gaTau : dsGaTau) {
            cbo_gaDi.addItem(gaTau.getTenGa());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_header = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnl_ga = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbo_gaDi = new javax.swing.JComboBox<>();
        lbl_next1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbo_gaDen = new javax.swing.JComboBox<>();
        pnl_ngay = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        date_ngayDi = new com.toedter.calendar.JDateChooser();
        lbl_next2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cb_tau = new javax.swing.JComboBox<>();
        pnl_timKiem = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnTimKiem = new javax.swing.JButton();
        btn_xoaTrang = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_thongTinChuyenTau = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1366, 768));
        setLayout(new java.awt.BorderLayout());

        pnl_header.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnl_header.setPreferredSize(new java.awt.Dimension(1366, 250));
        pnl_header.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin hành trình"), javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        pnl_ga.setMaximumSize(new java.awt.Dimension(65736, 70));
        pnl_ga.setMinimumSize(new java.awt.Dimension(1000, 25));
        pnl_ga.setPreferredSize(new java.awt.Dimension(100, 70));
        pnl_ga.setLayout(new javax.swing.BoxLayout(pnl_ga, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Ga đi:");
        jLabel1.setMaximumSize(new java.awt.Dimension(100, 16));
        jLabel1.setPreferredSize(new java.awt.Dimension(80, 16));
        pnl_ga.add(jLabel1);

        cbo_gaDi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Chọn ga đi---" }));
        cbo_gaDi.setMaximumSize(new java.awt.Dimension(32767, 50));
        pnl_ga.add(cbo_gaDi);

        lbl_next1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_next1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/fast-forward.png"))); // NOI18N
        lbl_next1.setPreferredSize(new java.awt.Dimension(70, 16));
        pnl_ga.add(lbl_next1);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Ga đến:");
        jLabel3.setPreferredSize(new java.awt.Dimension(80, 25));
        pnl_ga.add(jLabel3);

        cbo_gaDen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chọn ga đến---" }));
        cbo_gaDen.setMaximumSize(new java.awt.Dimension(32767, 50));
        pnl_ga.add(cbo_gaDen);

        jPanel2.add(pnl_ga);

        pnl_ngay.setMaximumSize(new java.awt.Dimension(65679, 70));
        pnl_ngay.setMinimumSize(new java.awt.Dimension(1000, 25));
        pnl_ngay.setLayout(new javax.swing.BoxLayout(pnl_ngay, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Ngày đi:");
        jLabel4.setPreferredSize(new java.awt.Dimension(80, 25));
        pnl_ngay.add(jLabel4);

        date_ngayDi.setMaximumSize(cbo_gaDi.getMaximumSize());
        date_ngayDi.setPreferredSize(cbo_gaDi.getPreferredSize());
        pnl_ngay.add(date_ngayDi);

        lbl_next2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_next2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/fast-forward.png"))); // NOI18N
        lbl_next2.setPreferredSize(new java.awt.Dimension(70, 16));
        pnl_ngay.add(lbl_next2);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Tàu:");
        jLabel6.setPreferredSize(new java.awt.Dimension(80, 25));
        pnl_ngay.add(jLabel6);

        cb_tau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Chọn tàu---" }));
        cb_tau.setMaximumSize(new java.awt.Dimension(32767, 50));
        cb_tau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tauActionPerformed(evt);
            }
        });
        pnl_ngay.add(cb_tau);

        jPanel2.add(pnl_ngay);

        pnl_timKiem.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        pnl_timKiem.setMaximumSize(new java.awt.Dimension(32767, 60));
        pnl_timKiem.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.setPreferredSize(new java.awt.Dimension(100, 40));
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        jPanel3.add(btnTimKiem);

        btn_xoaTrang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_xoaTrang.setText("Xóa trắng");
        btn_xoaTrang.setPreferredSize(new java.awt.Dimension(100, 40));
        btn_xoaTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaTrangActionPerformed(evt);
            }
        });
        jPanel3.add(btn_xoaTrang);

        pnl_timKiem.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel2.add(pnl_timKiem);

        pnl_header.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(pnl_header, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.setLayout(new java.awt.BorderLayout());

        tbl_thongTinChuyenTau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tàu", "Ngày đi", "Thời gian đi", "Ngày đến", "Thời gian đến", "Số lượng chỗ trống", "Giá vé"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_thongTinChuyenTau.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tbl_thongTinChuyenTau);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void cb_tauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_tauActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btn_xoaTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaTrangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_xoaTrangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btn_xoaTrang;
    private javax.swing.JComboBox<String> cb_tau;
    private javax.swing.JComboBox<String> cbo_gaDen;
    private javax.swing.JComboBox<String> cbo_gaDi;
    private com.toedter.calendar.JDateChooser date_ngayDi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_next1;
    private javax.swing.JLabel lbl_next2;
    private javax.swing.JPanel pnl_ga;
    private javax.swing.JPanel pnl_header;
    private javax.swing.JPanel pnl_ngay;
    private javax.swing.JPanel pnl_timKiem;
    private javax.swing.JTable tbl_thongTinChuyenTau;
    // End of variables declaration//GEN-END:variables
}
