/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.help;

import java.io.IOException;
import java.io.InputStream;
import javax.swing.text.Document;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import javax.swing.text.rtf.RTFEditorKit;

/**
 *
 * @author CÔNG HOÀNG
 */
public class TroGiup_GUI extends javax.swing.JPanel {

    /**
     * Creates new form TroGiup_GUI
     */
    public TroGiup_GUI() {
        initComponents();
        
        jTextPane1.setEditable(false);
        loadRTFFile("TroGiup.rtf");
    }
    private void loadRTFFile(String fileName) {
        try {
            RTFEditorKit rtfKit = new RTFEditorKit();
            jTextPane1.setEditorKit(rtfKit);
            //jTextPane1.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 30)); // Font mặc định
            Document doc = jTextPane1.getDocument();
            InputStream is = getClass().getResourceAsStream(fileName);
            if (is == null) {
                throw new IOException("File không tìm thấy: " + fileName);
            }
            rtfKit.read(is, doc, 0);
            is.close();

            // Áp dụng thụt lề đầu dòng
            StyledDocument styledDoc = jTextPane1.getStyledDocument();
            SimpleAttributeSet indent = new SimpleAttributeSet();
            StyleConstants.setFirstLineIndent(indent, 20f); // Thụt lề 20 pixel
            styledDoc.setParagraphAttributes(0, styledDoc.getLength(), indent, false);

        } catch (IOException | javax.swing.text.BadLocationException e) {
            e.printStackTrace();
            jTextPane1.setText("Lỗi khi tải file RTF: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(jTextPane1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
