/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.custom;

/**
 *
 * @author CÔNG HOÀNG
 */
public class ChonChuyenTau extends javax.swing.JPanel {

    /**
     * Creates new form ChonChuyenTau
     */
    public ChonChuyenTau() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_dsChuyenTau = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel10 = new javax.swing.JPanel();
        panelShadow6 = new gui.custom.PanelShadow();
        lbl_maTau = new javax.swing.JLabel();
        filler14 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        jPanel14 = new javax.swing.JPanel();
        lbl_thoiGianDi = new javax.swing.JLabel();
        lbl_gaDi = new javax.swing.JLabel();
        filler15 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jPanel18 = new javax.swing.JPanel();
        lbl_thoiGianDen = new javax.swing.JLabel();
        lbl_gaDen = new javax.swing.JLabel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jPanel19 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        lbl_soGheDaDat = new javax.swing.JLabel();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jPanel21 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        lbl_soGheConTrong = new javax.swing.JLabel();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        btn_chon = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        pnl_dsChuyenTau.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));
        pnl_dsChuyenTau.setPreferredSize(new java.awt.Dimension(250, 400));
        pnl_dsChuyenTau.setLayout(new java.awt.BorderLayout());

        jPanel20.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 4, 10, 0));
        jPanel20.setLayout(new java.awt.GridLayout());

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel31.setText("Chọn chuyến tàu");
        jPanel20.add(jLabel31);

        pnl_dsChuyenTau.add(jPanel20, java.awt.BorderLayout.PAGE_START);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel10.setPreferredSize(null);
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.Y_AXIS));

        panelShadow6.setBackground(new java.awt.Color(255, 255, 255));
        panelShadow6.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 30, 0, 30));
        panelShadow6.setMaximumSize(new java.awt.Dimension(32767, 90));
        panelShadow6.setMinimumSize(new java.awt.Dimension(881, 90));
        panelShadow6.setPreferredSize(new java.awt.Dimension(780, 90));
        panelShadow6.setShadowOpacity(0.2F);
        panelShadow6.setShadowSize(4);
        panelShadow6.setLayout(new javax.swing.BoxLayout(panelShadow6, javax.swing.BoxLayout.LINE_AXIS));

        lbl_maTau.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_maTau.setText("SE1");
        panelShadow6.add(lbl_maTau);
        panelShadow6.add(filler14);

        jPanel14.setMaximumSize(new java.awt.Dimension(32767, 50));
        jPanel14.setLayout(new java.awt.GridLayout(2, 1));

        lbl_thoiGianDi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_thoiGianDi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_thoiGianDi.setText("Thời gian đi: 20/10/2025 07:00");
        jPanel14.add(lbl_thoiGianDi);

        lbl_gaDi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_gaDi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_gaDi.setText("Sài Gòn");
        jPanel14.add(lbl_gaDi);

        panelShadow6.add(jPanel14);
        panelShadow6.add(filler15);

        jPanel18.setMaximumSize(new java.awt.Dimension(32767, 50));
        jPanel18.setLayout(new java.awt.GridLayout(2, 1));

        lbl_thoiGianDen.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_thoiGianDen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_thoiGianDen.setText("Thời gian đến: 21/10/2025 07:00");
        jPanel18.add(lbl_thoiGianDen);

        lbl_gaDen.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_gaDen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_gaDen.setText("Hà Nội");
        jPanel18.add(lbl_gaDen);

        panelShadow6.add(jPanel18);
        panelShadow6.add(filler9);

        jPanel19.setMaximumSize(new java.awt.Dimension(32767, 50));
        jPanel19.setLayout(new java.awt.GridLayout(2, 1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Số ghế đã đặt");
        jPanel19.add(jLabel23);

        lbl_soGheDaDat.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_soGheDaDat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_soGheDaDat.setText("0");
        jPanel19.add(lbl_soGheDaDat);

        panelShadow6.add(jPanel19);
        panelShadow6.add(filler10);

        jPanel21.setMaximumSize(new java.awt.Dimension(32767, 50));
        jPanel21.setLayout(new java.awt.GridLayout(2, 1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Số ghế còn trống");
        jPanel21.add(jLabel25);

        lbl_soGheConTrong.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_soGheConTrong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_soGheConTrong.setText("236");
        jPanel21.add(lbl_soGheConTrong);

        panelShadow6.add(jPanel21);
        panelShadow6.add(filler11);

        btn_chon.setText("Chọn");
        btn_chon.setMaximumSize(new java.awt.Dimension(72, 40));
        btn_chon.setPreferredSize(new java.awt.Dimension(100, 40));
        panelShadow6.add(btn_chon);

        jPanel10.add(panelShadow6);

        jScrollPane3.setViewportView(jPanel10);

        jPanel12.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        pnl_dsChuyenTau.add(jPanel12, java.awt.BorderLayout.CENTER);

        add(pnl_dsChuyenTau, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_chon;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler14;
    private javax.swing.Box.Filler filler15;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_gaDen;
    private javax.swing.JLabel lbl_gaDi;
    private javax.swing.JLabel lbl_maTau;
    private javax.swing.JLabel lbl_soGheConTrong;
    private javax.swing.JLabel lbl_soGheDaDat;
    private javax.swing.JLabel lbl_thoiGianDen;
    private javax.swing.JLabel lbl_thoiGianDi;
    private gui.custom.PanelShadow panelShadow6;
    private javax.swing.JPanel pnl_dsChuyenTau;
    // End of variables declaration//GEN-END:variables
}
